### ISSUE TITLE
rootless: /etc/sub{uid,gid} in OpenShift is tricky

### ISSUE THREAD

**Issue by TomasTomecek** [containers/libpod#1092]
I'm trying to run rootless podman in an OpenShift pod (so we can do scalable analysis of container images; current implementation uses `atomic --storage ostree` and skopeo).

The thing is that with OpenShift's anyuid feature it's not easy to predict the uid. `nss_wrapper` is being used as a solution to this problem.

Minimal reproducer:
```
#!/bin/bash
set -ex

CONT=cont
IMAGE=rootless-podman

podman stop $CONT || :
podman rm -f $CONT || :

podman pull registry.fedoraproject.org/fedora:29
podman run --net host -d --name $CONT registry.fedoraproject.org/fedora:29 sleep 99999
podman exec $CONT dnf install -y podman
podman exec $CONT useradd podm
podman exec $CONT bash -c 'printf "podm:1000:9999" >/etc/subuid && cp /etc/subuid /etc/subgid'
podman stop $CONT
podman commit $CONT $IMAGE
podman rm $CONT
# this is how openshift creates the default pod
# https://github.com/containers/libpod/issues/1092#issuecomment-437962358
# --net host for sake of not having networking issues; sometimes dnf can't sync a repo
podman run --net host --cap-drop=setuid --cap-drop=setgid --cap-drop=kill --cap-drop=mknod --name=$CONT -u podm $IMAGE podman --log-level=debug --storage-driver=vfs pull fedora:29
```

So I did this:
```
$ top -n 2 ./passwd
root:x:0:0:root:/root:/bin/bash
user:x:1000070000:1000070000:user:/src:/bin/bash
```

```
export LD_PRELOAD=libnss_wrapper.so
export NSS_WRAPPER_PASSWD="${PWD}/passwd"
export NSS_WRAPPER_GROUP=/etc/group
```

and then created
```
$ cat /etc/sub{uid,gid}
user:231072:65536
user:231072:65536
```

I'm still getting the same error message from podman:
```
bash-4.4$ id -u
1000070000

bash-4.4$ /src/podman --root $PWD/r/ pull docker.io/library/busybox
...
ERRO[0005] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: lchown /home: invalid argument
Failed

bash-4.4$ pwd
/var/tmp
bash-4.4$ ls -lha
total 16K
drwxrwxrwt. 1 root  root   27 Jul 13 14:59 .
drwxr-xr-x. 1 root  root   16 Apr 26 13:03 ..
-rw-r--r--. 1 user  root  829 Jul 13 14:54 passwd
drwxr-xr-x. 9 user  root 4.0K Jul 13 14:51 r
```

**Comment by giuseppe** [comment]
the busybox image has files owned by different users (not only root), so containers/storage tries to chown them with some uids/gids != 0.
I believe that podman has still only one uid available inside the user namespace, and after https://github.com/projectatomic/libpod/pull/1097 it will just fail to start.

**Comment by TomasTomecek** [comment]
Okay, I'll try again with the patch and with a different image.

**Comment by rhatdan** [comment]
Patch has been merged.

**Comment by TomasTomecek** [comment]
Sadly it still doesn't work. It seems that podman doesn't respect the nss_wrapper setup:
```
bash-4.4$ id
uid=1000070000(podm) gid=0(root) groups=0(root),1000070000

bash-4.4$ getent passwd podm
podm:x:1000070000:0:podm:/src:/bin/bash

bash-4.4$ podman
ERRO[0000] No subuid ranges found for user ""

bash-4.4$ cat /etc/subuid
podm:231072:65536

bash-4.4$ cat /etc/subgid
podm:231072:65536
```

I prepared a repo with my complete setup: https://github.com/TomasTomecek/rootless-podman-in-openshift

**Comment by giuseppe** [comment]
is the env variable `$USER` set correctly?

**Comment by rhatdan** [comment]
Does user.Lookupid(UIDString) do the right thing in the golang libraries?

**Comment by TomasTomecek** [comment]
It's definitely not. Trying it now right now. Will edit this comment with results.

**Comment by rhatdan** [comment]
@TomasTomecek We need to handle the error where USER is not set, we need to to a lookup.  Lets not loose that part of the issue.

**Comment by giuseppe** [comment]
> We need to handle the error where USER is not set, we need to to a lookup. Lets not loose that part of the issue.

I've opened a PR here: https://github.com/projectatomic/libpod/pull/1217

**Comment by TomasTomecek** [comment]
I tried this with latest releases:
```
podman-0.8.5-1.gitdc5a711.fc28.x86_64
origin 3.10
kernel-4.18.5-300.fc29.x86_64
```
and am still stuck on the `lchown /home: invalid argument`

**Comment by giuseppe** [comment]
we may be hitting this issue: https://github.com/genuinetools/img/issues/170

**Comment by TomasTomecek** [comment]
Giuseppe, I can see that both patches of yours for shadow were merged. When can we expect a build of podman built with them to try this out?

**Comment by giuseppe** [comment]
they are not going to be distributed with podman.  They are distributed as part of shadow-utils, @t8m might know better. 
For a test though, you could probably build a new image with shadow-utils built from upstream

**Comment by t8m** [comment]
If the solution for the issue is to ship the newuidmap and newgidmap utilities with CAP_SETUID fscap instead of them being simply setuid root, I can prepare the shadow-utils update for Fedora 29 soon.

**Comment by TomasTomecek** [comment]
@t8m awesome, that would be super helpful; I'll update my laptop to F29 in the meantime

**Comment by giuseppe** [comment]
> If the solution for the issue is to ship the newuidmap and newgidmap utilities with CAP_SETUID fscap instead of them being simply setuid root, I can prepare the shadow-utils update for Fedora 29 soon.

no that is not needed.  There is also a fix that will enable the feature when installed as a suid binary without changing file caps

**Comment by t8m** [comment]
@giuseppe But I prefer the fscaps solution to the problem as it does not require changing the code and actually gives the binaries only the capability that it needs.

**Comment by TomasTomecek** [comment]
Hm, so how can we test the proposed solution?

**Comment by t8m** [comment]
@TomasTomecek  can you please open a Fedоra bug against shadow-utils?

**Comment by TomasTomecek** [comment]
Okay, I won't be able to come up with a minimal reproducer: openshift is very strict in this space and the minimal reproducer would not correspond to the openshift environment. Anyway, I rerun my testing and here are my findings:
```
[podm@podman-in-okd-20181108t165009822581 /]$ podman --storage-driver=vfs pull fedora:29
Trying to pull docker.io/fedora:29...Getting image source signatures
Copying blob sha256:d0483bd5a55488f5ba6383a5cc8553d5101864f03acd07eabc5df7563c3692cf
 83.23 MB / 83.23 MB [=====================================================] 34s
Copying config sha256:8c568f1043264e34f0a8774587266565c7e5e54e9ea6b97ab459086d18ac5175
 2.29 KB / 2.29 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
ERRO[0040] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: lchown /run/systemd/netif: invalid argument   
```

Still the same error, just different directory. @t8m: Tome, once there is a build of shadow-utils with the patches from Giuseppe, please let me know and I'll try this again.

**Comment by t8m** [comment]
@TomasTomecek Are you sure that the fixed shadow-utils are in place? What is the kernel of the host?

**Comment by TomasTomecek** [comment]
@t8m this is F29, so 4.18. I'm 100% sure that updated shadow-utils are not there (since you haven't touched that bug I presumed there is still no build in koji: I can pick up the latest build from koji and try again).

**Comment by TomasTomecek** [comment]
Sadly, still the same error.
```
[podm@podman-in-okd-20181112t130610199320 /]$ podman --storage-driver=vfs pull fedora:29
Trying to pull docker.io/fedora:29...Getting image source signatures
Copying blob sha256:d0483bd5a55488f5ba6383a5cc8553d5101864f03acd07eabc5df7563c3692cf
 83.23 MB / 83.23 MB [======================================================] 3s
Copying config sha256:8c568f1043264e34f0a8774587266565c7e5e54e9ea6b97ab459086d18ac5175
 2.29 KB / 2.29 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
ERRO[0007] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: lchown /run/systemd/netif: invalid argument
Failed

[podm@podman-in-okd-20181112t130610199320 /]$ ls -lha /run/systemd/netif                                                        
total 0
drwxr-xr-x. 4 root root  33 Sep  6 03:00 .
drwxr-xr-x. 9 root root 113 Sep  6 03:00 ..
drwxr-xr-x. 2 root root   6 Sep  6 03:00 leases
drwxr-xr-x. 2 root root   6 Sep  6 03:00 links
[podm@podman-in-okd-20181112t130610199320 /]$ ls -lha /run/systemd/
total 0
drwxr-xr-x. 9 root root 113 Sep  6 03:00 .
drwxr-xr-x. 1 root root  48 Nov  8 15:32 ..
drwxr-xr-x. 2 root root   6 Sep  6 03:00 ask-password
drwxr-xr-x. 2 root root   6 Sep  6 03:00 machines
drwxr-xr-x. 4 root root  33 Sep  6 03:00 netif
drwxr-xr-x. 2 root root   6 Sep  6 03:00 seats
drwxr-xr-x. 2 root root   6 Sep  6 03:00 sessions
drwxr-xr-x. 2 root root   6 Sep  6 03:00 shutdown
drwxr-xr-x. 2 root root   6 Sep  6 03:00 users
```
I am using the newest podman and shadow-utils:
```
shadow-utils-4.6-4.fc29.x86_64
podman-0.11.1-1.gita4adfe5.fc29.x86_64
```

```
[podm@podman-in-okd-20181112t141546420819 /]$ podman info                                                                                                                                                   [2/521]
host:                          
  BuildahVersion: 1.5-dev
  Conmon:                                            
    package: podman-0.11.1-1.gita4adfe5.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 8967a1d691ed44896b81ad48c863033f23c65eb0-dirty'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 201998336
  MemTotal: 16695848960
  OCIRuntime:
    package: runc-1.0.0-57.dev.git9e5aa74.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc5+dev
      commit: ff195010cbfd3c62a98a3fd2f7a1e1594afdda1a
      spec: 1.0.1-dev
  SwapFree: 17172000768
  SwapTotal: 17179865088
  arch: amd64
  cpus: 8
  hostname: podman-in-okd-20181112t141546420819
  kernel: 4.18.17-300.fc29.x86_64
  os: linux
  uptime: 40m 54.03s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/podm/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /tmp/user/1000140000
```
