### ISSUE TITLE
`podman create --mac-address` doesn't work

### ISSUE THREAD

**Issue by runiq** [containers/libpod#1136]
/kind bug

**Description**

The `--mac-address` switch to `podman create`/`podman run` doesn't work.

**Steps to reproduce the issue:**

```
# podman run --rm -it --mac-address=02:23:45:67:89:ab registry.fedoraproject.org/fedora-minimal:28 cat /sys/class/net/eth0/address
0a:58:0a:58:01:5a
```

**Describe the results you received:**

An automatically-assigned MAC address.

**Describe the results you expected:**

The MAC address I specifiied in the argument.

**Output of `podman version`:**

```
Version:       0.7.2
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

<details>
<summary>Output of `podman info`</summary>

```
host:
  MemFree: 8406614016
  MemTotal: 16652193792
  SwapFree: 8398041088
  SwapTotal: 8398041088
  arch: amd64
  cpus: 4
  hostname: trabajo.itz.uni-halle.de
  kernel: 4.17.6-200.fc28.x86_64
  os: linux
  uptime: 20m 9.95s
insecure registries:
  registries:
  - trabajo.itz.uni-halle.de:5000
registries:
  registries:
  - trabajo.itz.uni-halle.de:5000
  - registry.fedoraproject.org
  - docker.io
store:
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/ajaam/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /run/user/29574/run
```

</details>

**Additional environment details (AWS, VirtualBox, physical, etc.):**

<details>
<summary>Contents of /etc/cni/net.d/87-podman-bridge.conflist</summary>

```
{
    "cniVersion": "0.3.0",
    "name": "podman",
    "plugins": [
      {
        "type": "bridge",
        "bridge": "cni0",
        "isGateway": true,
        "ipMasq": true,
        "ipam": {
            "type": "host-local",
            "subnet": "10.88.0.0/16",
            "routes": [
                { "dst": "0.0.0.0/0" }
            ]
        }
      },
      {
        "type": "portmap",
        "capabilities": {
          "portMappings": true
        }
      }
    ]
}
```

</details>
