### ISSUE TITLE
Rootless build: cannot specify gid= mount options for unmapped gid in rootless containers

### ISSUE THREAD

**Issue by aengelke** [containers/libpod#1147]
> /kind bug

*Note: I'm unsure whether this is a bug in buildah or podman. Please tell if I should file another bug report against buildah.*

**Description**

Consider this simple Dockerfile:
```
FROM fedora:28
RUN dnf -y update
```

Using `podman --log-level=debug build .` fails with `cannot specify gid= mount options for unmapped gid in rootless containers`, [logs here](https://home.in.tum.de/~engelke/raw/podman.3.log). (Note: the logs are copy-pasted from the terminal, if I redirect stderr, podman just hangs right before the error.)

**Steps to reproduce the issue:**

See above.

**Describe the results you received:**

`cannot specify gid= mount options for unmapped gid in rootless containers`

**Describe the results you expected:**

A successful build.

**Output of `podman version`:**

```
Version:       0.7.2
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
<snip>
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 4
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /var/home/engelke/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 2
  RunRoot: /run/user/1000/run
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Operating system if Fedora Atomic Workstation `28.20180723.0`.
