### ISSUE TITLE
"could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH"

### ISSUE THREAD

**Issue by lukasheinrich** [containers/libpod#1234]
/kind bug

**Description**

running rootless containers, podman tries to setup rootless networking via `slirp4netns` and throws an error if it's not available. The container proceeds to run as expected, so I think slirp4netns is an optional dependency (for now).

**Describe the results you received:**

```
[vagrant@localhost ~]$ podman run --rm -it busybox echo hello world
ERRO[0000] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH 
hello world
```

**Describe the results you expected:**

no error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 0.8.1
```

**Output of `podman info`:**

```
host:
  MemFree: 239022080
  MemTotal: 504094720
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  hostname: localhost.localdomain
  kernel: 4.16.3-301.fc28.x86_64
  os: linux
  uptime: 13h 30m 13.93s (Approximately 0.54 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/vagrant/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /run/user/1000/run
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
fedora 28 vagrant box with SELinux fixes as discussed in #1118
