### ISSUE TITLE
podman --help says wrong defaults

### ISSUE THREAD

**Issue by fkluknav** [containers/libpod#1292]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**Description**

**Steps to reproduce the issue:**

1. podman --help
...
--cgroup-manager value            cgroup manager to use (cgroupfs or systemd, default cgroupfs)

2. podman -storage-driver=vfs run -ti fedora sh  (inside a docker container)
container create failed: systemd cgroup flag passed, but systemd support for managing cgroups is not available
: internal libpod error

3. exit the inner container

4. podman -storage-driver=vfs --cgroup-manager=cgroupfs run -ti fedora sh
works

**Describe the results you received:**
It seems that cgroupfs is not the default.

**Describe the results you expected:**
podman --help telling the truth about defaults

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 0.8.2.1
```

**Output of `podman info`:**

```
could not get runtime: database graph driver name vfs does not match our graph driver name overlay: database configuration mismatch
```
```
podman -storage-driver=vfs info
host:
  Conmon:
    package: podman-0.8.2.1-1.gitf38eb4f.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: baa69faf02175231d7cefde331368f2b5b1eac43-dirty'
  MemFree: 470286336
  MemTotal: 16430018560
  OCIRuntime:
    package: runc-1.0.0-46.dev.gitb4e2ecb.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 19325939712
  SwapTotal: 19327348736
  arch: amd64
  cpus: 4
  hostname: 0b8c10b6f567
  kernel: 4.16.11-100.fc26.x86_64
  os: linux
  uptime: 311h 11m 46.52s (Approximately 12.96 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 4
  GraphDriverName: vfs
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```
