### ISSUE TITLE
podman run not displaying output from commands

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#1304]
/kind bug

**Description**
When doing a podman run command that has a command at the end of it, the output from the container is not displayed on the calling terminal.  These commands were run as root.

**Steps to reproduce the issue:**

1.  image=$(podman pull fedora)

2. podman run $image ls -alF /etc

**Describe the results you received:**

A slight pause and then a return to the command line prompt.

**Describe the results you expected:**

A listing of the container's /etc directory.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:       0.8.3
Go Version:    go1.10.3
OS/Arch:       linux/amd64

```

**Output of `podman info`:**

```
# podman info
host:
  Conmon:
    package: podman-0.8.3-1.git9d09a4d.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: c72f69ce3f3fd7e46dced78dd99b67ab5441441e-dirty'
  MemFree: 1039663104
  MemTotal: 2089201664
  OCIRuntime:
    package: runc-1.0.0-46.dev.gitb4e2ecb.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 1
  hostname: localhost.localdomain
  kernel: 4.17.14-202.fc28.x86_64
  os: linux
  uptime: 37m 46.07s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Run as root on a VM running a fully updated Fedora 28 machine as of 8/20/18
