### ISSUE TITLE
 docker and podman have different semantics around non existing host volumes

### ISSUE THREAD

**Issue by mbaldessari** [containers/libpod#1324]
/kind bug
**Description**

I don't know yet how this discrepancy will hit us in openstack, but since I noticed it, I thought it is at least worth reporting.

A) docker
```
$ ls -l /non-existant
ls: cannot access '/non-existant': No such file or directory
$ sudo docker run --name=test20 --net=host --user=root --rm -v /non-existant:/mnt/foo -it docker.io/centos /bin/sh -c 'mount|grep -i mnt; ls -lR /mnt'                                                        2 ↵
/dev/mapper/fedora_holtby-root on /mnt/foo type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/mnt:
total 0
drwxr-xr-x. 2 root root 6 Aug 22 18:54 foo

/mnt/foo:
total 0
```

I.e. somehow docker creates the non existing folder
```
$ ls -la /non-existant
total 0
drwxr-xr-x.  2 root root   6 Aug 22 20:54 .
dr-xr-xr-x. 18 root root 244 Aug 22 20:54 ..
```

B) podman
```
$ sudo rm -rf /non-existant
$ podman run --name=test20 --net=host --user=root --rm -v /non-existant:/mnt/foo -it docker.io/centos /bin/sh -c 'mount|grep -i mnt; ls -lR /mnt'
error checking path "/non-existant": stat /non-existant: no such file or directory
```

**Output of `podman version`:**

```
Version:       0.8.3
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.8.3-4.git9d09a4d.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 137533eb357b85f97b0dc9900326754c807901b6-dirty'
  MemFree: 1094594560
  MemTotal: 16690200576
  OCIRuntime:
    package: runc-1.0.0-46.dev.gitb4e2ecb.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  hostname: holtby
  kernel: 4.18.1-300.fc29.x86_64
  os: linux
  uptime: 11h 6m 52.41s (Approximately 0.46 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 10
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/michele/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 2
  RunRoot: /run/user/1000/run
```
