### ISSUE TITLE
Rootless 'podman stop' fails with containers that are both privileged and have "host" networking

### ISSUE THREAD

**Issue by debarshiray** [containers/libpod#1351]
/kind bug

**Description**

This is a continuation of #1313 and #1329.

I have a script like this to create a container called `fedora-toolbox-rishi:28`:
```
#!/bin/sh

toolbox_container="fedora-toolbox-$USER:28"

base_toolbox_image="registry.fedoraproject.org/fedora:28"
toolbox_image="fedora-toolbox-$USER:28"
working_container_name="fedora-toolbox-$USER-working-container"

buildah images --noheading | grep --quiet $toolbox_image
if [[ $? -eq 1 ]]; then
  buildah from --name $working_container_name $base_toolbox_image
  buildah containers --noheading | grep --quiet $working_container_name
  [[ $? -eq 1 ]] && echo "Failed to create working container" && exit 1

  buildah run $working_container_name -- useradd \
      --no-create-home \
      --uid $UID \
      --groups wheel \
      $USER
  buildah config --volume $HOME $working_container_name
  buildah config --volume /run/user/$UID $working_container_name

  buildah config --user $USER $working_container_name
  buildah config --workingdir $HOME $working_container_name

  buildah commit --rm $working_container_name $toolbox_image
fi

podman create \
    --hostname toolbox \
    --interactive \
    --name $toolbox_container \
    --network host \
    --privileged \
    --security-opt label=disable \
    --tty \
    --volume $HOME:$HOME \
    --volume /run/user/$UID:/run/user/$UID \
    $toolbox_image
```

This is what happens when I used it to create the container, started it, and tried to stop it:
```
$ ./toolbox-create 
6f47c9f04776a8359047a50b50224e89384873cb0deb2930a4d8557a960bc54e
$ podman start fedora-toolbox-rishi:28 
fedora-toolbox-rishi:28
$ podman stop fedora-toolbox-rishi:28
container_linux.go:377: signaling init process caused "operation not permitted"
failed to stop container 6f47c9f04776a8359047a50b50224e89384873cb0deb2930a4d8557a960bc54e: operation not permitted
```

**Output of `podman version`:**

```
Version:       0.8.4
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.8.4-1.1.git9f9b8cf.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: bfe89744b376a8d4733fa4877951bf952184af66-dirty'
  MemFree: 11513028608
  MemTotal: 16696352768
  OCIRuntime:
    package: runc-1.0.0-50.dev.git20aff4f.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 4208979968
  SwapTotal: 4208979968
  arch: amd64
  cpus: 4
  hostname: bollard
  kernel: 4.17.18-200.fc28.x86_64
  os: linux
  uptime: 30m 28.67s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /var/home/rishi/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 2
  RunRoot: /run/user/1000/run
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is a physical laptop running Fedora 28 Silverblue 28.20180826.0.
