### ISSUE TITLE
podman: output of ps with a conatiner publishing 1000 ports is sub-optimal

### ISSUE THREAD

**Issue by jfilak** [containers/libpod#1358]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**
If I publish many ports, the output of docker ps gets unreadable.

**Steps to reproduce the issue:**

1. podman run -it -p 1000-2000:1000-2000 --rm --name manyports centos /bin/bash

2. podman ps

3.

**Describe the results you received:**

The output contains information about every port for both protocols.

**Describe the results you expected:**
I guess the same information which is used to start the container would be enough - `1000-2000:1000-2000`.

**Additional information you deem important (e.g. issue happens only occasionally):**

issue happens always

**Output of `podman version`:**

```
Version:       0.8.3
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.8.3-1.git9d09a4d.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: c72f69ce3f3fd7e46dced78dd99b67ab5441441e-dirty'
  MemFree: 12090945536
  MemTotal: 16547180544
  OCIRuntime:
    package: runc-1.0.0-50.dev.git20aff4f.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8346660864
  SwapTotal: 8346660864
  arch: amd64
  cpus: 4
  hostname: brql33992173a
  kernel: 4.17.18-200.fc28.x86_64
  os: linux
  uptime: 34m 5.58s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical Fedora 28
