### ISSUE TITLE
podman: failed to create containers are not automatically removed

### ISSUE THREAD

**Issue by jfilak** [containers/libpod#1359]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

Whenever podman fails to create the requested contianer and the option `--rm` is passed on command line, the container is listed in `podman ps -a` and it is not possible to create a container of the same name, even though the container should have been removed.

**Steps to reproduce the issue:**

1. podman run -it --rm --name noexec centos /does/not/exist

2. podman ps -a

3. podman run -it --rm --name noexec centos /does/not/exist

**Describe the results you received:**

```
# podman ps -a
CONTAINER ID   IMAGE                             COMMAND           CREATED          STATUS    PORTS   NAMES
4a6d34d50be5   docker.io/library/centos:latest   /does/not/exist   33 seconds ago   Created           noexec
# podman run -it --rm --name noexec centos /bin/bash
error creating container storage: the container name "noexec" is already in use by "4a6d34d50be5dabe105b93b6c36378e7853c313d869446e77d52a4f3a5861d3c". You have to remove that container to be able to reuse that name.: that name is already in use
```

**Describe the results you expected:**

```
# podman ps -a
# podman run -it --rm --name noexec centos /bin/bash
$
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This is super annoying because if you make a typo you have to run `rm` and if you forgot `--name` you also must run `ps`.

**Output of `podman version`:**

```
Version:       0.8.3
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.8.3-1.git9d09a4d.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: c72f69ce3f3fd7e46dced78dd99b67ab5441441e-dirty'
  MemFree: 11768156160
  MemTotal: 16547180544
  OCIRuntime:
    package: runc-1.0.0-50.dev.git20aff4f.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8346660864
  SwapTotal: 8346660864
  arch: amd64
  cpus: 4
  hostname: brql33992173a
  kernel: 4.17.18-200.fc28.x86_64
  os: linux
  uptime: 44m 2.28s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical Fedora 28
