### ISSUE TITLE
podman: run -h has different behavior than docker

### ISSUE THREAD

**Issue by jfilak** [containers/libpod#1367]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

We need to run our containers with specific hostnames.
I have a wrapper script that starts my containers in docker because the run command is rather huge.
The script also the option '-h thehostname' in the run command and I spent some time figuring out why podman prints help instead of starting my containers. I thought the that there is an unsupported option or an illegal value. I was cutting the options one by one and it took me 10 options until I noticed the option '-h'.

**Steps to reproduce the issue:**

1. podman run -it --rm -h vhcalnplci centos /bin/bash

**Describe the results you received:**

The help message is printed out.

**Describe the results you expected:**

The container is started.

**Additional information you deem important (e.g. issue happens only occasionally):**

Feel free to ignore this issue. Docker team has made a bad decision to use the common option for help for specifying hostname. I am going to change it in my scripts (but it will make the run command a bit more unreadable).

**Output of `podman version`:**

```
Version:       0.8.3
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.8.3-1.git9d09a4d.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: c72f69ce3f3fd7e46dced78dd99b67ab5441441e-dirty'
  MemFree: 926855168
  MemTotal: 16547172352
  OCIRuntime:
    package: runc-1.0.0-50.dev.git20aff4f.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8344825856
  SwapTotal: 8346660864
  arch: amd64
  cpus: 4
  hostname: brql33992173a
  kernel: 4.17.18-200.fc28.x86_64
  os: linux
  uptime: 7h 59m 13.1s (Approximately 0.29 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical Fedora 28
