### ISSUE TITLE
Pull podman images with docker after pushing to ACR with podman fails

### ISSUE THREAD

**Issue by tomkukral** [containers/libpod#1400]
**Description**
I'm building images by `buildah` and pushing it to ACR using `buildah push`. 

These images can be pulled only by `podman`, `docker pull` doesn't work.

```
docker pull volterra.azurecr.io/ves.io/vpm@sha256:6e5abcb2a2bfbec829052e2113b5c5b81158441a05afcd341cbe06f526ad933e
Trying to pull repository volterra.azurecr.io/ves.io/vpm ... 
unknown: some resources specified could not be found

podman pull volterra.azurecr.io/ves.io/vpm@sha256:6e5abcb2a2bfbec829052e2113b5c5b81158441a05afcd341cbe06f526ad933e
Trying to pull volterra.azurecr.io/ves.io/vpm@sha256:6e5abcb2a2bfbec829052e2113b5c5b81158441a05afcd341cbe06f526ad933e...Getting image source signatures
Skipping fetch of repeat blob sha256:17840c1046d97df07cdb2d703eee9d1e933e81a091eb36778feea36909295968
Copying config sha256:255af733af489362461850d8009e707d8302092781745459f6f2088b83423025
 441 B / 441 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
255af733af489362461850d8009e707d8302092781745459f6f2088b83423025
```

I'll be very grateful for any hint helping me to debug this. I'm pretty sure that it's a ACR issue because it works on Docker hub and locall `registry:2`.

I'm asking about this problem here because I believe that you can have some insight of differences in layer manipulation. 

**Steps to reproduce the issue:**

1. Build image using `buildah` and push it to ACR using `podman push`

2. Find SHA256 for your image and try to pull it using `docker pull`

**Describe the results you received:**

```
docker pull volterra.azurecr.io/ves.io/vpm@sha256:6e5abcb2a2bfbec829052e2113b5c5b81158441a05afcd341cbe06f526ad933e
Trying to pull repository volterra.azurecr.io/ves.io/vpm ... 
unknown: some resources specified could not be found
```

**Describe the results you expected:**

I was expecting to pull image. It works with podman

```
podman pull volterra.azurecr.io/ves.io/vpm@sha256:6e5abcb2a2bfbec829052e2113b5c5b81158441a05afcd341cbe06f526ad933e
Trying to pull volterra.azurecr.io/ves.io/vpm@sha256:6e5abcb2a2bfbec829052e2113b5c5b81158441a05afcd341cbe06f526ad933e...Getting image source signatures
Skipping fetch of repeat blob sha256:17840c1046d97df07cdb2d703eee9d1e933e81a091eb36778feea36909295968
Copying config sha256:255af733af489362461850d8009e707d8302092781745459f6f2088b83423025
 441 B / 441 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
255af733af489362461850d8009e707d8302092781745459f6f2088b83423025
```

It's a shame we are still using `docker` instead of `cri-o` for production deployments.

**Additional information you deem important (e.g. issue happens only occasionally):**

Works on Docker Hub.

**Output of `podman version`:**

```
podman version
Version:       0.8.3
Go Version:    go1.10.3
OS/Arch:       linux/amd64

docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-61.git9cb56fd.fc28.x86_64
 Go version:      go1.10.3
 Git commit:      1556cce-unsupported
 Built:           Wed Aug  1 17:21:17 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-61.git9cb56fd.fc28.x86_64
 Go version:      go1.10.3
 Git commit:      1556cce-unsupported
 Built:           Wed Aug  1 17:21:17 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Output of `podman info`:**

```
podman info
host:
  Conmon:
    package: podman-0.8.3-4.git9d09a4d.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 137533eb357b85f97b0dc9900326754c807901b6-dirty'
  MemFree: 158633984
  MemTotal: 6125809664
  OCIRuntime:
    package: runc-1.0.0-50.dev.git20aff4f.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 10665611264
  SwapTotal: 10737414144
  arch: amd64
  cpus: 4
  hostname: sif
  kernel: 4.17.18-200.fc28.x86_64
  os: linux
  uptime: 45h 15m 42.58s (Approximately 1.88 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```
