### ISSUE TITLE
/dev/null can't be found inside the container

### ISSUE THREAD

**Issue by EmilienM** [containers/libpod#1412]
/kind bug

**Description**
/dev/null can't be found inside the container, which is problematic for some applications like iSCSI or other services in OpenStack which require the access to /dev/null.

**Steps to reproduce the issue:**
Start a container which needs access to /dev/null

**Describe the results you received:**
From strace:
[pid 64887] stat("/dev/null", 0xc420106818) = -1 ENOENT (No such file or directory)

Full podman debug:
http://paste.openstack.org/show/hDyRznDV1Wv5K4lqNNVr/

**Describe the results you expected:**
Container starts correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
Version:       0.9.1-dev                                                                      
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**
```
host:
  Conmon:
    package: podman-0.8.2.1-1.gitf38eb4f.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 74bba30adae4fdcacf887d35e4d6331318765028-dirty'
  MemFree: 4904316928
  MemTotal: 16657346560
  OCIRuntime:
    package: runc-1.0.0-37.rc5.dev.gitad0f525.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 1610608640
  SwapTotal: 1610608640
  arch: amd64
  cpus: 4
  hostname: undercloud.localdomain
  kernel: 3.10.0-862.11.6.el7.x86_64
  os: linux
  uptime: 5h 29m 8.39s (Approximately 0.21 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.centos.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 49
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 29
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running it in a VM managed by libvirt/kvm.
