### ISSUE TITLE
Can't start container: error reading container (probably exited) json message: EOF

### ISSUE THREAD

**Issue by jlebon** [containers/libpod#1430]
> /kind bug

**Description**

After finally upgrading to 0.8.4 from 0.7.4 (which I had been holding off due to https://github.com/containers/libpod/issues/1283), I'm now hitting:

```
$ sudo podman start pet
unable to start container "pet": error reading container (probably exited) json message: EOF
```

**Steps to reproduce the issue:**

1. Again, I'm not sure other than potentially a compat issue. I can create and run new containers fine. It seems to be specifically about starting a previously created container.

```
$ ros db diff 7167d79cc60336d68efcd22a7efb5ca763bfa08368722a3efdf6e119f36b87bc 48a190a11b072807d3ea259c8524c50a761546f5b9fc1a603f3ecc864304f25f | grep podman
  podman 0.7.4-4.git80612fb.fc28 -> 0.8.4-2.git9f9b8cf.fc28
``` 

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.8.4-2.git9f9b8cf.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: fd2097f7ef3d0aacd9ed450ddb36fe544a242de4-dirty'
  MemFree: 8360644608
  MemTotal: 12491980800
  OCIRuntime:
    package: runc-1.0.0-51.dev.gitfdd8055.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8321495040
  SwapTotal: 8321495040
  arch: amd64
  cpus: 4
  hostname: lux
  kernel: 4.17.19-200.fc28.x86_64
  os: linux
  uptime: 17m 50.58s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora Silverblue laptop at version `28.20180907.0`.
