### ISSUE TITLE
podman containers not manageable from systemd

### ISSUE THREAD

**Issue by EmilienM** [containers/libpod#1446]
/kind bug

**Description**

containers managed by systemd start and fail after a few seconds.

**Steps to reproduce the issue:**

1. Create a systemd unit file for HAproxy container in /etc/systemd/system/haproxy.service:

```
[Unit]
Description=haproxy container
[Service]
Restart=always
ExecStart=/usr/bin/podman start haproxy
ExecStop=/usr/bin/podman stop -t 10 haproxy
[Install]
WantedBy=multi-user.target
```

2. Enable the service:
```systemctl enable haproxy.service```

3. Start the service:
```systemctl start haproxy.service```

**Describe the results you received:**

```
[root@undercloud ~]# service haproxy status -l
Redirecting to /bin/systemctl status  -l haproxy.service
● haproxy.service - haproxy container
   Loaded: loaded (/etc/systemd/system/haproxy.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2018-09-11 21:33:07 UTC; 2min 30s ago
  Process: 51209 ExecStop=/usr/bin/podman stop -t 10 haproxy (code=exited, status=0/SUCCESS)
  Process: 51125 ExecStart=/usr/bin/podman start haproxy (code=exited, status=0/SUCCESS)
 Main PID: 51125 (code=exited, status=0/SUCCESS)

Sep 11 21:33:07 undercloud.localdomain systemd[1]: haproxy.service holdoff time over, scheduling restart.
Sep 11 21:33:07 undercloud.localdomain systemd[1]: start request repeated too quickly for haproxy.service
Sep 11 21:33:07 undercloud.localdomain systemd[1]: Failed to start haproxy container.
Sep 11 21:33:07 undercloud.localdomain systemd[1]: Unit haproxy.service entered failed state.
Sep 11 21:33:07 undercloud.localdomain systemd[1]: haproxy.service failed.
```

Running ``podman ps`` hangs for 5 seconds and then returns empty (no container running).

**Describe the results you expected:**

Service in systemd should be active and running.
Podman should return the list of running containers.

**Additional information you deem important (e.g. issue happens only occasionally):**

Output of ps:
```
root       48327  0.0  0.0  85888   892 ?        Ssl  21:32   0:00 /usr/libexec/podman/conmon -s -c 2d7308674890d95c9f3b875046cc77082c83db9fd1fc8966d5f18e30344a3c50 -u 2d7308674890d95c9f3b875046cc77082c83db9fd1fc8966d5f18e30344a3c50 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/2d7308674890d95c9f3b875046cc77082c83db9fd1fc8966d5f18e30344a3c50/userdata -p /var/run/containers/storage/overlay-containers/2d7308674890d95c9f3b875046cc77082c83db9fd1fc8966d5f18e30344a3c50/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/2d7308674890d95c9f3b875046cc77082c83db9fd1fc8966d5f18e30344a3c50/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket --log-level error
root       62322  0.0  0.0  85888   840 ?        Ssl  21:37   0:00 /usr/libexec/podman/conmon -s -c 8dc22a2955b24aac7305cd25e68c45d4e2b3645ec84a79726f55349eba51fb80 -u 8dc22a2955b24aac7305cd25e68c45d4e2b3645ec84a79726f55349eba51fb80 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/8dc22a2955b24aac7305cd25e68c45d4e2b3645ec84a79726f55349eba51fb80/userdata -p /var/run/containers/storage/overlay-containers/8dc22a2955b24aac7305cd25e68c45d4e2b3645ec84a79726f55349eba51fb80/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/8dc22a2955b24aac7305cd25e68c45d4e2b3645ec84a79726f55349eba51fb80/userdata/ctr.log --exit-dir /var/run/libpod/exits --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /var/run/containers/storage --exit-command-arg --log-level --exit-command-arg error --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /var/run/libpod --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 8dc22a2955b24aac7305cd25e68c45d4e2b3645ec84a79726f55349eba51fb80 --socket-dir-path /var/run/libpod/socket --log-level error
root       62357  0.2  0.2 456408 16996 ?        Ssl  21:37   0:00 /usr/bin/podman stop -t 10 memcached
```

**Output of `podman version`:**

```
podman version 0.9.2-dev
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.8.5-3.gitdc5a711.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.11.2, commit: 2d86a71a1e3f3ccf65f6fb610558e660f5830fe4-dirty'
  MemFree: 213479424
  MemTotal: 8201625600
  OCIRuntime:
    package: runc-1.0.0-37.rc5.dev.gitad0f525.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 1610338304
  SwapTotal: 1610608640
  arch: amd64
  cpus: 4
  hostname: undercloud.localdomain
  kernel: 3.10.0-862.11.6.el7.x86_64
  os: linux
  uptime: 36m 45.47s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.centos.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 28
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 29
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running my lab in a VM managed by libvirt.
