### ISSUE TITLE
--net=host --privileged leaks /sys/fs/selinux

### ISSUE THREAD

**Issue by cgwalters** [containers/libpod#1448]
Using `--net=host` *and* `--privileged` leaks in `/sys/fs/selinux`, which causes tools (e.g. `rpm`, `libvirt`) inside the container to think that SELinux is enabled, and try to perform domain transitions, which will cause failures as the filesystem types are `container_t`.

```
# rpm-ostree status -b
State: idle
AutomaticUpdates: ex-stage; rpm-ostreed-automatic.timer: last run 15h ago
Deployments:
● ostree://fedora-atomic:fedora/28/x86_64/workstation
                   Version: 28.20180911.0 (2018-09-11 15:06:50)
                BaseCommit: acfb4afdebf0731ce0b9134adf434173472a970328d75ece68d5015af27b33e4
# rpm -q docker podman
docker-1.13.1-61.git9cb56fd.fc28.x86_64
podman-0.8.4-2.git9f9b8cf.fc28.x86_64
# 
```

First, docker:

```
# docker run --privileged -ti --rm registry.fedoraproject.org/fedora:28 ls -al /sys/fs/selinux
total 0
dr-xr-xr-x. 2 root root 0 Sep 12 13:16 .
drwxr-xr-x. 9 root root 0 Sep 12 13:16 ..
host:root@vanadium tmp/fcos
# docker run --net=host --privileged -ti --rm registry.fedoraproject.org/fedora:28 ls -al /sys/fs/selinux
total 0
dr-xr-xr-x. 2 root root 0 Sep 11 20:55 .
drwxr-xr-x. 9 root root 0 Sep 11 20:55 ..
#
```

Now podman:

```
# podman run --privileged -ti --rm registry.fedoraproject.org/fedora:28 ls -al /sys/fs/selinux
total 0
dr-xr-xr-x. 2 root root 0 Sep 12 13:16 .
drwxr-xr-x. 9 root root 0 Sep 12 13:16 ..
# podman run --net=host --privileged -ti --rm registry.fedoraproject.org/fedora:28 ls -al /sys/fs/selinux
total 0
drwxr-xr-x.   7 root root    0 Sep 11 20:55 .
drwxr-xr-x.   9 root root    0 Sep 11 20:55 ..
-rw-rw-rw-.   1 root root    0 Sep 11 20:55 access
dr-xr-xr-x.   2 root root    0 Sep 11 20:55 avc
dr-xr-xr-x.   2 root root    0 Sep 11 20:55 booleans
-rw-r--r--.   1 root root    0 Sep 11 20:55 checkreqprot
dr-xr-xr-x. 131 root root    0 Sep 11 20:55 class
--w-------.   1 root root    0 Sep 11 20:55 commit_pending_bools
-rw-rw-rw-.   1 root root    0 Sep 11 20:55 context
-rw-rw-rw-.   1 root root    0 Sep 11 20:55 create
-r--r--r--.   1 root root    0 Sep 11 20:55 deny_unknown
--w-------.   1 root root    0 Sep 11 20:55 disable
-rw-r--r--.   1 root root    0 Sep 11 20:55 enforce
dr-xr-xr-x.   2 root root    0 Sep 11 20:55 initial_contexts
-rw-------.   1 root root    0 Sep 11 20:55 load
-rw-rw-rw-.   1 root root    0 Sep 11 20:55 member
-r--r--r--.   1 root root    0 Sep 11 20:55 mls
crw-rw-rw-.   1 root root 1, 3 Sep 11 20:55 null
-r--r--r--.   1 root root    0 Sep 11 20:55 policy
dr-xr-xr-x.   2 root root    0 Sep 11 20:55 policy_capabilities
-r--r--r--.   1 root root    0 Sep 11 20:55 policyvers
-r--r--r--.   1 root root    0 Sep 11 20:55 reject_unknown
-rw-rw-rw-.   1 root root    0 Sep 11 20:55 relabel
-r--r--r--.   1 root root    0 Sep 11 20:55 status
-rw-rw-rw-.   1 root root    0 Sep 11 20:55 user
--w--w--w-.   1 root root    0 Sep 11 20:55 validatetrans
