### ISSUE TITLE
podman rm: implement -v, --volumes as no-op

### ISSUE THREAD

**Issue by pkubatrh** [containers/libpod#1459]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**Description**
Similar issue to #356 

Even if the created volumes get removed by podman with the container by default it would still make sense to me to have the option defined as a no-op in order to be able to use scripts originally written for docker (which leaves the volume when `-v` is not used) with podman as well.

**Steps to reproduce the issue:**

1. Run an image using podman
2. podman rm -v $CONTAINER_ID

**Describe the results you received:**
```
flag provided but not defined: -v
See 'podman rm --help'.
```

**Describe the results you expected:**
Image gets removed without an issue even though the `-v` option is ignored.

**Additional information you deem important (e.g. issue happens only occasionally):**
Using custom built podman rpm so as to have latest buildah bundled in (for https://github.com/projectatomic/buildah/pull/1007)
https://github.com/pkubatrh/libpod/tree/new_buildah

**Output of `podman version`:**

```
Version:       0.9.2-dev
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.9.1.1-1.dev.git4abb87e.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a8e1786574473e3bd1eb9a3d02c2ec1b35a930a2-dirty'
  MemFree: 401100800
  MemTotal: 11980427264
  OCIRuntime:
    package: runc-1.0.0-51.dev.gitfdd8055.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 5954859008
  SwapTotal: 6043987968
  arch: amd64
  cpus: 4
  hostname: localhost.localdomain
  kernel: 4.18.5-200.fc28.x86_64
  os: linux
  uptime: 4h 12m 33.28s (Approximately 0.17 days)
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 6
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/pkubat/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 3
  RunRoot: /run/user/21722/run
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
