### ISSUE TITLE
'podman run' with untagged image ends with 'panic: runtime error: index out of range'

### ISSUE THREAD

**Issue by pkubatrh** [containers/libpod#1499]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: # **kind bug**

**Description**
When calling `podman run IMAGE_ID` where `IMAGE_ID` points to an untagged image podman will run into `panic: runtime error: index out of range`

**Steps to reproduce the issue:**

1. build any image and don't tag it

2. `podman run IMAGE_ID`

**Describe the results you received:**
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.createContainer(0xc420160580, 0xc420130000, 0xc420130000, 0x0, 0x0, 0x0)
	/home/pkubat/Workdir/tmp/podman/libpod-e4770b82895659278b67a1bddb1a5acd8d785f59/_build/src/github.com/containers/libpod/cmd/podman/create.go:126 +0x7fb
main.runCmd(0xc420160580, 0x0, 0x0)
	/home/pkubat/Workdir/tmp/podman/libpod-e4770b82895659278b67a1bddb1a5acd8d785f59/_build/src/github.com/containers/libpod/cmd/podman/run.go:49 +0xd4
github.com/containers/libpod/vendor/github.com/urfave/cli.HandleAction(0x10d4420, 0x131c690, 0xc420160580, 0x0, 0xc4203346c0)
	/home/pkubat/Workdir/tmp/podman/libpod-e4770b82895659278b67a1bddb1a5acd8d785f59/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/containers/libpod/vendor/github.com/urfave/cli.Command.Run(0x1289eae, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12ae463, 0x20, 0x0, ...)
	/home/pkubat/Workdir/tmp/podman/libpod-e4770b82895659278b67a1bddb1a5acd8d785f59/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/command.go:165 +0x47d
github.com/containers/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc4201e2a80, 0xc4200a8060, 0x3, 0x3, 0x0, 0x0)
	/home/pkubat/Workdir/tmp/podman/libpod-e4770b82895659278b67a1bddb1a5acd8d785f59/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:259 +0x6e8
main.main()
	/home/pkubat/Workdir/tmp/podman/libpod-e4770b82895659278b67a1bddb1a5acd8d785f59/_build/src/github.com/containers/libpod/cmd/podman/main.go:251 +0x175b
```

**Describe the results you expected:**
A container is started without any issues.

**Additional information you deem important (e.g. issue happens only occasionally):**
Once the built image gets tagged `podman run IMAGE_ID` works without any issues.

Using podman from latest master (https://github.com/containers/libpod/commit/e4770b82895659278b67a1bddb1a5acd8d785f59)

**Output of `podman version`:**

```
Version:       0.9.3-dev
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.9.2.1-1.gite4770b8.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 9b94add581d789ae0c0014e1ab57f1f7b62700ce-dirty'
  MemFree: 404865024
  MemTotal: 11980427264
  OCIRuntime:
    package: runc-1.0.0-51.dev.gitfdd8055.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 5860749312
  SwapTotal: 6043987968
  arch: amd64
  cpus: 4
  hostname: localhost.localdomain
  kernel: 4.18.5-200.fc28.x86_64
  os: linux
  uptime: 4h 55m 42.68s (Approximately 0.17 days)
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 18
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/pkubat/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 65
  RunRoot: /run/user/21722/run


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
