### ISSUE TITLE
Podman empties .ContainerConfig.ExposedPorts if EXPOSE is not last Dockerfile command

### ISSUE THREAD

**Issue by pkubatrh** [containers/libpod#1536]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/**kind bug**

**Description**

I have run into this curious issue that when an image exposes a port via the Dockerfile's EXPOSE command, the ports are ignored unless the EXPOSE command is the last command in the Dockerfile.

**Steps to reproduce the issue:**

1.cat << EOF >Dockerfile
FROM centos:7
EXPOSE 8080
EOF
2. podman build -t expose .
3. podman inspect expose --format {{.ContainerConfig.ExposedPorts}}
4. echo "USER 1001" >> Dockerfile
5. podman build --no-cache -t expose .
6. podman inspect expose --format {{.ContainerConfig.ExposedPorts}}

**Describe the results you received:**
step 3:
map[8080/tcp:{}]
step 6:
map[]

**Describe the results you expected:**
step 3:
map[8080/tcp:{}]
step 6:
map[8080/tcp:{}]

**Additional information you deem important (e.g. issue happens only occasionally):**
Both root and rootless.
This works ok if the Dockerfile from step 4 is built using buildah (buildah-1.3-1.git4888163.fc28.x86_64)

**Output of `podman version`:**

```
Version:       0.9.3
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.9.3-4.gita723353.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 0fc9fe1e482dc5cb8dfca6d485cb1e27ec738f9d-dirty'
  MemFree: 1404514304
  MemTotal: 11980427264
  OCIRuntime:
    package: runc-1.0.0-51.dev.gitfdd8055.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 6043987968
  SwapTotal: 6043987968
  arch: amd64
  cpus: 4
  hostname: localhost.localdomain
  kernel: 4.18.5-200.fc28.x86_64
  os: linux
  uptime: 7h 23m 49.01s (Approximately 0.29 days)
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 15
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 26
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
