### ISSUE TITLE
podman does not start container with CMD or ENTRYPOINT

### ISSUE THREAD

**Issue by tamarintech** [containers/libpod#1588]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: # Uncomment only one, leave it on its own line:

**kind bug**

[//]: # **kind feature**

**Description**

`podman run` responds with `No command specified on command line or as CMD or ENTRYPOINT in this image` in an image built from a Dockerfile that includes `ENTRYPOINT ["/opt/unitd/unitd", "--no-daemon", "--log", "/dev/stdout"]`

```
$ podman inspect localhost/nginx-unit:1.1 | jq .[0].ContainerConfig.Entrypoint
[
  "/opt/unitd/unitd",
  "--no-daemon",
  "--log",
  "/dev/stdout"
]
```

Is podman ignoring the Entrypoint? This also happens if I use CMD.

**Steps to reproduce the issue:**

1. Build container from Dockerfile with ENTRYPOINT or CMD specified

2. Try to `podman run` the image

**Describe the results you received:**

`ENTRYPOINT ["/opt/unitd/unitd", "--no-daemon", "--log", "/dev/stdout"]`

**Describe the results you expected:**

The container should start.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:       0.9.1
Go Version:    go1.10.4
OS/Arch:       linux/amd64

```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.9.1-3.gitaba58d1.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 1d75f1d54e9e123a97e7f505e38df7ab7192cfa7-dirty'
  MemFree: 1234755584
  MemTotal: 16811745280
  OCIRuntime:
    package: runc-1.0.0-51.dev.gitfdd8055.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8392011776
  SwapTotal: 8476684288
  arch: amd64
  cpus: 16
  hostname: desktop
  kernel: 4.18.10-200.fc28.x86_64
  os: linux
  uptime: 46h 4m 27.56s (Approximately 1.92 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 16
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 20
  RunRoot: /run/user/1000/run
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical, Fedora 28
