### ISSUE TITLE
Can't login to AWS ECR

### ISSUE THREAD

**Issue by krashekspres** [containers/libpod#1599]
# **kind bug**

**Description**

Can't login to AWS ECR with `podman login -u AWS -p SOME_HASH https://###########.dkr.ecr.us-west-2.amazonaws.com`.
Podman returns:
```
error authenticating creds for "https://##########.dkr.ecr.us-west-2.amazonaws.com": pinging docker registry returned: Get https://https//###########.dkr.ecr.us-west-2.amazonaws.com/v2/: dial tcp: lookup https on 192.168.73.1:53: no such host
```  
AWS ECR docu > https://aws.amazon.com/ecr/

**Steps to reproduce the issue:**

1. Get login details from AWS ECR

2. Try to authenticate with podman

3. Fail with a message from the description.

**Describe the results you received:**
Got an error.

**Describe the results you expected:**
Should get success so I can pull/push images from AWS ECR.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 0.8.4
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: conmon-1.12.0-12.dev.gitc4f232a.fc29.x86_64
    path: /usr/libexec/crio/conmon
    version: 'conmon version 1.12.0-dev, commit: ed74efc8af284f786e041e8a98a910db4b2c0ec7'
  MemFree: 2912731136
  MemTotal: 8261115904
  OCIRuntime:
    package: runc-1.0.0-50.dev.git20aff4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc5+dev
      commit: d31de0a20f99562a3bdf58b21c57de931575e06a
      spec: 1.0.0
  SwapFree: 8396992512
  SwapTotal: 8396992512
  arch: amd64
  cpus: 4
  hostname: silverhulk
  kernel: 4.18.10-300.fc29.x86_64
  os: linux
  uptime: 13m 26.04s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 14
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /var/home/dario/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 10
  RunRoot: /run/user/1000/run

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
