### ISSUE TITLE
podman cannot pull & skopeo cannot inspect images from nvcr.io (NVIDIA GPU Cloud)

### ISSUE THREAD

**Issue by zvonkok** [containers/libpod#1612]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# **kind bug**
**Description**

podman-0.9.4-dev, podman-0.9.2 cannot pull images from the NVIDIA GPU Cloud 
skopeo-0.1.31-dev cannot inspect images from the NVIDIA GPU Cloud

**Steps to reproduce the issue:**

1. `podman pull  nvcr.io/nvidia/caffe2:18.08-py3`
2.  `skopeo inspect  docker://nvcr.io/nvidia/caffe2:18.08-py3`

**Describe the results you received:**

podman: 
```
Trying to pull nvcr.io/nvidia/caffe2:18.08-py3...Getting image source signatures
Copying blob sha256:8ee29e426c26c79e7ba03ccc8bbc7fe99db00ffcbccb679d9c643b5546d8dc8a
Failed
error pulling image "nvcr.io/nvidia/caffe2:18.08-py3": unable to pull nvcr.io/nvidia/caffe2:18.08-py3: unable to pull image: Error reading blob sha256:8ee29e426c26c79e7ba03ccc8bbc7fe99db00ffcbccb679d9c643b5546d8dc8a: Invalid status code returned when fetching blob 504
```
skopeo:
```
FATA[0063] Invalid status code returned when fetching blob 504 
```

**Output of `podman version`:**

```
podman-0.9.4-dev
podman-0.9.2
skopeo-0.1.31-dev
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.9.2-5.git37a2afe.el7_5.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.11.4, commit: cade65d40947e9d2c10294022cb672c4252b64e8-dirty'
  Distribution:
    distribution: '"rhel"'
    version: "7.5"
  MemFree: 158547619840
  MemTotal: 257610862592
  OCIRuntime:
    package: runc-1.0.0-52.dev.git70ca035.el7_5.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 32
  hostname: ip-172-31-66-66.eu-central-1.compute.internal
  kernel: 3.10.0-935.el7.x86_64
  os: linux
  uptime: 341h 45m 49.03s (Approximately 14.21 days)
insecure registries:
  registries:
  - nvcr.io
registries:
  registries:
  - registry.access.redhat.com
  - nvcr.io
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
```
