### ISSUE TITLE
pypodman is not able to work on rhel7.5 python3.4.9

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#1641]
**Is this a BUG REPORT or FEATURE REQUEST?**:
**kind bug**

**Description**

With the environment of rhel7.5 and python 3.4.9, pypodman raises a TypeError while I'm trying to get the remote machine's containers info. I also tried this environment not for the remote feature, like `pypodman images` or `pypodman ps`, this error still exists.

**Steps to reproduce the issue:**
##### On remote machine:
```
# hostnamectl                                         
   Static hostname: localhost.localdomain
Transient hostname: dhcp-2-7.nay.redhat.com
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: cd196ab74fbf40448d31037ceafbcf05
           Boot ID: 7811c3c51c0d46ad90c327e8153dcbcd
  Operating System: Fedora 27 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:27
            Kernel: Linux 4.18.7-100.fc27.x86_64
```
```
# podman version
Version:       0.10.2-dev
Go Version:    go1.9.7
OS/Arch:       linux/amd64
```
```
# podman info
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: conmon-1.10.3-1.gite558bd5.fc27.x86_64
    path: /usr/libexec/crio/conmon
    version: 'conmon version 1.10.3, commit: 27d18947e07ae525daacba333e67a98a6296fc5d'                   
  Distribution:
    distribution: fedora
    version: "27"
  MemFree: 174825472
  MemTotal: 11980427264
  OCIRuntime:
    package: runc-1.0.0-36.gitad0f525.fc27.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc5+dev
      spec: 1.0.0
  SwapFree: 5162135552
  SwapTotal: 6043987968
  arch: amd64
  cpus: 4
  hostname: dhcp-2-7.nay.redhat.com
  kernel: 4.18.7-100.fc27.x86_64
  os: linux
  uptime: 99h 28m 45.01s (Approximately 4.12 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

1. build podman from [upstream](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md#building-and-installing-podman)

2. `systemctl enable io.podman.socket`

3. `systemctl start io.podman.socket`

4. get socket status:
```
systemctl status io.podman.socket
● io.podman.socket - Podman Remote API Socket
   Loaded: loaded (/usr/lib/systemd/system/io.podman.socket; enabled; vendor preset: disabled)
   Active: active (listening) since Fri 2018-10-12 17:00:47 CST; 2 days ago
     Docs: man:podman-varlink(1)
   Listen: /run/podman/io.podman (Stream)
```

5. `podman varlink -t 5000000 unix:/run/podman/io.podman`

##### On host machine:
```
# hostnamectl
Static hostname: localhost.localdomain
Transient hostname: dell-per630-03.rhts.eng.pek2.redhat.com                                              
         Icon name: computer-server
           Chassis: server
        Machine ID: 132a8e31ef294cd4ba9b6b771a2953ff
           Boot ID: 12654aac39b94bd89fb7a573286fc9ec
  Operating System: CloudForms
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.5:GA:server                                         
            Kernel: Linux 3.10.0-862.el7.x86_64
      Architecture: x86-64
```
```
# python3 --version
3.4.9
```

1. [install python package podman from upstream](https://github.com/containers/libpod/tree/master/contrib/python/podman#releases)

2. [install pypodman from upstream](https://github.com/containers/libpod/tree/master/contrib/python/pypodman#releases) 

3. `export PATH="$PATH:/root/.local/bin"`

4. `pypodman -l root --host 10.66.2.7 ps`

**Describe the results you received:**
```
[root@dell-per630-03 pypodman]# pypodman -l root --host 10.66.2.7 ps
Traceback (most recent call last):
  File "/root/.local/bin/pypodman", line 11, in <module>
    load_entry_point('pypodman==0.0.0', 'console_scripts', 'pypodman')()
  File "/root/.local/lib/python3.4/site-packages/pypodman-0.0.0-py3.4.egg/pypodman/main.py", line 35, in main
  File "/usr/lib64/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: argument should be string, bytes or integer, not PosixPath
```

**Describe the results you expected:**
Be able to have the same result as `podman ps` on the remote machine.

**Additional information you deem important (e.g. issue happens only occasionally):**
Always happen on this eviroment.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical
