### ISSUE TITLE
command `pypodman images` shows different image size with `podman images` does

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#1653]
**Is this a BUG REPORT or FEATURE REQUEST?**:
# **kind bug**

**Description**
The **SIZE** column shows the different size, and the **CREATED** column also has the different format.

**Steps to reproduce the issue:**

1. `podman pull registry.fedoraproject.org/f27/httpd`

2. `podman images`

3. `pypodman images`

**Describe the results you received:**
```
# podman images   
REPOSITORY                             TAG      IMAGE ID       CREATED        SIZE
registry.fedoraproject.org/f27/httpd   latest   18f01f6f77ef   3 months ago   426MB
```
```
# pypodman images
REPOSITORY                               TAG        IMAGE ID     CREATED      SIZE    
registry.fedoraproject.org/f27/httpd     latest     18f01f6f77ef Jul 17       406.3 Mi
```

**Describe the results you expected:**
`pypodman images` shows the same size as `podman images` does.

**Additional information you deem important (e.g. issue happens only occasionally):**
Always

**Output of `podman version`:**
```
podman version
Version:       0.10.2-dev
Go Version:    go1.9.7
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
podman info
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: conmon-1.10.3-1.gite558bd5.fc27.x86_64
    path: /usr/libexec/crio/conmon
    version: 'conmon version 1.10.3, commit: 27d18947e07ae525daacba333e67a98a6296fc5d'                   
  Distribution:
    distribution: fedora
    version: "27"
  MemFree: 776192000
  MemTotal: 11980427264
  OCIRuntime:
    package: runc-1.0.0-36.gitad0f525.fc27.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc5+dev
      spec: 1.0.0
  SwapFree: 2315251712
  SwapTotal: 6043987968
  arch: amd64
  cpus: 4
  hostname: dhcp-2-7.nay.redhat.com
  kernel: 4.18.7-100.fc27.x86_64
  os: linux
  uptime: 127h 9m 0.79s (Approximately 5.29 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
``` 
# hostnamectl
   Static hostname: localhost.localdomain
Transient hostname: dhcp-2-7.nay.redhat.com
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: cd196ab74fbf40448d31037ceafbcf05
           Boot ID: 7811c3c51c0d46ad90c327e8153dcbcd
  Operating System: Fedora 27 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:27
            Kernel: Linux 4.18.7-100.fc27.x86_64
      Architecture: x86-64
```
