### ISSUE TITLE
"podman ps" seems to set "--no-trunc" by default

### ISSUE THREAD

**Issue by cjeanner** [containers/libpod#1727]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: # Uncomment only one, leave it on its own line:

# **kind bug**

[//]: # **kind feature**

**Description**

There's an issue when we issue a ```podman ps```: the output is just unreadable. Among the issues:

- COMMAND field isn't truncated, meaning it might be far, far too long for a standard screen
- ID field shows the full ID, not the short one
- No "newline" at the end of the listing, meaning the shell prompt is on that same last line

In short: it looks like the ```--no-trunc``` is set by default, with an additional bug regarding the missing "newline" at the end of the output.

**Steps to reproduce the issue:**

1. Run some container

2. Run ```podman ps```

3. Enjoy the output

**Describe the results you received:**
An unreadable, far too long output without any truncated field

**Describe the results you expected:**
A human readable, truncated content output by default, and if we want to get the full output, we pass ```--no-trunc```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.10.2-dev
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-2.git6e1aeb0.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0, commit: 097cf71375bd18454d1c48b9fdf8ccff2ed995f8-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 2207911936
  MemTotal: 29273866240
  OCIRuntime:
    package: runc-1.0.0-54.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 12
  hostname: undercloud.lain.internux.ch
  kernel: 3.10.0-862.14.4.el7.x86_64
  os: linux
  uptime: 4h 10m 44.85s (Approximately 0.17 days)
insecure registries:
  registries:
  - 192.168.24.1:8787
  - 192.168.24.3:8787
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 90
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 37
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
