### ISSUE TITLE
Random relabelling failures

### ISSUE THREAD

**Issue by EmilienM** [containers/libpod#1739]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# **kind bug**

**Description**
Since we have podman-0.10.1.3-2.git6e1aeb0.el7.x86_64 in OpenStack CI, we have more than 65% of failure in our jobs and they fail for the same reason: relabelling a one directory (always the same).

**Steps to reproduce the issue:**

1. Running podman command:
```
/usr/bin/podman run --user root --name docker-puppet-ironic_inspector --env PUPPET_TAGS=file,file_line,concat,augeas,cron,ironic_inspector_config --env NAME=ironic_inspector --env HOSTNAME=undercloud --env NO_ARCHIVE= --env STEP=6 --env NET_HOST=true --volume /etc/localtime:/etc/localtime:ro --volume /tmp/tmpXkPhuw:/etc/config.pp:ro,z --volume /etc/puppet/:/tmp/puppet-etc/:ro,z --volume /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro --volume /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro --volume /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro --volume /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro --volume /var/lib/config-data:/var/lib/config-data/:rw,z --volume /dev/log:/dev/log:rw --volume /var/lib/docker-puppet/docker-puppet.sh:/var/lib/docker-puppet/docker-puppet.sh:rw,z --security-opt label=disable --volume /usr/share/openstack-puppet/modules/:/usr/share/openstack-puppet/modules/:ro --volume /var/lib/ironic:/var/lib/ironic:z --volume /var/lib/ironic-inspector/dhcp-hostsdir:/var/lib/ironic-inspector/dhcp-hostsdir:z --entrypoint /var/lib/docker-puppet/docker-puppet.sh --net host --volume /etc/hosts:/etc/hosts:ro 192.168.24.1:8787/tripleomaster/centos-binary-ironic-inspector:current-tripleo-updated-20181026224149
```

2. It fails randomly, and never on the same container, but always on /var/lib/config-data relabelling.

**Describe the results you received:**
```
relabel failed \"/var/lib/config-data\": no such file or directory"
```

**Describe the results you expected:**
Container should be run and relabelling should work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman-0.10.1.3-2.git6e1aeb0.el7.x86_64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-2.git6e1aeb0.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0, commit: 097cf71375bd18454d1c48b9fdf8ccff2ed995f8-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 401932288
  MemTotal: 8365150208
  OCIRuntime:
    package: runc-1.0.0-54.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8556113920
  SwapTotal: 8588881920
  arch: amd64
  cpus: 8
  hostname: undercloud.localdomain
  kernel: 3.10.0-862.14.4.el7.x86_64
  os: linux
  uptime: 1h 3m 44.05s (Approximately 0.04 days)
insecure registries:
  registries:
  - 192.168.24.1:8787
  - 192.168.24.3:8787
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 22
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The CI jobs run in VMs, with 8vcpu, 8GB of RAM and 8GB of swap.
