### ISSUE TITLE
hostname is not added to /etc/hosts

### ISSUE THREAD

**Issue by jfilak** [containers/libpod#1745]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind bug**

**Description**

podman does not add container's hostname to /etc/hosts (docker does).

**Steps to reproduce the issue:**

1. podman run -it --rm --hostname foobar centos /bin/bash
2. cat /etc/hosts

**Describe the results you received:**
I can see the content of host's /etc/hosts and there is no entry with the host `foobar`.

**Describe the results you expected:**
```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      foobar
````

**Output of `podman version`:**

```
Version:       0.10.1.3
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-1.gitdb08685.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 4a03e555ee4105308fa4d814d4ce02a059af0b7f-dirty'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 4620840960
  MemTotal: 16547115008
  OCIRuntime:
    package: runc-1.0.0-56.dev.git78ef28e.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8346660864
  SwapTotal: 8346660864
  arch: amd64
  cpus: 4
  hostname: brql33992173a
  kernel: 4.18.16-200.fc28.x86_64
  os: linux
  uptime: 18h 21m 12.12s (Approximately 0.75 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```
