### ISSUE TITLE
`--runtime=` flag

### ISSUE THREAD

**Issue by vbatts** [containers/libpod#1750]
# **kind feature**

**Description**

`podman run -it --runtime=kata fedora bash`
where the path and custom flags for that runtime are configured in /etc/...

**Describe the results you received:**

**Describe the results you expected:**

Ability to easily use runtimes other than runc

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.10.1.3
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-1.gitdb08685.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 4a03e555ee4105308fa4d814d4ce02a059af0b7f-dirty'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 842072064
  MemTotal: 16645189632
  OCIRuntime:
    package: runc-1.0.0-56.dev.git78ef28e.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 12
  hostname: getdown.usersys.redhat.com
  kernel: 4.18.8-200.fc28.x86_64
  os: linux
  uptime: 1008h 13m 16.84s (Approximately 42.00 days)
insecure registries:
  registries:
  - localhost:5000
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 4
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/vbatts/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 19
  RunRoot: /run/user/1000/run
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vbatts** [comment]
this would likely need the config for array of `runtime_path` to be more like a map, than an array

**Comment by mheon** [comment]
I've been thinking about this one for a while - I'd consider it a blocker for CRI-O integration.

We need to modify `libpod` to allow multiple OCI runtimes, and then modify containers to ensure that they store the runtime they were created with in the database (and modify the database to ensure that all Podman processes using it have the same runtimes defined - we get into an awkward spot if Podman A creates a Kata container, and Podman B tries to start that container but doesn't have the Kata runtime available).

It probably also makes sense to add checks that all containers in a pod must use the same runtime, and all dependencies of a container must share the same runtime (we can't expect namespace sharing on the host to work right when some containers are launched in VMs).

**Comment by vbatts** [comment]
(coincidentally kata-runtime works nicely currently by setting `runtime_path=["/usr/bin/kata-runtime"]` in libpod.conf)

**Comment by rhatdan** [comment]
I believe @giuseppe Also got gvisor to work with podman.

**Comment by vbatts** [comment]
railcar, not so much. even if you set cgroupfs as the cgroup manager (https://github.com/oracle/railcar/issues/41) there is something else failing

**Comment by vbatts** [comment]
like:
```toml
[[runtimes]]
  Name = "runc"
  Paths = ["/usr/bin/runc"]

[[runtimes]]
  Name = "kata"
  Paths = ["/usr/bin/kata-runtime"
```
