### ISSUE TITLE
non-root on centos7 hangs

### ISSUE THREAD

**Issue by vbatts** [containers/libpod#1758]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# **kind bug**

**Description**

running a container as non-root on centos7 hangs
(looks to be in a futex wait loop)

**Steps to reproduce the issue:**

1. centos7 host, with podman installed, and https://copr.fedorainfracloud.org/coprs/vbatts/shadow-utils-newxidmap/

2. `strace -f -o podman.dump -- podman run -it --rm fedora echo farts`

3.

**Describe the results you received:**

command hangs and never succeeds or fails.

**Describe the results you expected:**

"farts"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.9.2
Go Version:    go1.9.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.9.2-5.git37a2afe.el7_5.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.11.4, commit: a8705beb2cadf0a86c3e2c12e350a060ceb8659f-dirty'
  MemFree: 19578548224
  MemTotal: 32912543744
  OCIRuntime:
    package: runc-1.0.0-52.dev.git70ca035.el7_5.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 16575885312
  SwapTotal: 16575885312
  arch: amd64
  cpus: 8
  hostname: beater.usersys.redhat.com
  kernel: 3.10.0-862.14.4.el7.x86_64
  os: linux
  uptime: 3h 18m 37.04s (Approximately 0.12 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.centos.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 6
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 11
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
