### ISSUE TITLE
container_t isn't allowed to access container_var_lib_t

### ISSUE THREAD

**Issue by cjeanner** [containers/libpod#1782]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: # Uncomment only one, leave it on its own line:

# **kind bug**

[//]: # **kind feature**

**Description**

**Steps to reproduce the issue:**

1. Deploy some container with *docker* and some volumes (let docker create the host directories)

2. Migrate the container to Podman, with that same directory

3. Try to read/write in the volume from podman

**Describe the results you received:**
We get SELinux access denied, for instance:
```
type=AVC msg=audit(1541628356.826:5369): avc: denied { read } for pid=452886 comm="python" name="rabbitmq-env.conf" dev="dm-0" ino=100801360 scontext=system_u:system_r:container_t:s0:c41,c44 tcontext=unconfined_u:object_r:container_var_lib_t:s0 tclass=file
```

**Describe the results you expected:**
We should be able to access the data in the same way we could with docker

**Additional information you deem important (e.g. issue happens only occasionally):**
It would be cool to be able to access the data without any "chcon" - especially if there are many directory levels and many files.

**Output of `podman version`:**

```
Version:       0.10.2-dev
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-4.gitee513cc.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0, commit: 01d038c5b51fddd21be5210091707dd15bb830e0-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 6690496512
  MemTotal: 25111056384
  OCIRuntime:
    package: runc-1.0.0-54.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 12683571200
  SwapTotal: 12683571200
  arch: amd64
  cpus: 10
  hostname: undercloud.localdomain
  kernel: 3.10.0-862.14.4.el7.x86_64
  os: linux
  uptime: 20h 9m 1.95s (Approximately 0.83 days)
insecure registries:
  registries:
  - 192.168.24.1:8787
  - 192.168.24.3:8787
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 18
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 22
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This issue is also described on Launchpad: https://bugs.launchpad.net/tripleo/+bug/1802203
