### ISSUE TITLE
podman assigns new IP to each new container

### ISSUE THREAD

**Issue by jfilak** [containers/libpod#1791]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# **kind bug**

**Description**

I used to rely on the fact that docker starts assigning IPs from 172.17.0.2 and always use the first available IP. This behavior allowed me to have entries such as "172.17.0.2      docker2" in my /etc/hosts and use those hostnames in our tools which work only with hostnames.

**Steps to reproduce the issue:**

1. for i in 1 2 3; do podman run -it --rm --hostname foobar centos hostname -I; done
2. for i in 1 2 3; do docker run -it --rm --hostname foobar centos hostname -I; done

**Describe the results you received:**
- podman
```
10.88.18.67 
10.88.18.68 
10.88.18.69
```
- docker
```
172.17.0.2 
172.17.0.2 
172.17.0.2
```

**Describe the results you expected:**
- podman
```
10.88.18.67
10.88.18.67
10.88.18.67
```

**Output of `podman version`:**

```
Version:       0.10.1.3
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-1.gitdb08685.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 4a03e555ee4105308fa4d814d4ce02a059af0b7f-dirty'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 8286851072
  MemTotal: 16547123200
  OCIRuntime:
    package: runc-1.0.0-57.dev.git9e5aa74.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8346660864
  SwapTotal: 8346660864
  arch: amd64
  cpus: 4
  hostname: brql33992173a
  kernel: 4.18.16-200.fc28.x86_64
  os: linux
  uptime: 1h 43m 27.13s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ContainerStore:
    number: 9
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical, Fedora 28
