### ISSUE TITLE
podman and harbor ui doesn't play well together

### ISSUE THREAD

**Issue by floriankoch** [containers/libpod#1792]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind bug**

**Description**

podman pushes are not visible in the [harbor](https://github.com/goharbor) Ui
There is an issue about this https://github.com/goharbor/harbor/issues/5729
(afaik it affects all clients without "docker"  as user agent)

**Steps to reproduce the issue:**

1. Setup harbor

2. push an image with docker -> visible in the ui

3. push an image with podman -> not visible in the ui

**Describe the results you received:**

podman and docker behavior is differnet

**Describe the results you expected:**

podman and docker behavior is identical

**Additional information you deem important (e.g. issue happens only occasionally):**

As i understand, docker uses "docker" as User-Agent, podman does not

**Output of `podman version`:**

```
podman version 0.10.1.3
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-1.gitdb08685.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 4a03e555ee4105308fa4d814d4ce02a059af0b7f-dirty'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 257114112
  MemTotal: 16818675712
  OCIRuntime:
    package: runc-1.0.0-56.dev.git78ef28e.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8465399808
  SwapTotal: 8476684288
  arch: amd64
  cpus: 4
  hostname: xxx
  kernel: 4.18.13-200.fc28.x86_64
  os: linux
  uptime: 575h 23m 25.74s (Approximately 23.96 days)
insecure registries:
  registries:
  - https://harbor.lan
  registries:
  - https://harbor.lan
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 37
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/xxx/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 16
  RunRoot: /run/user/1000/run
```
