### ISSUE TITLE
question: how-to download a container image using a proxy

### ISSUE THREAD

**Issue by nskalis** [containers/libpod#1797]
**Description**

Hi,

I am sorry as I am not sure if this is the right place to ask a question;

Could you please advise how to specify the proxy settings (http(s), ipaddress, port) 
in order to download a container image using podman ?
Is that possible ?

**Output of `podman version`:**

```
$ podman version
Version:       0.9.2
Go Version:    go1.9.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.9.2-5.git37a2afe.el7_5.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.11.4, commit: a8705beb2cadf0a86c3e2c12e350a060ceb8659f-dirty'
  MemFree: 176283648
  MemTotal: 8201056256
  OCIRuntime:
    package: runc-1.0.0-52.dev.git70ca035.el7_5.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8428720128
  SwapTotal: 8455712768
  arch: amd64
  cpus: 8
  hostname: nl-ams02c-xxx.xxx.xxx
  kernel: 3.10.0-862.11.6.el7.x86_64
  os: linux
  uptime: 1493h 6m 52.15s (Approximately 62.21 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.centos.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
KVM guest
