### ISSUE TITLE
"podman inspect --type image --format exists <image>" reports a not-friendly error when image doesn't exist in local storage

### ISSUE THREAD

**Issue by cjeanner** [containers/libpod#1845]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: # Uncomment only one, leave it on its own line:

# **kind bug**

[//]: # **kind feature**

**Description**
When we run ```podman inspect --type image --format exists <image>``` against a non-existing image, we end up with a long, not really nice message like:
```
2018-11-19 21:42:01 |         "b'error getting image \"docker.io/tripleomaster/centos-binary-cinder-volume:3ed8ac0e93367a02ad53d9fa93467057724b6621_fd8eb74b\": unable to find \\'docker.io/tripleomaster/centos-binary-cinder-volume:3ed8ac0e93367a02ad53d9fa93467057724b6621_fd8eb74b\\' in local storage\\n'",
```
It should return something like ```the image <image> does not exist``` instead, and at least not as an error, especially since we are testing its existence.

**Steps to reproduce the issue:**

1. run the command against an image not yet present in the local storage

2.

3.

**Describe the results you received:**
Long, not nice, not userfriendly message, with an "error" flag

**Describe the results you expected:**
A small, informative message stating the image doesn't exist, without "error" in it

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.11.1.1
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.11.1.1-3.git594495d.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: ccde1bf8e093607ecf92b404368033f645cad755-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 874045440
  MemTotal: 8365137920
  OCIRuntime:
    package: runc-1.0.0-55.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8557686784
  SwapTotal: 8588881920
  arch: amd64
  cpus: 8
  hostname: undercloud.localdomain
  kernel: 3.10.0-862.14.4.el7.x86_64
  os: linux
  rootless: false
  uptime: 59m 56.33s
insecure registries:
  registries:
  - 192.168.24.1:8787
  - 192.168.24.3:8787
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 19
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
