### ISSUE TITLE
set podman image storage location

### ISSUE THREAD

**Issue by abitrolly** [containers/libpod#1916]
[//]: # **kind feature**

or, rather, **support request**.

My root is mounted at SSD for speed, and so does my home. However, I am not rich, so SSD is small, and now I want more space. First I want to move images to another disk, and if that won't help, move containers as well.

I found `podman info`, which printed some useful info at the end.
```
...
store:
  ContainerStore:
    number: 3
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/anatoli/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /run/user/1000/run
```
The path `/home/anatoli/.local/share/containers/storage` is 6.3G, and there is only one image 745Mb in size there.
```
✗ podman images -a
REPOSITORY                 TAG     IMAGE ID       CREATED        SIZE
docker.io/library/golang   1.9.4   a6c306bd0b2f   8 months ago   754MB
✗ du -hs  ~/.local/share/containers/storage
6.3G	/home/anatoli/.local/share/containers/storage
```
I don't see how can I move images to the other place, because `vfs-images` contains only meta information and `vfs` hosts only hash dirs.
```
6.3G	/home/anatoli/.local/share/containers/storage/vfs
132K	/home/anatoli/.local/share/containers/storage/vfs-containers
28K	/home/anatoli/.local/share/containers/storage/vfs-images
1.8M	/home/anatoli/.local/share/containers/storage/vfs-layers
```

**Is there a setting that I can change to store images in a separate dir?**

**Output of `podman version`:**
```
Version:       0.10.1.3
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```
