### ISSUE TITLE
dangling dir in vfs

### ISSUE THREAD

**Issue by abitrolly** [containers/libpod#1917]
[//]: # **kind bug**

I've got unknown 706M of image/container data.
```
➜  podman git:(master) ✗ podman images -a                                
➜  podman git:(master) ✗ podman ps -a                                    
➜  podman git:(master) ✗ ls -l ~/.local/share/containers/storage/vfs/dir 
total 4
drwxr-xr-x. 21 anatoli anatoli 4096 Dec  2 10:50 97ba8f52abc877f267dce6b6767a63a5fe549ab6b7b49cfac219a94631ca357a
➜  podman git:(master) ✗ du -hs ~/.local/share/containers/storage/vfs/dir 
706M	/home/anatoli/.local/share/containers/storage/vfs/dir
```
What is that and how to clean it?

**Output of `podman version`:**

```
Version:       0.10.1.3
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-1.gitdb08685.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 4a03e555ee4105308fa4d814d4ce02a059af0b7f-dirty'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 1200979968
  MemTotal: 8053104640
  OCIRuntime:
    package: runc-1.0.0-57.dev.git9e5aa74.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8109944832
  SwapTotal: 8196714496
  arch: amd64
  cpus: 4
  hostname: localhost
  kernel: 4.19.4-200.fc28.x86_64
  os: linux
  uptime: 27h 59m 18.37s (Approximately 1.12 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/anatoli/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000/run
```
