### ISSUE TITLE
podman anonymous pull fails

### ISSUE THREAD

**Issue by akostadinov** [containers/libpod#1963]
**Is this a BUG REPORT or FEATURE REQUEST?**:
**kind bug**

**Description**

podman seems to not allow anonymous pull.

**Steps to reproduce the issue:**

1. Skopeo can inspect image:
```
$ skopeo inspect docker://myrepo.example.com/myproject/myimage
{
    "Name": "myrepo.example.com/myproject/myimage",
    "Digest": "sha256:d275b00bb22cac63962979784098dfb62ff240a4d2c057d3d7bba881650e4d71",
    "RepoTags": [
        "latest",
        "20181205"
    ],
    ...
```

2. Podman run image
```
$ sudo podman run docker://myrepo.example.com/myproject/myimage -- /bin/bash -l
```

**Describe the results you received:**
```
Trying to pull docker://myrepo.example.com/myproject/myimage...Failed
unable to pull docker://myrepo.example.com/myproject/myimage: unable to pull image: Error determining manifest MIME type for docker://myrepo.example.com/myproject/myimage:latest: unable to retrieve auth token: invalid username/password
```

**Describe the results you expected:**
I enter into proper bash shell

**Additional information you deem important (e.g. issue happens only occasionally):**
docker package **not** installed, Fedora 29

**Output of `podman version`:**

```
$ podman version
Version:       0.10.1.3
Go Version:    go1.11
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-4.gitdb08685.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 1f741a8b8381375b068b147605704a02a91167a2-dirty'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 513298432
  MemTotal: 2087391232
  OCIRuntime:
    package: runc-1.0.0-59.dev.gitccb5efd.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      commit: 6e5a791a02fefb403034e0de8693d225d52b33a7
      spec: 1.0.1-dev
  SwapFree: 858505216
  SwapTotal: 858779648
  arch: amd64
  cpus: 2
  hostname: fedoraw
  kernel: 4.19.6-300.fc29.x86_64
  os: linux
  uptime: 2h 53m 55.25s (Approximately 0.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

KVM, Fedora 29 fully updated as of today
