### ISSUE TITLE
podman run --rm will not remove the container if the command isn't found

### ISSUE THREAD

**Issue by kirbyfan64** [containers/libpod#1985]
/kind bug

**Description**

**Steps to reproduce the issue:**

1. Run `podman run --rm` with some command that is not inside the container's path, e.g. `podman run --rm -it alpine xyz`. This occurs in both standard/root and rootless modes.

2. Observe that is says `internal libpod error`.

3. Run `podman ps -a` to see the list of present containers.

**Describe the results you received:**

The list of containers contains the one that I just ran.

**Describe the results you expected:**

It should not be on that list because `--rm` was used.

**Additional information you deem important (e.g. issue happens only occasionally):**

As mentioned above, this occurs with or without root.

Example set of commands to reproduce (removed my shell ps1 because it looks ugly here):

```
$ sudo podman ps -a          
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
$ sudo podman run --rm -it alpine xyz
container create failed: container_linux.go:344: starting container process caused "exec: \"xyz\": executable file not found in $PATH"
: internal libpod error
$ sudo podman ps -a                  
CONTAINER ID  IMAGE                            COMMAND  CREATED       STATUS   PORTS  NAMES
ddfe5395daa7  docker.io/library/alpine:latest  xyz      1 second ago  Created         vigilant_haibt
```

**Output of `podman version`:**

```
Version:       0.12.1.1
Go Version:    go1.11.2
Git Commit:    "0c9259a2c84f6234a29dcd78674c3f4837fd3101"
Built:         Fri Dec  7 13:29:27 2018
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.1-1.git66d3499.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 0c9259a2c84f6234a29dcd78674c3f4837fd3101'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 555073536
  MemTotal: 8222674944
  OCIRuntime:
    package: runc-1.0.0-59.dev.gitccb5efd.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      commit: 6e5a791a02fefb403034e0de8693d225d52b33a7
      spec: 1.0.1-dev
  SwapFree: 7964717056
  SwapTotal: 8359243776
  arch: amd64
  cpus: 4
  hostname: fedora.refi64.com
  kernel: 4.19.7-300.fc29.x86_64
  os: linux
  rootless: true
  uptime: 2h 6m 15.03s (Approximately 0.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 50
  GraphDriverName: vfs
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/ryan/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 137
  RunRoot: /run/user/1000/run
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Reproduced on Fedora 29 Silverblue.
