### ISSUE TITLE
Test cases should use multi-arch images 

### ISSUE THREAD

**Issue by harche** [containers/libpod#1992]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/ **kind bug**

**Description**

Test cases shipped with libpod for testing [containers](https://github.com/containers/libpod/blob/master/test/test_podman_baseline.sh) and [pods](https://github.com/containers/libpod/blob/master/test/test_podman_pods.sh) fail on architectures other than x64 (e.g. `ppc64le`). This is because the container images used in those test cases are not multi-arch. 

Images in question,

- [registry.access.redhat.com/rhscl/redis-32-rhel7](https://github.com/containers/libpod/blob/master/test/test_podman_baseline.sh#L63)

- [docker/whalesay:latest](https://github.com/containers/libpod/blob/master/test/test_podman_baseline.sh#L440)

- [quay.io/baude/alpine_nginx:latest](https://github.com/containers/libpod/blob/master/test/test_podman_pods.sh#L63)

- [fedora-minimal:28](https://github.com/containers/libpod/blob/master/test/test_podman_pods.sh#L64)

**Steps to reproduce the issue:**

1. https://github.com/containers/libpod/ (make sure you have installed `podman` and `buildah`)

2. run `test/test_podman_baseline.sh` and `test/test_podman_pods.sh` on an architecture other than x64, such as `ppc64le`

**Describe the results you received:**
For the every image in question above, you will get `standard_init_linux.go:203: exec user process caused "exec format error"`

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```bash
[root@rhel8 libpod]# podman version 
Version:       0.10.1.3
Go Version:    go1.10.3
OS/Arch:       linux/ppc64le
```

**Output of `podman info`:**

```
[root@rhel8 libpod]# podman info
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-5.gitdb08685.el8+2131+7e3e9e07.ppc64le
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 6a63dada254d8efb3e9b30ed93ad55ab6622bd29-dirty'
  Distribution:
    distribution: '"rhel"'
    version: "8.0"
  MemFree: 2879324160
  MemTotal: 3722903552
  OCIRuntime:
    package: runc-1.0.0-52.rc5.dev.git2abd837.el8+1884+9fee228c.ppc64le
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 4382982144
  SwapTotal: 4395565056
  arch: ppc64le
  cpus: 1
  hostname: rhel8
  kernel: 4.18.0-40.el8.ppc64le
  os: linux
  uptime: 49h 57m 45.99s (Approximately 2.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - registry.redhat.io
  - quay.io
  - docker.io
store:
  ContainerStore:
    number: 14
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
arch - `ppc64le`
