### ISSUE TITLE
'podman build' cannot create images with empty Dockerfile

### ISSUE THREAD

**Issue by harche** [containers/libpod#1993]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/**kind bug**

**Description**

```bash
[root@rhel8 from-scratch]# cat Dockerfile 
FROM scratch
# 
```
```bash
[root@rhel8 from-scratch]# buildah bud -t test1 .
STEP 1: FROM scratch
STEP 2: COMMIT containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]localhost/test1:latest
Getting image source signatures
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
 32 B / 32 B [==============================================================] 0s
Copying config sha256:45fc63f3e5b4223be70bbd336ef205a59e92eff16b115cc9be722aa56a2a33b2
 340 B / 340 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
--> 45fc63f3e5b4223be70bbd336ef205a59e92eff16b115cc9be722aa56a2a33b2

[root@rhel8 from-scratch]# buildah images 
IMAGE ID             IMAGE NAME                                               CREATED AT             SIZE
45fc63f3e5b4         localhost/test1:latest                                   Dec 12, 2018 05:39     1.71 KB

[root@rhel8 from-scratch]# podman images 
REPOSITORY        TAG      IMAGE ID       CREATED          SIZE
localhost/test1   latest   45fc63f3e5b4   24 seconds ago   1.71kB
```
So `buildah` can create an image from a Dockerfile that has only `FROM scratch`. Now let's try with `podman build`

First cleanup, 
```bash
[root@rhel8 from-scratch]# buildah rmi localhost/test1:latest
untagged: localhost/test1:latest
45fc63f3e5b4223be70bbd336ef205a59e92eff16b115cc9be722aa56a2a33b2

[root@rhel8 from-scratch]# podman images 
[root@rhel8 from-scratch]# buildah images 
[root@rhel8 from-scratch]# 
```
```bash
[root@rhel8 from-scratch]# podman build -t test1 -f Dockerfile
STEP 1: FROM scratch
[root@rhel8 from-scratch]# podman images 
[root@rhel8 from-scratch]# buildah images
[root@rhel8 from-scratch]# 
```
As you can see `podman build` didn't create any image, but `buildah bud` was able to. Now let's try this,
```bash
[root@rhel8 from-scratch]# touch test 
[root@rhel8 from-scratch]# echo "COPY test /" >> Dockerfile 
[root@rhel8 from-scratch]# cat Dockerfile 
FROM scratch
COPY test /
[root@rhel8 from-scratch]# ls
Dockerfile  test
[root@rhel8 from-scratch]# podman build -t test1 -f Dockerfile
STEP 1: FROM scratch
STEP 2: COPY test /
--> e40aa9a9f7f3dc0e05dfd21dd939e88c31cef6d16856631ad089f7c337e53326
STEP 3: COMMIT test1
[root@rhel8 from-scratch]# podman images
REPOSITORY        TAG      IMAGE ID       CREATED         SIZE
localhost/test1   latest   e40aa9a9f7f3   3 seconds ago   2.26kB
[root@rhel8 from-scratch]# buildah images
IMAGE ID             IMAGE NAME                                               CREATED AT             SIZE
e40aa9a9f7f3         localhost/test1:latest                                   Dec 12, 2018 05:45     2.26 KB
[root@rhel8 from-scratch]# 
```
So this time it worked if some content was added in Dockerfile apart from the first line. 

This is issue is affecting the test case here, https://github.com/containers/libpod/blob/master/test/test_podman_build.sh#L23

**Steps to reproduce the issue:**

1. Create a Dockerfile with just `FROM scratch`. `podman build` won't be able to create an image, while `buildah bud` will be able to. 

**Describe the results you received:**
container image should have gotten created.

**Describe the results you expected:**
No container image got created.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.10.1.3
Go Version:    go1.10.3
OS/Arch:       linux/ppc64le
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-5.gitdb08685.el8+2131+7e3e9e07.ppc64le
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 6a63dada254d8efb3e9b30ed93ad55ab6622bd29-dirty'
  Distribution:
    distribution: '"rhel"'
    version: "8.0"
  MemFree: 2873229312
  MemTotal: 3722903552
  OCIRuntime:
    package: runc-1.0.0-52.rc5.dev.git2abd837.el8+1884+9fee228c.ppc64le
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 4382982144
  SwapTotal: 4395565056
  arch: ppc64le
  cpus: 1
  hostname: rhel8
  kernel: 4.18.0-40.el8.ppc64le
  os: linux
  uptime: 50h 47m 42.51s (Approximately 2.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - registry.redhat.io
  - quay.io
  - docker.io
store:
  ContainerStore:
    number: 18
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
