### ISSUE TITLE
podman images -q can show too many images.

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#1997]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# **kind bug**

**Description**

When an image with multiples names is displayed with the `podman images -q` command, multiple images are listed with the same Image ID.  This will break Docker scripts that are aliased that do `podman rmi -f $(podman images -q)`

```
# podman images
REPOSITORY                                TAG      IMAGE ID       CREATED             SIZE
localhost/scratch-image                   latest   f77d8f8c957a   About an hour ago   1.71 kB
docker.io/library/another-scratch-image   latest   f77d8f8c957a   About an hour ago   1.71 kB
localhost/so-many-scratch-images          latest   f77d8f8c957a   About an hour ago   1.71 kB

# podman images -q
f77d8f8c957a
f77d8f8c957a
f77d8f8c957a

# podman rmi -f $(podman images -q)
f77d8f8c957acf00460af2febd50f03bd86b3bcbd22dc1269d36a3131e39708a
unable to find a name and tag match for f77d8f8c957a in repotags: no such image
unable to find a name and tag match for f77d8f8c957a in repotags: no such image
```

**Steps to reproduce the issue:**
```
# cat /root/Build_Multi_Tags.sh
target=scratch-image
target2=another-scratch-image
target3=so-many-scratch-images

buildah bud -t ${target} -t docker.io/${target2} -t ${target3} -f ~/Dockerfile.scratch . 

# cat ~/Dockerfile.scratch
FROM scratch

# /bin/sh /root/Build_Multi_Tags.sh
```

**Describe the results you received:**
An error message when deleting the images and multiple "duplicate" images shown with the '-q' command.

**Describe the results you expected:**
Only unique Image Id's to be shown when there are multiples.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:       0.12.2-dev
Go Version:    go1.10.4
Git Commit:    "b7729cf3eb504680c98ee7703b4b22f00023ce91-dirty"
Built:         Wed Dec 12 11:52:27 2018
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
# podman info
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.10.1.3-1.gitdb08685.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 4a03e555ee4105308fa4d814d4ce02a059af0b7f-dirty'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 766468096
  MemTotal: 2089144320
  OCIRuntime:
    package: runc-1.0.0-57.dev.git9e5aa74.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2142801920
  SwapTotal: 2147479552
  arch: amd64
  cpus: 1
  hostname: localhost.localdomain
  kernel: 4.18.17-200.fc28.x86_64
  os: linux
  rootless: false
  uptime: 27h 12m 35.98s (Approximately 1.12 days)
insecure registries:
  registries:
  - insecure.io
registries:
  registries:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
