### ISSUE TITLE
'make shell' is broken

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#1999]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# **kind bug**

**Description**

The 'make shell' command is shown in the Integration Test Readme (https://github.com/containers/libpod/blob/master/test/README.md) is broken and fails with:

```
STEP 43: FROM babb7658838ed5f22c7dc7afc936cde1df7e52f28264cb22788be797b1057d79
STEP 44: WORKDIR /go/src/github.com/containers/libpod
--> b48558f6617007d55a2e9e9810faaf3c3c79f0160f373e2be193831fb6cc3524
STEP 45: COMMIT libpod_dev:master
/usr/local/bin/podman run --tmpfs -e STORAGE_OPTIONS="--storage-driver=vfs" -e CGROUP_MANAGER=cgroupfs -e TESTFLAGS -e TRAVIS -it --privileged --rm -v /root/tsweeney/workspaces/podman/src/github.com/containers/libpod:/go/src/github.com/containers/libpod libpod_dev:master sh
option --tmpfs requires a value
make: *** [Makefile:168: shell] Error 125

```
It also is using golang v1.10 and probably should be bumped up to v1.11.

**Steps to reproduce the issue:**

1. `make shell`

**Describe the results you received:**

See description

**Describe the results you expected:**
Happy container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:       0.12.2-dev
Go Version:    go1.10.4
Git Commit:    "b7729cf3eb504680c98ee7703b4b22f00023ce91-dirty"
Built:         Wed Dec 12 13:44:26 2018
OS/Arch:       linux/amd64

```

**Output of `podman info`:**

```
# podman info
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.10.1.3-1.gitdb08685.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 4a03e555ee4105308fa4d814d4ce02a059af0b7f-dirty'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 763330560
  MemTotal: 2089144320
  OCIRuntime:
    package: runc-1.0.0-57.dev.git9e5aa74.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2138853376
  SwapTotal: 2147479552
  arch: amd64
  cpus: 1
  hostname: localhost.localdomain
  kernel: 4.18.17-200.fc28.x86_64
  os: linux
  rootless: false
  uptime: 29h 46m 10.22s (Approximately 1.21 days)
insecure registries:
  registries:
  - insecure.io
registries:
  registries:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 24
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
