### ISSUE TITLE
`podman push` to "dir:" has wrong mediaType

### ISSUE THREAD

**Issue by vbatts** [containers/libpod#2013]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# **kind bug**

**Description**
both as format docker `v2s2` and as `oci`, the layers say they're `+gzip` but are just plain tar archives.

**Steps to reproduce the issue:**

1. `podman push vbatts/slackware dir:xx`

2. `podman push --format oci vbatts/slackware dir:xxx`

3.

**Describe the results you received:**
```shell
[vbatts@poly] {master *} ~/xx$ jq . manifest.json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 1644,
    "digest": "sha256:f53237604b1d11c1a11c7868097bcb51ba8b77191199d3ec7f64600b47cb96a1"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 95180800,
      "digest": "sha256:c3d15b6cd3a11ba35b3d1e390aee7de0d959084e8c37df1f3a51339e58838a7f"
    }
  ]
}
[vbatts@poly] {master *} ~/xx$ file c3d15b6cd3a11ba35b3d1e390aee7de0d959084e8c37df1f3a51339e58838a7f
c3d15b6cd3a11ba35b3d1e390aee7de0d959084e8c37df1f3a51339e58838a7f: POSIX tar archive (GNU)
```

and 
```shell
[vbatts@poly] {master *} ~/xxx$ jq . manifest.json 
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:e35d29b9ca3ffefd56aa85397497bc974614f4097c467d93051c3cb0730e29bd",
    "size": 671
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "digest": "sha256:c3d15b6cd3a11ba35b3d1e390aee7de0d959084e8c37df1f3a51339e58838a7f",
      "size": 95180800
    }
  ]
}
[vbatts@poly] {master *} ~/xxx$ file c3d15b6cd3a11ba35b3d1e390aee7de0d959084e8c37df1f3a51339e58838a7f 
c3d15b6cd3a11ba35b3d1e390aee7de0d959084e8c37df1f3a51339e58838a7f: POSIX tar archive (GNU)
```

**Describe the results you expected:**

expected layer mediaType to be gzip (of that the object were itself gzipped)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.10.2-dev
Go Version:    go1.11.2
Git Commit:    "85dbfb33f4c20ca75c86abd687fe0f8a31ce080e"
Built:         Thu Nov  8 13:45:44 2018
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: Unknown
    path: /usr/local/libexec/crio/conmon
    version: 'conmon version , commit: 605136242787b6c7e1c7c8233b74a14c9097e510'
  Distribution:
    distribution: slackware
    version: "14.2"
  MemFree: 2444173312
  MemTotal: 8224837632
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      commit: ccb5efd37fb7c86364786e9137e22948751de7ed
      spec: 1.0.1-dev
  SwapFree: 8359243776
  SwapTotal: 8359243776
  arch: amd64
  cpus: 4
  hostname: poly.batts.lan
  kernel: 4.19.9
  os: linux
  uptime: 3h 31m 44.37s (Approximately 0.12 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 2
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /home/vbatts/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 5
  RunRoot: /var/run/user/1000
```
