### ISSUE TITLE
sudo podman create: error creating container storage: error creating ID-mapped copy of layer "8042eb3a896959439cf57f9e6c964552292c90a8540048fa2efb80cef5d5feec": exit status 1: error during chown: storage-chown-by-maps: chown("usr/bin/ping"): no data available

### ISSUE THREAD

**Issue by edwintorok** [containers/libpod#2015]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]:  **kind bug**

**Description**

Running podman create with sudo fails to create a container.
Running the command without sudo (rootless) creates the container, but  I run into another issue (https://github.com/containers/buildah/issues/1240).

**Steps to reproduce the issue:**

1. `sh -x /usr/bin/fedora-toolbox --sudo -v create`

**Describe the results you received:**
```
+ source /etc/os-release
++ NAME=Fedora
++ VERSION='29.20181216.0 (Workstation Edition)'
++ ID=fedora
++ VERSION_ID=29
++ VERSION_CODENAME=
++ PLATFORM_ID=platform:f29
++ PRETTY_NAME='Fedora 29.20181216.0 (Workstation Edition)'
++ ANSI_COLOR='0;34'
++ LOGO=fedora-logo-icon
++ CPE_NAME=cpe:/o:fedoraproject:fedora:29
++ HOME_URL=https://fedoraproject.org/
++ DOCUMENTATION_URL=https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/
++ SUPPORT_URL=https://fedoraproject.org/wiki/Communicating_and_getting_help
++ BUG_REPORT_URL=https://bugzilla.redhat.com/
++ REDHAT_BUGZILLA_PRODUCT=Fedora
++ REDHAT_BUGZILLA_PRODUCT_VERSION=29
++ REDHAT_SUPPORT_PRODUCT=Fedora
++ REDHAT_SUPPORT_PRODUCT_VERSION=29
++ PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
++ VARIANT='Workstation Edition'
++ VARIANT_ID=workstation
++ OSTREE_VERSION=29.20181216.0
+ release=29
+ prefix_sudo=
+ registry=registry.fedoraproject.org
+ registry_candidate=candidate-registry.fedoraproject.org
+ toolbox_prompt='🔹[\u@\h \W]\$ '
+ exec
+ [[ --sudo = -* ]]
+ case $1 in
+ prefix_sudo=sudo
+ shift
+ [[ -v = -* ]]
+ case $1 in
+ exec
+ shift
+ [[ create = -* ]]
+ fgc=f29
+ '[' '' = '' ']'
+ toolbox_container=fedora-toolbox-edwin:29
+ base_toolbox_image=fedora-toolbox:29
+ toolbox_image=fedora-toolbox-edwin:29
+ '[' create = '' ']'
+ op=create
+ shift
+ case $op in
+ [[ '' = -* ]]
+ exit_if_extra_operand
+ '[' '' '!=' '' ']'
+ create
+ dbus_system_bus_address=unix:path=/var/run/dbus/system_bus_socket
+ tmpfs_size=67108864
++ uuidgen --time
+ working_container_name=fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4
+ sudo buildah inspect --type image fedora-toolbox-edwin:29
error reading image "fedora-toolbox-edwin:29": error reading image: error locating image "fedora-toolbox-edwin:29" for importing settings: error locating image with name "fedora-toolbox-edwin:29": image not known
+ sudo buildah from --name fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4 localhost/fedora-toolbox:29
Error determining manifest MIME type for docker://localhost/fedora-toolbox:29: pinging docker registry returned: Get https://localhost/v2/: dial tcp [::1]:443: connect: connection refused
+ sudo buildah from --name fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4 registry.fedoraproject.org/f29/fedora-toolbox:29
Getting image source signatures
Copying blob sha256:af19ce19de5ee70d1ca852c65f9927fab6ba09de2864af2acdf18d60774bffbd
 85.70 MiB / 85.70 MiB [===================================================] 15s
Copying blob sha256:6df1bfffa76ae08ebcb61de2ae28fbf5f8a84079b6cb316d095cdf4cb5e2bdbb
 182.56 MiB / 182.56 MiB [=================================================] 32s
Copying config sha256:032b427fbbf72ac22336638af319ef989a2b99e038ca087743c132ab71445ed8
 2.69 KiB / 2.69 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
+ sudo buildah run fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4 -- useradd --no-create-home --shell /bin/zsh --uid 1000 --groups wheel edwin
+ sudo buildah run fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4 -- passwd -d edwin
passwd: Note: deleting a password also unlocks the password.
+ sudo buildah run fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4 -- passwd -d root
passwd: Note: deleting a password also unlocks the password.
+ sudo buildah config --volume /home/edwin fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4
+ sudo buildah config --volume /run/user/1000 fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4
+ '[' '' '!=' '' ']'
++ echo unix:path=/var/run/dbus/system_bus_socket
++ cut --delimiter = --fields 2
+ dbus_system_bus_path=/var/run/dbus/system_bus_socket
++ readlink --canonicalize /var/run/dbus/system_bus_socket
+ dbus_system_bus_path=/run/dbus/system_bus_socket
+ sudo buildah config --volume /run/dbus/system_bus_socket fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4
+ sudo buildah config --volume /dev/dri fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4
+ sudo buildah config --user edwin fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4
+ sudo buildah config --workingdir /home/edwin fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4
+ sudo buildah commit --rm fedora-toolbox-working-container-eaa41f4e-0162-11e9-b9cc-e03f49a06ed4 fedora-toolbox-edwin:29
Getting image source signatures
Skipping fetch of repeat blob sha256:8080f9aa6262000ad12d3d7e55331d275d412faa730b75c41bbf444b4ce056e9
Skipping fetch of repeat blob sha256:d399ea65472cbad41d640ec2a09724c2f11ac7fa52636b6cec6905e8fa490865
Copying blob sha256:7424ac1e5e5d7321f68f4e0913626dd6615b4df0736a75054617b7e54b0f9650
 1.96 KiB / 1.96 KiB [======================================================] 0s
Copying config sha256:6f8006ac8fd516cbdcb41c46a3b9df7a5fe8b57738e60737ff6d6bf6c07c9f77
 1.44 KiB / 1.44 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
+ sudo podman inspect --type container fedora-toolbox-edwin:29
error looking up container "fedora-toolbox-edwin:29": no container with name or ID fedora-toolbox-edwin:29 found: no such container
++ awk '( $1 == "MemTotal:" ) { print $2 }' /proc/meminfo
+ total_ram=32898548
+ is_integer 32898548
+ '[' 32898548 '!=' '' ']'
+ '[' 32898548 -eq 32898548 ']'
+ return 0
+ tmpfs_size=16844056576
+ max_uid_count=65536
+ max_minus_uid=64536
+ uid_plus_one=1001
+ sudo podman create --group-add wheel --hostname toolbox --interactive --name fedora-toolbox-edwin:29 --network host --privileged --security-opt label=disable --tmpfs /dev/shm:size=16844056576 --tty --uidmap 1000:0:1 --uidmap 0:1:1000 --uidmap 1001:1001:64536 --volume /home/edwin:/home/edwin --volume /run/user/1000:/run/user/1000 --volume /run/dbus/system_bus_socket:/run/dbus/system_bus_socket --volume /dev/dri:/dev/dri fedora-toolbox-edwin:29 /bin/sh
error creating container storage: error creating ID-mapped copy of layer "8042eb3a896959439cf57f9e6c964552292c90a8540048fa2efb80cef5d5feec": exit status 1: error during chown: storage-chown-by-maps: chown("usr/bin/ping"): no data available
+ echo '/usr/bin/fedora-toolbox: failed to create container fedora-toolbox-edwin:29'
/usr/bin/fedora-toolbox: failed to create container fedora-toolbox-edwin:29
+ exit 1
+ exit
```

**Describe the results you expected:**
Succesful creation of container

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried wiping .local/share/containers and /var/lib/containers, but the problem is still there.
I fodun this while debugging https://pagure.io/teamsilverblue/issue/61

**Output of `podman version`:**

```
Version:       0.12.1.1
Go Version:    go1.11.2
Git Commit:    "0c9259a2c84f6234a29dcd78674c3f4837fd3101"
Built:         Fri Dec  7 19:29:27 2018
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.1-1.git66d3499.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 0c9259a2c84f6234a29dcd78674c3f4837fd3101'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 24436994048
  MemTotal: 33688113152
  OCIRuntime:
    package: runc-1.0.0-59.dev.gitccb5efd.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      commit: 6e5a791a02fefb403034e0de8693d225d52b33a7
      spec: 1.0.1-dev
  SwapFree: 16915623936
  SwapTotal: 16915623936
  arch: amd64
  cpus: 8
  hostname: bolt
  kernel: 4.19.8-300.fc29.x86_64
  os: linux
  rootless: true
  uptime: 53m 1.07s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 11
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/edwin/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 25
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical
