### ISSUE TITLE
podman build --layers: runtime panic

### ISSUE THREAD

**Issue by vbatts** [containers/libpod#2032]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# **kind bug**

**Description**

**Steps to reproduce the issue:**

1. https://github.com/vbatts/copr-build-bazel

2. continually call `podman build --layers .`

3.

**Describe the results you received:**

```shell
[vbatts@getdown] {master *+} ~/src/github.com/vbatts/copr-build-bazel$ podman build --layers .
STEP 1: FROM fedora
STEP 2: WORKDIR /build
--> Using cache a69a57407f64bdff1da2b615dd1bed3c6172944e2d431a9559483959cb6c3350
STEP 3: FROM a69a57407f64bdff1da2b615dd1bed3c6172944e2d431a9559483959cb6c3350
STEP 4: RUN dnf install -y 'dnf-command(builddep)' rpm-build java-1.8.0-openjdk-devel zlib-devel pkgconfig python gcc-c++ make
--> Using cache 4a7d7c39508704e583b59ee5da6bdc700d5ac2c0eb4f71b2cee7e470332ccdb8
STEP 5: FROM 4a7d7c39508704e583b59ee5da6bdc700d5ac2c0eb4f71b2cee7e470332ccdb8
STEP 6: ADD . /build
error checking if cached image exists from a previous build: error checking if copied files match: error resolving symlinks and comparing modified times: "/home/vbatts/src/github.com/vbatts/copr-build-bazel": panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/containers/libpod/vendor/github.com/containers/buildah/imagebuildah.modTimeIsGreater(0x7ffc3fa1f164, 0x33, 0x7ffc3fa1f198, 0x33, 0x7ffc3fa1f1cc, 0x1e, 0xc4202bb698, 0x55f555, 0x4158c4)
        /builddir/build/BUILD/libpod-66d34998316adac9f9d3c0f422705bf4b02011d5/_build/src/github.com/containers/libpod/vendor/github.com/containers/buildah/imagebuildah/chroot_symlink.go:142 +0x3a2
github.com/containers/libpod/vendor/github.com/containers/buildah/imagebuildah.resolveSymlinkTimeModified()
        /builddir/build/BUILD/libpod-66d34998316adac9f9d3c0f422705bf4b02011d5/_build/src/github.com/containers/libpod/vendor/github.com/containers/buildah/imagebuildah/chroot_symlink.go:98 +0x211
github.com/containers/libpod/vendor/github.com/containers/storage/pkg/reexec.Init(0x1133d00)
        /builddir/build/BUILD/libpod-66d34998316adac9f9d3c0f422705bf4b02011d5/_build/src/github.com/containers/libpod/vendor/github.com/containers/storage/pkg/reexec/reexec.go:26 +0x77
main.main()
        /builddir/build/BUILD/libpod-66d34998316adac9f9d3c0f422705bf4b02011d5/_build/src/github.com/containers/libpod/cmd/podman/main.go:51 +0x71
: exit status 2
```

**Describe the results you expected:**

normal build process

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.12.1.1
Go Version:    go1.10.5
Git Commit:    "8a97c0f33b6bd8eabb04f0b8368b78022b53942f-dirty"
Built:         Fri Dec  7 15:01:00 2018
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.1-1.git66d3499.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 8a97c0f33b6bd8eabb04f0b8368b78022b53942f-dirty'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 8722235392
  MemTotal: 16645189632
  OCIRuntime:
    package: runc-1.0.0-59.dev.gitccb5efd.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 12
  hostname: getdown.usersys.redhat.com
  kernel: 4.18.8-200.fc28.x86_64
  os: linux
  rootless: true
  uptime: 2144h 16m 7.03s (Approximately 89.33 days)
insecure registries:
  registries:
  - docker.usersys.redhat.com
  - localhost:5000
  - getdown.local:5000
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 4
  GraphDriverName: vfs
  GraphOptions:
  - overlay.mount_program=/usr/local/bin/fuse-overlayfs
  - overlay.mount_program=/usr/local/bin/fuse-overlayfs
  GraphRoot: /home/vbatts/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 27
  RunRoot: /run/user/1000/run
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
