### ISSUE TITLE
New podman version introduce new issue with selinux and relabelling: relabel failed "/run/netns": operation not supported

### ISSUE THREAD

**Issue by cjeanner** [containers/libpod#2034]
# **kind bug**

**Description**

With latest podman release (see bellow), we encounter an issue when we mount /run/netns with "z,shared" flags:
```
relabel failed "/run/netns": operation not supported
```

**Steps to reproduce the issue:**

1. Create some network namespace in order to ensure /run/netns exists

2. Create a container with /run/netns mounted as a volume (--volume /run/netns:/run/netns:z,shared)

3.

**Describe the results you received:**
The container crashes with an error on the relabelling of /run/netns

**Describe the results you expected:**
It should start the container and proceed to the relabelling.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.12.1.2
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.2-2.git9551f6b.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 97d5f1232f62307696c8b4b2d430e8b771a45873-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 755589120
  MemTotal: 8364449792
  OCIRuntime:
    package: runc-1.0.0-57.dev.git2abd837.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 3376672768
  SwapTotal: 8588881920
  arch: amd64
  cpus: 8
  hostname: undercloud.localdomain
  kernel: 3.10.0-957.1.3.el7.x86_64
  os: linux
  rootless: false
  uptime: 1h 53m 11.26s (Approximately 0.04 days)
insecure registries:
  registries:
  - 192.168.24.1:8787
  - 192.168.24.3:8787
registries:
  registries:
  - registry.centos.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  ContainerStore:
    number: 88
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 35
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
