### ISSUE TITLE
symlinked device paths not supported as "valid device nodes"

### ISSUE THREAD

**Issue by thoraxe** [containers/libpod#2057]
[//]: **kind bug**

**Description**

when attempting to use `/dev/serial/by-id` to attach devices to containers, `podman` complains they are `not a valid device`.

**Steps to reproduce the issue:**

1. `podman run -it --rm -v /opt/zigbeemqtt-data:/app/data:Z --device /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED293B-if00:/dev/ttyACM0:rwm -u 10101 koenkk/zigbee2mqtt`

**Describe the results you received:**
`/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED293B-if00 is not a valid device: not a device node`

**Describe the results you expected:**
running container

**Additional information you deem important (e.g. issue happens only occasionally):**
Not sure if this is a valid bug or not, but I don't see why it shouldn't work.

**Output of `podman version`:**

```
1d [root:/opt/zigbeemqtt-data] # podman version
Version:       0.11.2-dev
Go Version:    go1.10.2
Git Commit:    "7f866bb2a3ccca733c98cf70e621681ecbb8fa06"
Built:         Mon Nov 19 14:44:40 2018
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.11.2-1542656671.gitea928f2d.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 7f866bb2a3ccca733c98cf70e621681ecbb8fa06'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 209743872
  MemTotal: 8197885952
  OCIRuntime:
    package: runc-1.0.0-57.dev.git9e5aa74.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 7237005312
  SwapTotal: 7918841856
  arch: amd64
  cpus: 12
  hostname: dumpster.festive.local
  kernel: 3.10.0-862.14.4.el7.x86_64
  os: linux
  rootless: false
  uptime: 304h 57m 40.75s (Approximately 12.67 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 33
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 98
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS7 host
