### ISSUE TITLE
utime on symlink: permission denied in rootless unprivileged container (symlinks become owned by root?)

### ISSUE THREAD

**Issue by edwintorok** [containers/libpod#2091]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: **kind bug**

**Description**

I am not able to extract https://github.com/ocaml/ocamlbuild/archive/0.12.0.tar.gz, it fails in the utime call on a symlink of a directory.
```
tar: ocamlbuild-0.12.0/examples/07-dependent-projects/libdemo: Cannot utime: Operation not permitted
```
As a workaround I can run my container with `--privileged`, but that doesn't work if I want to build a container, because `podman build` doesn't have a `--privileged` flag.

**Steps to reproduce the issue:**

1. 
```
cat >Dockerfile.bugmin <<EOF
FROM busybox:latest
RUN adduser -D testuser
USER testuser
WORKDIR /tmp
RUN touch -d @1510420249 -h foo
RUN ln -s foo foo-symlink
RUN touch -d @1510420249 -h foo-symlink
EOF
podman build -t bug -f Dockerfile.bugmin

cat >Dockerfile <<EOF
FROM ubuntu:latest
RUN apt-get update && apt-get install -y wget strace && apt-get clean
RUN useradd testuser
USER testuser
WORKDIR /tmp
RUN wget https://github.com/ocaml/ocamlbuild/archive/0.12.0.tar.gz
EOF
podman build -t bug-orig -f Dockerfile
podman run -it bug-orig
tar xf 0.12.0.tar.gz
^D
podman run --privileged -it bug-orig
tar xf 0.12.0.tar.gz
^D
```

**Describe the results you received:**
```
STEP 12: RUN touch -d @1510420249 -h foo-symlink
touch: foo-symlink: Operation not permitted
error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[touch -d @1510420249 -h foo-symlink] Flags:[] Attrs:map[] Message:RUN touch -d @1510420249 -h foo-symlink Original:RUN touch -d @1510420249 -h foo-symlink}: error while running runtime: exit status 1
$ podman run --privileged -it bug-orig
testuser@e1a58f040af0:/tmp$ tar xf 0.12.0.tar.gz
tar: ocamlbuild-0.12.0/examples/07-dependent-projects/libdemo: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
$ podman run --privileged -it bug-orig
testuser@e6b4265e2b28:/tmp$ tar xf 0.12.0.tar.gz
testuser@e6b4265e2b28:/tmp$ exit
```

**Describe the results you expected:**
Able to extract my tarball, set modification/access times on symlink.

**Additional information you deem important (e.g. issue happens only occasionally):**
If I run podman rootless, but I am root inside my container then updating the timestamp works.
If I change to a regular user inside the container it fails as can be seen above.
If I run the same container as privileged (but still rootless) then everything works.

This was initially discovered while tracking down another bug: https://github.com/containers/libpod/issues/2053, but is otherwise unrelated to that bug.

**Output of `podman version`:**

```
podman version
Version:       0.12.1.2
Go Version:    go1.11.2
Git Commit:    "67ab7549b44484cc3f201d7bb2b58b922f8edc24"
Built:         Thu Dec 13 19:35:26 2018
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.2-1.git9551f6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 67ab7549b44484cc3f201d7bb2b58b922f8edc24'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 20816773120
  MemTotal: 33684381696
  OCIRuntime:
    package: runc-1.0.0-66.dev.gitbbb17ef.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ead425507b6ba28278ef71ad06582df97f2d5b5f
      spec: 1.0.1-dev
  SwapFree: 16915623936
  SwapTotal: 16915623936
  arch: amd64
  cpus: 8
  hostname: bolt
  kernel: 4.19.13-300.fc29.x86_64
  os: linux
  rootless: true
  uptime: 2h 45m 48.5s (Approximately 0.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 44
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/edwin/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 34
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 29 Silverblue
