### ISSUE TITLE
"podman start -a" fails to start previously created container after fresh boot

### ISSUE THREAD

**Issue by sysrich** [containers/libpod#2107]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind bug**

**Description**

I have a few previously created podman containers (created by "podman create ....") started by systemd services.

The systemd services were very simple, doing no more than:

```
ExecStart=/usr/bin/podman start -a ncserver
ExecStop=/usr/bin/podman stop ncserver
```

On a fresh reboot, these ExecStarts would all fail

Trying to do `/usr/bin/podman start -a ncserver"` manually after a fresh reboot would provide the following error message

> unable to start container 0e0819a1019bb9d92f3dd674dd7f87e81d18e4bc0634eba955249536994d191b: container create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/exec: no such file or directory\""
> : internal libpod error

**Steps to reproduce the issue:**

1. Create a container with "podman create"

2. Reboot

3. Attempt to start container with "podman start"

**Describe the results you received:**

Error 

> unable to start container 0e0819a1019bb9d92f3dd674dd7f87e81d18e4bc0634eba955249536994d191b: container create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/exec: no such file or directory\"" : internal libpod error

Container did not start

**Describe the results you expected:**

Container should start without errors

**Additional information you deem important (e.g. issue happens only occasionally):**

The problem can be worked around by doing a "podman create" or "podman run" before the "podman start"

There does not need to be any relationship between the create/run and the container you wish to start. For example, "podman run hello-world" is enough to make all failing "podman start" calls work again.

Even if this "podman create" call fails (for example, trying to create a container with a name that matches the previously created containers), all subsequent "podman run" calls will work fine

Therefore as a workaround I've added "ExecStartPre=-/usr/bin/podman create ...." calls into my systemd unit files for each container. They normally fail as the containers already exist, but then the ExecStarts work ;)

**Output of `podman version`:**

```
Version:       0.11.1.1
Go Version:    go1.11.1
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.11.1.1-2.1.x86_64
    path: /usr/lib/podman/bin/conmon
    version: 'conmon version 1.12.0-dev, commit: '
  Distribution:
    distribution: '"opensuse-tumbleweed-kubic"'
    version: "20180926"
  MemFree: 12480204800
  MemTotal: 16487211008
  OCIRuntime:
    package: runc-1.0.0~rc6-1.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: r2d2
  kernel: 4.19.11-1-default
  os: linux
  rootless: false
  uptime: 11m 12.27s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ContainerStore:
    number: 2
  GraphDriverName: btrfs
  GraphOptions: []
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Build Version: 'Btrfs v4.17.1 '
    Library Version: "102"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical system, openSUSE Kubic, MicroOS system role
