### ISSUE TITLE
storage.conf oscillates between camel and lower case formats

### ISSUE THREAD

**Issue by debarshiray** [containers/libpod#2158]
/kind bug

When I remove the local configuration (`rm -f ~/.config/containers/*.conf)` and data (`sudo rm -rf ~/.local/share/containers`), and start from a clean state, `podman` creates a new `storage.conf` for me. The format is sometimes in camel case, and at other times in lower case.

Camel case:
```
RunRoot = "/run/user/1000"
GraphRoot = "/home/rishi/.local/share/containers/storage"
GraphDriverName = "overlay"
GraphDriverOptions = ["overlay.mount_program=/usr/bin/fuse-overlayfs"]
```

Lower case:
```
[storage]
  driver = "overlay"
  runroot = "/run/user/1000"
  graphroot = "/home/rishi/.local/share/containers/storage"
  [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
```

I learnt in `#podman` that the latter is the correct format.

I haven't been able to figure out a reliable reproducer, but I have seen it fail with this error on some occasions when the camel case format was in play:
```
ERRO[0000] 'overlay' is not supported over extfs at "/home/rishi/.local/share/containers/storage/overlay"
```

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 21:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 1806233600
  MemTotal: 8127070208
  OCIRuntime:
    package: runc-1.0.0-66.dev.gitbbb17ef.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ead425507b6ba28278ef71ad06582df97f2d5b5f
      spec: 1.0.1-dev
  SwapFree: 4133482496
  SwapTotal: 4133482496
  arch: amd64
  cpus: 4
  hostname: kolache
  kernel: 4.19.13-300.fc29.x86_64
  os: linux
  rootless: true
  uptime: 2h 28m 31.86s (Approximately 0.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/rishi/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/rishi/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 2
  RunRoot: /run/user/1000
```
