### ISSUE TITLE
Volume is not created when using VOLUME in Dockerfile

### ISSUE THREAD

**Issue by tvass** [containers/libpod#2170]
/kind bug

Podman does NOT create a volume at run when it is specified in the Dockerfile.

**Steps to reproduce the issue:**

1. Create a basic Dockerfile that use VOLUME syntax.
```
FROM ubuntu
RUN mkdir /myvol
RUN echo "hello world" > /myvol/greeting
VOLUME /myvol
```
2. Build
```
$ buildah bud -t test .
STEP 1: FROM ubuntu
STEP 2: RUN mkdir /myvol
STEP 3: RUN echo "hello world" > /myvol/greeting
STEP 4: VOLUME /myvol
STEP 5: COMMIT containers-storage:[overlay@/home/tvass/.local/share/containers/storage+/run/user/1000:overlay.mount_program=/usr/bin/fuse-overlayfs,overlay.mount_program=/usr/bin/fuse-overlayfs]localhost/test:latest
Getting image source signatures
Skipping fetch of repeat blob sha256:2fb7bfc6145d0ad40334f1802707c2e2390bdcfc16ca636d9ed8a56c1101f5b9
Skipping fetch of repeat blob sha256:c8dbbe73b68c96e3252f8191226b700d4f4b284154624fa40a2e6a0c42712a0d
Skipping fetch of repeat blob sha256:1f6b6c7dc482cab1c16d3af058c5fa1782e231cac9aab4d9e06b3f7d77bb1a58
Skipping fetch of repeat blob sha256:2c77720cf318a4c7eaee757162e6bfc364c3ed83a96a525bc20c548e0f75f1af
Copying blob sha256:c6d18d2f24e2942cdf5fabb4c8cd06202fb3f559fa6e57a8d1996e236299a798
 152 B / 152 B [============================================================] 0s
Copying config sha256:8410741373f6544ba90712f8e3faada622526ae444d870288d50bbb10f4983ef
 2.56 KiB / 2.56 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
--> 8410741373f6544ba90712f8e3faada622526ae444d870288d50bbb10f4983ef
```
3. Run 
```
podman run --rm -ti test sh
# 
```
On a separate terminal, check volumes present :
**Describe the results you received:**

```
$ podman volume ls
DRIVER   VOLUME NAME
$
```

**Describe the results you expected:**
We should have a volume.

```
$ podman volume ls
DRIVER   VOLUME NAME
local    xxxxxxxxxxxxxxxxxxxxxxxxxx
$
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Could you please tell me if this is expected or a bug ? 
Thanks

**Output of `podman version`:**

```
podman version 0.12.1.2
```

**Output of `podman info`:**

```
podman info
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.2-1.git9551f6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 67ab7549b44484cc3f201d7bb2b58b922f8edc24'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 6490259456
  MemTotal: 16450523136
  OCIRuntime:
    package: runc-1.0.0-66.dev.gitbbb17ef.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ead425507b6ba28278ef71ad06582df97f2d5b5f
      spec: 1.0.1-dev
  SwapFree: 8296329216
  SwapTotal: 8296329216
  arch: amd64
  cpus: 8
  hostname: dhcp-10-17-17-222.yul.redhat.com
  kernel: 4.19.14-300.fc29.x86_64
  os: linux
  rootless: true
  uptime: 4h 54m 21.87s (Approximately 0.17 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/tvass/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 20
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 29
