### ISSUE TITLE
[Q] systemd in a container: how to get debian:9 up without unconfined?

### ISSUE THREAD

**Issue by space88man** [containers/libpod#2173]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

With seccomp at defaults, systemd in a debian:9 container won't startup

**Steps to reproduce the issue:**
[UPDATE] This works on Fedora 29 podman 0.12 so might be a CentOS/RHEL issue

1. create image with systemd-sysv installed from debian:9
buildah run  $CON apt update
buildah run $CON apt install -y systemd systemd-sysv
buildah commit $CON debian_and_systemd:9

2. podman run --entrypoint=/sbin/init --stop-signal=RTMIN+3 debian_and_systemd:9

3.

**Describe the results you received:**
```
Failed to determine whether /sys is a mount point: Operation not permitted
Failed to determine whether /proc is a mount point: Operation not permitted
Failed to determine whether /dev is a mount point: Operation not permitted
Failed to determine whether /dev/shm is a mount point: Operation not permitted
Failed to determine whether /run is a mount point: Operation not permitted
Failed to determine whether /run/lock is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup/systemd is a mount point: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.

```
and systemd won't start up in the container

**Describe the results you expected:**
systemd runs in a debian:9 container

**Additional information you deem important (e.g. issue happens only occasionally):**
1. debian:9 - works if seccomp is unconfined
1. centos:7 - works
1. ubuntu:18.04 - build images in the same way to install systemd system-sysv; works
1. Host is CentOS 7.6.1810  

I'm trying to understand what is the minimal seccomp to allow the debian:9 systemd to start up.

Is there a recommended way to bisect seccomp between unconfined and default?

**Output of `podman version`:**
```
Version:       0.11.1.1
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**
```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.11.1.1-3.git594495d.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: d61f1d176b2b01a5e46efbf236427ece745b92f2-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 96456704
  MemTotal: 2026344448
  OCIRuntime:
    package: runc-1.0.0-57.dev.git2abd837.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: localhost.localdomain
  kernel: 3.10.0-957.1.3.el7.x86_64
  os: linux
  rootless: false
  uptime: 917h 12m 30.11s (Approximately 38.21 days)
insecure registries:
  registries: []
registries:
  registries:
  - registry.centos.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 4
  RunRoot: /var/run/containers/storage

```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
