### ISSUE TITLE
Running without namespace mapping as non-root

### ISSUE THREAD

**Issue by seanmcneil3** [containers/libpod#2180]
/kind feature

**Description**

There is a use-case where I want to basically run a container as non-root and have no uid or gid mapping. I cannot figure out the correct way to do this. Whenever I use the --user option it will do namespace mapping.

**Steps to reproduce the issue:**

1. podman run -it --rm --privileged --user=$(id -u):$(id -g) --volume="/etc/passwd:/etc/passwd:ro" --volume="/etc/group:/etc/group:ro" --volume=$PWD:$PWD" --workdir="$PWD" container_name bash

2. touch some_nonexistent_filename

3. exit

**Describe the results you received:**

ls -l some_nonexistent_filename

file has a uid/gid that was mapped to not be user uid/gid.

**Describe the results you expected:**

ls -l some_nonexistent_filename

file uid/gid that is exactly user uid/gid.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.0.0
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 7128797184
  MemTotal: 33742376960
  OCIRuntime:
    package: runc-1.0.0-66.dev.gitbbb17ef.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ead425507b6ba28278ef71ad06582df97f2d5b5f
      spec: 1.0.1-dev
  SwapFree: 16834621440
  SwapTotal: 16852709376
  arch: amd64
  cpus: 16
  hostname: desk.mcneil.com
  kernel: 4.19.15-300.fc29.x86_64
  os: linux
  rootless: true
  uptime: 23h 52m 12.77s (Approximately 0.96 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/sean/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/sean/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 0
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

/etc/subuid has
user:165536:65536

/etc/subgid has
user:165536:65536
