### ISSUE TITLE
podman build improperly creating intermediate images

### ISSUE THREAD

**Issue by seanmcneil3** [containers/libpod#2194]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman build is keeping intermediate layers around as it appears to default to

export BUILDAH_LAYERS=true

**Steps to reproduce the issue:**

1. Create a Dockerfile with multiple RUN commands. As an example, the start of a centos:6 environment build I have

FROM		centos:6
MAINTAINER	Sean McNeil <sean@mcneil.com>
WORKDIR		/tmp

RUN	yum install -y wget
RUN	wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
RUN	rpm -ivh epel-release-6-8.noarch.rpm
RUN	yum clean expire-cache
RUN	yum update -y

2. Create an image with "podman build --squash -t sean/centos:6 ."

3. Run "podman images" and see many layers.

4. No build command arguments affect the creation of the layers. I've tried --rm=true and --force-rm=true.

**Describe the results you received:**

Looks like 1 image is listed for each RUN command.

**Describe the results you expected:**

There should only be 2 layers that are created from the build. There should be the original layer copied with the FROM declaration and then the committed layer for the end of the build which is named "sean/centos:6".

**Additional information you deem important (e.g. issue happens only occasionally):**

If I add

export BUILDAH_LAYERS=false

I get the expected behavior.

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Tue Jan 15 03:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 6140149760
  MemTotal: 33742360576
  OCIRuntime:
    package: runc-1.0.0-66.dev.gitbbb17ef.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ead425507b6ba28278ef71ad06582df97f2d5b5f
      spec: 1.0.1-dev
  SwapFree: 16636178432
  SwapTotal: 16852709376
  arch: amd64
  cpus: 16
  hostname: desk.mcneil.com
  kernel: 4.19.15-300.fc29.x86_64
  os: linux
  rootless: true
  uptime: 69h 9m 20.77s (Approximately 2.88 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/sean/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/sean/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 3
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 29 host
