### ISSUE TITLE
podman-load not tagging image as documented in man page

### ISSUE THREAD

**Issue by seanmcneil3** [containers/libpod#2210]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman load does not behave as documented.

**Steps to reproduce the issue:**

1. Take existing image such as example:1, save to image as something like "podman -o image.tar example:1".

2. Delete the image such as "podman rmi example:1

3. Load the image as "podman load -i image.tar example:1

**Describe the results you received:**

Image is loaded without being tagged.

**Describe the results you expected:**

"man podman-load" documents the command with "podman load [OPTIONS] NAME[:TAG|@DIGEST]". It should have essentially tagged the image as the command "podman tag id example:1" would do.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Tue Jan 15 03:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 2177036288
  MemTotal: 33742360576
  OCIRuntime:
    package: runc-1.0.0-66.dev.gitbbb17ef.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ead425507b6ba28278ef71ad06582df97f2d5b5f
      spec: 1.0.1-dev
  SwapFree: 16580866048
  SwapTotal: 16852709376
  arch: amd64
  cpus: 16
  hostname: desk.mcneil.com
  kernel: 4.19.15-300.fc29.x86_64
  os: linux
  rootless: true
  uptime: 118h 57m 55.37s (Approximately 4.92 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/sean/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/sean/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 4
  RunRoot: /run/user/1000

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
