### ISSUE TITLE
podman fails if apparmor_parser not installed

### ISSUE THREAD

**Issue by Vogtinator** [containers/libpod#2228]
/kind bug

**Description**

If apparmor is enabled, but apparmor_parser is not installed, podman fails with

`exec: "apparmor_parser": executable file not found in $PATH`.

It should disable apparmor support in this case.

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-2.1.x86_64
    path: /usr/lib/podman/bin/conmon
    version: 'conmon version 1.12.0-dev, commit: '
  Distribution:
    distribution: '"opensuse-tumbleweed-kubic"'
    version: "20190121"
  MemFree: 8020680704
  MemTotal: 8361922560
  OCIRuntime:
    package: runc-1.0.0~rc6-2.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 3
  hostname: e104
  kernel: 4.20.0-1-default
  os: linux
  rootless: false
  uptime: 9m 21.19s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: btrfs
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Build Version: 'Btrfs v4.19.1 '
    Library Version: "102"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```
