### ISSUE TITLE
podman ps --format "{{.Mounts}}" doesn't work

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#2238]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

kind bug
**Description**

The command:
`# /usr/local/bin/podman ps -a --format "{{.Mounts}}"

doesn't work as doucmented.

**Steps to reproduce the issue:**

1. See description

**Describe the results you received:**
```
# /usr/local/bin/podman ps -a --format "{{.Mounts}}"
template: output:1:2: executing "output" at <.Mounts>: can't evaluate field Mounts in type shared.PsContainerOutput
```

**Describe the results you expected:**

The list of mounts or if not present, and empty set.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:       1.0.1-dev
Go Version:    go1.10.4
Git Commit:    "37002ad549fc6bd5dd7cb126433d3a9580451a70-dirty"
Built:         Fri Jan 18 19:34:53 2019
OS/Arch:       linux/amd64

```

**Output of `podman info`:**

```
# podman info
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 327964bfa96f91f39042b87b3e52388f448fd66e'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 1091354624
  MemTotal: 2089144320
  OCIRuntime:
    package: containerd.io-1.2.2-3.fc28.x86_64
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 96ec2177ae841256168fcf76954f7177af9446eb
      spec: 1.0.1-dev
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 1
  hostname: localhost.localdomain
  kernel: 4.18.17-200.fc28.x86_64
  os: linux
  rootless: false
  uptime: 10h 17m 0.94s (Approximately 0.42 days)
insecure registries:
  registries:
  - insecure.io
registries:
  registries:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtual Machine Running Fedora 29
