### ISSUE TITLE
when use "podman pod stats --format '{{GO template}}'","--format" option doesn't work

### ISSUE THREAD

**Issue by wenj1104** [containers/libpod#2258]
/kind bug

**Description**

When i use `podman pod stats --format`  to view resource usage statistics for the pods,if I use a Go template,`--format` option does not work.

**Steps to reproduce the issue:**

1. create a pod.
```
# podman pod create
3cc2ebb00c7512f3ba41ef4f2d8c28181c89dad21b603fb9c4bba46ad20cfb51

# podman pod ps
POD ID         NAME             STATUS    CREATED          # OF CONTAINERS   INFRA ID
3cc2ebb00c75   sad_heisenberg   Running   16 seconds ago   1                 adae4b38c879
```
2. use a GO template to view resource usage statistics.
```
# podman pod stats -l --no-stream --format "{{.MemUsage}}"

POD            CID            NAME         CPU %  MEM USAGE/ LIMIT    MEM %  NET IO              BLOCK IO            PIDS
3cc2ebb00c75   adae4b38c879   3cc2ebb00c   5.85%  1.032MB / 67.51GB   0.00%  978B / 6.541kB      -- / --             1
```
As you can see, the output of the command is not in the specified format.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 15:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 6033768448
  MemTotal: 67505704960
  OCIRuntime:
    package: runc-1.0.0-67.dev.git12f6a99.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: d164d9b08bf7fc96a931403507dd16bced11b865
      spec: 1.0.1-dev
  SwapFree: 33820766208
  SwapTotal: 33820766208
  arch: amd64
  cpus: 24
  hostname: fedora29
  kernel: 4.18.16-300.fc29.x86_64
  os: linux
  rootless: false
  uptime: 123h 51m 48.15s (Approximately 5.12 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
```
