### ISSUE TITLE
memory parameter for CreateContainer varlink API does not have any effect

### ISSUE THREAD

**Issue by KKoukiou** [containers/libpod#2277]
**Steps to reproduce the issue:**

1.  sudo varlink call unix:/run/podman/io.podman/io.podman.CreateContainer '{"create": { "name": "test", "image": "busybox","command": ["sh"], "resources": {"memory":1048576} }}'

2. sudo podman inspect --format '{{.HostConfig.Memory}}' test

**Describe the results you received:**
Verify that memory is not configured as expected but instead it's 0, which leads to no memory limit.

**Describe the results you expected:**
Expected to have Memory: 1048576 as I configured.
If I run the container with podman run I can limit the memory as expected.
```sudo podman run -m 1G busybox sh```

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 21:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 2516893696
  MemTotal: 11978817536
  OCIRuntime:
    package: runc-1.0.0-67.dev.git12f6a99.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: d164d9b08bf7fc96a931403507dd16bced11b865
      spec: 1.0.1-dev
  SwapFree: 6039793664
  SwapTotal: 6039793664
  arch: amd64
  cpus: 4
  hostname: sequoia
  kernel: 4.20.5-200.fc29.x86_64
  os: linux
  rootless: true
  uptime: 5h 51m 15.45s (Approximately 0.21 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/kkoukiou/.config/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: vfs
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/kkoukiou/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 2
  RunRoot: /run/user/1000/run
```
