### ISSUE TITLE
Feature request: Relay runc logs to podman

### ISSUE THREAD

**Issue by filbranden** [containers/libpod#2285]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

When passing podman a `--log-level debug` or similar setting, it would be great if it could collect the `runc` logs and show them together with the podman logs.

**Steps to work around the issue:**

It is possible to collect `runc` logs, but that needs a wrapper and logs the runs to separate files (so not really good for finding correlations.)

For example, create `/usr/bin/logged_runc.sh` with contents:

```sh
#!/bin/sh
exec /usr/bin/runc --log "/tmp/runc.log-$$-$(date +%Y%m%dT%H%M%S)" "$@"
```

And then run:

```
# podman --log-level debug --runtime /usr/bin/logged_runc.sh run -t fedora:28 echo "Hello world!"
```

**Possible implementation:**

Perhaps a good way to implement this would be to open a pipe, clear FD_CLOEXEC on its writing end and pass `runc` a `--log /dev/fd/X` argument to write logs to that pipe. (At least, this is what I'd do if this was C.)

In podman, have a go routine read from that pipe and relay that message through the native logging system.

This assumes this podman process (with the go routine reading from the pipe) will be around for the lifetime of runc, not sure that's the case and there's such a thing.

I'm happy to contribute code, if needed. But I'd like some pointers on whether this is a good approach and which pitfalls to look for.

**Output of `podman version`:**

```
Version:            1.0.1-dev
RemoteAPI Version:  1
Go Version:         go1.12beta2
Git Commit:         "c9e1f365e294135968bdd4d754dca7e1044587dc-dirty"
Built:              Thu Jan 24 11:06:57 2019
OS/Arch:            linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.1-17.dev.gitd5593b8.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: d3cac30f4e81084c7bc36922e02817841ccc3456'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 888102912
  MemTotal: 8360546304
  OCIRuntime:
    package: runc-1.0.0-70.dev.gite4fa8a4.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 5b54487295859772ddfc57918f10e82994e501ae
      spec: 1.0.1-dev
  SwapFree: 2146942976
  SwapTotal: 2147479552
  arch: amd64
  cpus: 8
  hostname: rawhide.libvirt
  kernel: 5.0.0-0.rc3.git0.1.fc30.x86_64
  os: linux
  rootless: true
  uptime: 291h 32m 50.81s (Approximately 12.12 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/filbranden/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/filbranden/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /run/user/5192
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

QEMU-KVM, libvirt.
