### ISSUE TITLE
Problem with 'podman --storage-driver vfs' in rootless mode

### ISSUE THREAD

**Issue by SergeyBear** [containers/libpod#2347]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When unprivileged user switch from default 'overlay' to 'vfs' with podman using '--storage-driver' error occur:

```
Could not get runtime: database storage graph driver overlay does not match our storage graph driver vfs: database configuration mismatch
```

Same command with buildah works well.

I'm running container with centos 7 and buildah to build images, so vfs is my only choice.
Switching host to vfs is a stap back in performance.
**P.S.** Selinux is in permissive mode.

**Steps to reproduce the issue:**

useradd test
su - test
buildah  --storage-driver=vfs pull fedora
buildah --storage-driver=vfs images

```
IMAGE NAME                                               IMAGE TAG            IMAGE ID             CREATED AT             SIZE
docker.io/library/fedora                                 latest               26ffec5b4a8a         Jan 16, 2019 21:24     283 MB
```

podman --storage-driver=vfs images

```
Could not get runtime: database storage graph driver overlay does not match our storage graph driver vfs: database configuration mismatch
```

**Describe the results you received:**
```
Could not get runtime: database storage graph driver overlay does not match our storage graph driver vfs: database configuration mismatch
```

**Describe the results you expected:**
```
IMAGE NAME                                               IMAGE TAG            IMAGE ID             CREATED AT             SIZE
docker.io/library/fedora                                 latest               26ffec5b4a8a         Jan 16, 2019 21:24     283 MB
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 20:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `buildah version`:**

```
Version:         1.6
Go Version:      go1.11.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 359284736
  MemTotal: 2087301120
  OCIRuntime:
    package: runc-1.0.0-67.dev.git12f6a99.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: d164d9b08bf7fc96a931403507dd16bced11b865
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: fedora
  kernel: 4.20.7-200.fc29.x86_64
  os: linux
  rootless: true
  uptime: 3h 23m 14.83s (Approximately 0.12 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/gitlab-runner/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/gitlab-runner/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 3
  RunRoot: /tmp/user/991
```

**Output of `buildah info`:**

```
{
    "host": {
        "Distribution": {
            "distribution": "fedora",
            "version": "29"
        },
        "MemTotal": 2087301120,
        "MenFree": 209571840,
        "SwapFree": 0,
        "SwapTotal": 0,
        "arch": "amd64",
        "cpus": 2,
        "hostname": "fedora",
        "kernel": "4.20.7-200.fc29.x86_64",
        "os": "linux",
        "rootless": true,
        "uptime": "3h 29m 59.77s (Approximately 0.12 days)"
    },
    "store": {
        "ContainerStore": {
            "number": 2
        },
        "GraphDriverName": "overlay",
        "GraphOptions": [
            "overlay.mount_program=/usr/bin/fuse-overlayfs"
        ],
        "GraphRoot": "/home/gitlab-runner/.local/share/containers/storage",
        "GraphStatus": {
            "Backing Filesystem": "extfs",
            "Native Overlay Diff": "false",
            "Supports d_type": "true"
        },
        "ImageStore": {
            "number": 3
        },
        "RunRoot": "/tmp/user/991"
    }
}
```

**Fedora 29**
