### ISSUE TITLE
Podman is unable to create a pod when running as a regular non-root user

### ISSUE THREAD

**Issue by jgillich** [containers/libpod#2349]
/kind bug

**Description**

Podman is unable to create a pod when running as a regular non-root user.
1. `$ podman pod create --name foobar`

**Describe the results you received:**
```
$ podman pod create --name foobar
error starting Infra Container: container create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/run/user/1000/overlay-containers/c9778b670d4317fbaffca5e6c30010890faf695c0a6d06e72157c01a471e87c5/userdata/hosts\\\" to rootfs \\\"/var/home/jgillich/.local/share/containers/storage/overlay/52400d797a4257d93af7505ab63e17e09fa2734ccbe24043caf576abbd073d8d/merged\\\" at \\\"/var/home/jgillich/.local/share/containers/storage/overlay/52400d797a4257d93af7505ab63e17e09fa2734ccbe24043caf576abbd073d8d/merged/etc/hosts\\\" caused \\\"operation not permitted\\\"\""
: internal libpod error
```

**Describe the results you expected:**

Podman should create the pod.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 21:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 655138816
  MemTotal: 8226537472
  OCIRuntime:
    package: runc-1.0.0-67.dev.git12f6a99.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: d164d9b08bf7fc96a931403507dd16bced11b865
      spec: 1.0.1-dev
  SwapFree: 8352690176
  SwapTotal: 8363438080
  arch: amd64
  cpus: 4
  hostname: thinkpad.localdomain
  kernel: 4.20.7-200.fc29.x86_64
  os: linux
  rootless: true
  uptime: 13h 2m 57.87s (Approximately 0.54 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/jgillich/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/jgillich/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 3
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 29 Silverblue laptop.

I'm not sure if this is a bug or working as intended. If it's not, the error message could probably be improved (= not state `internal libpod error`).

Launching standalone containers works as expected, so this is not a general permission problem.
