### ISSUE TITLE
podman push --all-tags

### ISSUE THREAD

**Issue by SergeyBear** [containers/libpod#2369]
/kind feature

**Description**

It would be very usefull to have '--all-tags' option for ```podman push```, so to be able to push all image tags at once to remote registry.

**Usecase:** I'm building image from scratch and automatically tag local image with installed package version by build script. Then in separate CI job I'm testing image and if it's ok, I push it to remote registry. The problem is CI cannot know package version to use it as a tag in push job and without a tag podman push only latest image. Using whole build -> test -> push in single script makes it hard to maintain and using of CI/CD less usefull.

**Steps to reproduce the issue:**

```
buildah pull busybox
buildah tag busybox busybox:1.2.3
```

**Describe the results you received:**
```
podman push busybox docker://<remote_registry>/busybox
skopeo inspect docker://<remote_registry>/busybox
...
"RepoTags": [
        "latest"
    ],
...
```

**Describe the results you expected:**
```
podman push --all-tags busybox docker://<remote_registry>/busybox
skopeo inspect docker://<remote_registry>/busybox
...
"RepoTags": [
        "latest",
        "1.2.3"
    ],
...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 20:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 1689677824
  MemTotal: 2087301120
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: fedora
  kernel: 4.20.8-200.fc29.x86_64
  os: linux
  rootless: true
  uptime: 1h 56m 14.06s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/gitlab-runner/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/gitlab-runner/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 3
  RunRoot: /tmp/user/991
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
fedora 29
