### ISSUE TITLE
Unable to set dns option to podman create on a container with host networking

### ISSUE THREAD

**Issue by robmv** [containers/libpod#2383]
/kind bug

**Description**

bb6c1cf8d1667c7c8e4d539ea2250a18fa89a58a disables the possibility of setting up DNS when the container is run in host networking mode.

My use case is a Samba AD domain as a container, AD domains provide they own DNS server. We don't expose the AD DNS server to the clients, the host run bind that forwards to the container.

The container is run in host networking, with a dedicated IP address, because of some issues of how Samba interacts within the container.

**Steps to reproduce the issue:**

1. podman create --network host  --dns 127.0.0.1 ...

**Describe the results you received:**

Using the --dns option when network mode is shared with the host or another container is not allowed:

```
specifying DNS flags when network mode is shared with the host or another container is not allowed
```

**Describe the results you expected:**

Previous versions did not have this error message

**Output of `podman version`:**

```
Version:       0.12.1.2
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.2-2.git9551f6b.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: b909c9e1a3e8f14d5694a118fb9c0c0325a31d4f-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 10476048384
  MemTotal: 12380729344
  OCIRuntime:
    package: runc-1.0.0-59.dev.git2abd837.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 6308229120
  SwapTotal: 6308229120
  arch: amd64
  cpus: 8
  hostname: localhost.localdomain
  kernel: 3.10.0-957.5.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 1h 53m 50.83s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage

```

**Additional environment details:**

Host is CentOS 7

**Workaround:**

Mount a single file volume to /etc/resolv.conf with the dns setting preconfigured
