### ISSUE TITLE
make 'podman play kube' set local volume mounts

### ISSUE THREAD

**Issue by ikke-t** [containers/libpod#2536]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Currently, podman play kube fails to create any kind of persistent pods. Which in case of e.g. database is important. Please add handling for hostPath type of volumes, e.g:

```
  containers:
   ...
    volumeMounts:
    - mountPath: /var/lib/postgresql/data/pgdata
      name: db-volume
  volumes:
  - name: db-volume
    hostPath:
      # directory location on host
      path: /tmp/pg_data
      # this field is optional
      type: Directory
```

Podman should
1. recognize there is volumeMounts and hostPath sections
2. create the requested directory if missing (optional)
3. set selinux labels to it (:z or :Z -kind)
4. add the mount to requested mount points
5. do the rest of starting the container

This is already implemented in command line options, so probably just affects the play kube parsing.

Issue is related to this one, but does not require it: #2303. It would just help moving from command line definitions to yaml.

**Steps to reproduce the issue:**

1. Generate postgres.yml:

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-03-03T12:10:26Z"
  labels:
    app: postgres
  name: postgres
spec:
  containers:
  - command:
    - docker-entrypoint.sh
    - postgres
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/9.6/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
    - name: container
      value: podman
    - name: PG_VERSION
      value: 9.6.11-1.pgdg90+1
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: POSTGRES_PASSWORD
      value: pg
    - name: POSTGRES_USER
      value: pg
    - name: POSTGRES_DB
      value: test
    - name: GOSU_VERSION
      value: "1.11"
    - name: LANG
      value: en_US.utf8
    - name: PG_MAJOR
      value: "9.6"
    image: docker.io/library/postgres:9.6
    name: postgres
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    workingDir: /
    volumeMounts:
    - mountPath: /var/lib/postgresql/data/pgdata
      name: db-volume
  volumes:
  - name: db-volume
    hostPath:
      # directory location on host
      path: /tmp/pg_data
      # this field is optional
      type: Directory
```

2. ```sudo podman play kube postgres-volume.yml```

3. verify mounts exist: ```sudo podman inspect postgres|less```

**Describe the results you received:**

Currently it totally ignores those sections, no mounts get created.

**Describe the results you expected:**

Volume mounts to be in place, just like ```podman run -v``` would do.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[ikke@ohuska ~]$ podman version
Version:            1.2.0-dev
RemoteAPI Version:  1
Go Version:         go1.12
OS/Arch:            linux/amd64

[ikke@ohuska ~]$ rpm -qi podman
Name        : podman
Epoch       : 2
Version     : 1.2.0
Release     : 5.dev.git9adcda7.fc31
Architecture: x86_64
Install Date: Sun 03 Mar 2019 02:05:43 PM EET
Group       : Unspecified
Size        : 51676426
License     : ASL 2.0
Signature   : (none)
Source RPM  : podman-1.2.0-5.dev.git9adcda7.fc31.src.rpm
Build Date  : Sat 02 Mar 2019 07:29:35 AM EET
Build Host  : buildvm-28.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://podman.io/
Bug URL     : https://bugz.fedoraproject.org/podman
Summary     : Manage Pods, Containers and Container Images
Description :
Manage Pods, Containers and Container Images
libpod provides a library for applications looking to use
the Container Pod concept popularized by Kubernetes.
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12
  podman version: 1.2.0-dev
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.2.0-5.dev.git9adcda7.fc31.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 3e600fb5a3d38abd075757cce69b14c5c060bdb3'
  Distribution:        
    distribution: fedora
    version: "29"
  MemFree: 220405760          
  MemTotal: 8052445184          
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc                            
    version: |-     
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 7713058816
  SwapTotal: 8199860224       
  arch: amd64
  cpus: 4                     
  hostname: ohuska.localdomain
  kernel: 4.20.6-200.fc29.x86_64
  os: linux                                             
  rootless: false
  uptime: 229h 44m 38.92s (Approximately 9.54 days)
insecure registries:      
  registries: []
registries:                                      
  registries:                                          
  - docker.io 
  - registry.fedoraproject.org
  - quay.io                     
  - registry.access.redhat.com
  - registry.centos.org    
store:       
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:        
    number: 4                                                                                                                 
  GraphDriverName: overlay
  GraphOptions:    
  - overlay.mountopt=nodev               
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:          
    number: 4
  RunRoot: /var/run/containers/storage                
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
