### ISSUE TITLE
lchown error on podman pull 

### ISSUE THREAD

**Issue by KamiQuasi** [containers/libpod#2542]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
After logging in to our locally hosted repository and attempting to `podman pull` our latest image I received a couple of errors (one related to transport that was fixed by adding the `docker://` to the call) the error below is still present (contact me for URL to image):

```
ERRO[0011] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: lchown /var/www/drupal/web/config/active: invalid argument 
Failed
(0x183b040,0xc00052b600)
```

**Steps to reproduce the issue:**

1. `podman login -p {SECRET KEY} -u unused {IMAGE REPO}`

2. `podman pull docker://{IMAGE REPO}`

3. Error

**Describe the results you received:**
Error instead of an image

**Describe the results you expected:**
Image to be used

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.2.0-dev
```

**Output of `podman info --debug`:**

```
  MemFree: 511528960
  MemTotal: 5195935744
  OCIRuntime:
    package: Unknown
    path: /usr/local/sbin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: f79e211b1d5763d25fb8debda70a764ca86a0f23
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: penguin
  kernel: 4.19.4-02480-gd44d301822f0
  os: linux
  rootless: true
  uptime: 136h 10m 42.4s (Approximately 5.67 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - {IMAGE REPO}
store:
  ConfigFile: /home/ldary/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/ldary/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000
  VolumePath: /home/ldary/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is a Debian sandbox on a Pixelbook. We found that one error was removed by adding the `docker://` that was also displayed when run without the transport. @vbatts also had me run this command `findmnt -T /home/ldary/.local/share/containers/storage`
Output
```TARGET SOURCE                                                         FSTYPE OPTIONS
/      /dev/vdb[/lxd/storage-pools/default/containers/penguin/rootfs] btrfs  rw,relatime,discard,space_cache,user_subvol_rm_allowed,subvolid=266,subvol=/lxd/storage-pools/default/containers/penguin/rootfs```
