### ISSUE TITLE
support File -type hostPath in podman play kube

### ISSUE THREAD

**Issue by ikke-t** [containers/libpod#2922]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

As container user, I want to mount config files from host to containers. As of now, podman only supports hostPath type Directory only. It's very normal way to map config files into container, that's what [kubernetes does](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath)

**Steps to reproduce the issue:**

1. create a host path config file:
```echo foobar > /tmp/foobar.txt```

2. create foobar.yml
```
cat >>/tmp/foobar.yml<<EOF 
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: foobar
  name: foobar
spec:
  volumes:
  - name: foobar
    hostPath:
      path: /tmp/foobar
      type: File
  containers:
  - command:
    - /usr/bin/sleep 10000
    image: fedora
    name: fedora
    volumeMounts:
    - mountPath: /etc/foobar
      name: foobar
EOF
```

3. run podman
```
sudo podman play kube /tmp/foobar.yml 
```

**Describe the results you received:**

```
$ sudo podman play kube /tmp/foobar.yml 
e37c0beed3cbb384af281c87c522722ee52e05ec4f801eff2f0aa470b7dcf2e8
Error: Directories are the only supported HostPath type
```

**Describe the results you expected:**

pod started, mounting config file into container.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is missing feature, happens always.

**Output of `podman version`:**
latest nightly
```
Version:            1.3.0-dev
RemoteAPI Version:  1
Go Version:         go1.12.2
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.2
  podman version: 1.3.0-dev
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: podman-1.3.0-12.dev.git1572367.fc31.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 0b1ee7659f4424ceb261263ecdf8d9f5f1375c6f'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 5381058560
  MemTotal: 8363380736
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  hostname: ikke-fedora
  kernel: 4.18.16-300.fc29.x86_64
  os: linux
  rootless: false
  uptime: 1h 8m 56.4s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 6
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 29 on Lenovo Carbon X1
