### ISSUE TITLE
podman kube play does not use default environment variables

### ISSUE THREAD

**Issue by Fodoj** [containers/libpod#2930]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am using postgres image from Docker Library. If I run it just with `podman run`, without specifying any extra environment variables, it works fine - it picks default values for things like `PGDATA`, `PATH` etc.

But if I use pod.yaml and `podman play kube`, it doesn't use any default values and forces me to specify every environment variable in my pod.yaml, like this:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mkdev-dev
  name: mkdev-dev
spec:
  containers:
  - command:
    - docker-entrypoint.sh
    - postgres
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/9.6/bin
    - name: PG_VERSION
      value: 9.6.9-2.pgdg90+1
    - name: PGDATA
      value: /var/lib/postgresql/data
    - name: POSTGRES_PASSWORD
      value: secrets
    - name: GOSU_VERSION
      value: "1.10"
    - name: LANG
      value: en_US.utf8
    - name: PG_MAJOR
      value: "9.6"
    image: docker.io/library/postgres:9.6.9
    ports:
      - hostPort: 5432
        containerPort: 5432
        protocol: tcp
    name: postgres
    workingDir: /
```

`podman generate kube` outputs yaml with all possible environment variables that are needed, but it still would be nice not to specify all the internals like PATH etc directly, as I probably should not be concerned with internals of the image that much.

**Steps to reproduce the issue:**

1. `podman kube play pod.yaml` with the above yaml, but without PGDATA or PATH

**Describe the results you received:**

Container fails to start, as PGDATA variable is missing

**Describe the results you expected:**

Container starts with default PGDATA

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.2.0
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: podman-1.2.0-2.git3bd528e.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: d88bb0e63cb70f9787a8e410716924f380af361f'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 4914077696
  MemTotal: 25005699072
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 12574519296
  SwapTotal: 12574519296
  arch: amd64
  cpus: 8
  hostname: linux.fritz.box
  kernel: 5.0.4-200.fc29.x86_64
  os: linux
  rootless: false
  uptime: 360h 40m 8.78s (Approximately 15.00 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 4
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
Linux linux.fritz.box 5.0.4-200.fc29.x86_64 #1 SMP Mon Mar 25 02:27:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
