### ISSUE TITLE
[podman-remote] attach: --detach-key does not work

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#3008]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
As the title described when I set the option `--detach-key="ctrl-["` on the remote node, the key `ctrl-[` does not work, but `ctrl-p,ctrl-q` works.

On the podman node, `--detach-key` works perfectly with the newly defined key.

**Comment by Edward5hen** [comment]
Details on remote node:
```
# podman info
host:
  BuildahVersion: 1.8-dev
  Conmon:
    package: conmon-1.10.3-1.gite558bd5.fc27.x86_64
    path: /usr/libexec/crio/conmon
    version: 'conmon version 1.10.3, commit: 27d18947e07ae525daacba333e67a98a6296fc5d'
  Distribution:
    distribution: fedora
    version: "27"
  MemFree: 147574784
  MemTotal: 11980427264
  OCIRuntime:
    package: runc-1.0.0-36.gitad0f525.fc27.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc5+dev
      spec: 1.0.0
  SwapFree: 1245184
  SwapTotal: 6043987968
  arch: amd64
  cpus: 4
  hostname: dhcp-2-7.nay.redhat.com
  kernel: 4.18.7-100.fc27.x86_64
  os: linux
  rootless: false
  uptime: 260h 45m 30.17s (Approximately 10.83 days)
insecure registries:
  registries:
  - brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 15
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```
