### ISSUE TITLE
[podman-remote] attach --no-stdin: Error: invalid argument 

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#3009]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When I tried `attach --no-stdin` on the remote node, error message `Error: invalid argument` is printed in the output. I don't know if remote client is going to support this option, if it is, we probably need to write in the doc that remote client not support it, if it is not, there should be something like `Error: unknown flag: --no-stdin` is printed out.

**Comment by Edward5hen** [comment]
Details on remote node:
```
# podman info
host:
  BuildahVersion: 1.8-dev
  Conmon:
    package: conmon-1.10.3-1.gite558bd5.fc27.x86_64
    path: /usr/libexec/crio/conmon
    version: 'conmon version 1.10.3, commit: 27d18947e07ae525daacba333e67a98a6296fc5d'
  Distribution:
    distribution: fedora
    version: "27"
  MemFree: 147574784
  MemTotal: 11980427264
  OCIRuntime:
    package: runc-1.0.0-36.gitad0f525.fc27.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc5+dev
      spec: 1.0.0
  SwapFree: 1245184
  SwapTotal: 6043987968
  arch: amd64
  cpus: 4
  hostname: dhcp-2-7.nay.redhat.com
  kernel: 4.18.7-100.fc27.x86_64
  os: linux
  rootless: false
  uptime: 260h 45m 30.17s (Approximately 10.83 days)
insecure registries:
  registries:
  - brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 15
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```
