### ISSUE TITLE
[podman-remote] start a running container: nothing happened and exit code is 0

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#3011]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
From the podman documentation:
>  If you attempt to start a running container with the --attach option, podman will simply attach to the container.

But for podman-remote, it just does nothing with exit code 0.

**Steps to reproduce the issue:**

1. `podman run --name test-start -it busybox`

3. on remote node: `PODMAN_VARLINK_ADDRESS="tcp:127.0.0.1:1234" bin/podman-remote start -a -i test-start`

**Describe the results you received:**
User cannot enter into the interactive mode with anything printed out.
And the exit code is `0`.

varlink error log:
```
# podman varlink -t 0 --log-level=debug unix:/run/podman/io.podman
ERRO[7152] container 3c5421321859cc14a6c80b817e1f8f77f46afde4c2a2ec473a3cabef9bb8ffad must be in Created or Stopped state to be started: container state improper
```

**Describe the results you expected:**
should get into the interactive mode as `attach` does

**Comment by baude** [comment]
details on your client? version, etc?

**Comment by Edward5hen** [comment]
```
# podman info
host:
  BuildahVersion: 1.8-dev
  Conmon:
    package: conmon-1.10.3-1.gite558bd5.fc27.x86_64
    path: /usr/libexec/crio/conmon
    version: 'conmon version 1.10.3, commit: 27d18947e07ae525daacba333e67a98a6296fc5d'
  Distribution:
    distribution: fedora
    version: "27"
  MemFree: 147574784
  MemTotal: 11980427264
  OCIRuntime:
    package: runc-1.0.0-36.gitad0f525.fc27.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc5+dev
      spec: 1.0.0
  SwapFree: 1245184
  SwapTotal: 6043987968
  arch: amd64
  cpus: 4
  hostname: dhcp-2-7.nay.redhat.com
  kernel: 4.18.7-100.fc27.x86_64
  os: linux
  rootless: false
  uptime: 260h 45m 30.17s (Approximately 10.83 days)
insecure registries:
  registries:
  - brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 15
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```
