### ISSUE TITLE
Relative volume path in Kube yaml is not resolved

### ISSUE THREAD

**Issue by Fodoj** [containers/libpod#3029]
For example:

```
  volumes:
    - name: app
      hostPath:
        path: ./
        type: Directory
```

Will result in volume simply ignored. Podman 1.3.0-dev, Fedora Workstation 29.
