### ISSUE TITLE
podman pull sagemathinc/cocalc results in an infinite extraction of files

### ISSUE THREAD

**Issue by ismail** [containers/libpod#3269]
How to reproduce (I already downloaded the layers so ignore the "already exists"):

havana ~ > podman pull sagemathinc/cocalc
Trying to pull docker.io/sagemathinc/cocalc...Getting image source signatures
Copying blob b8af9ea7344d skipped: already exists
Copying blob 0330ca45a200 skipped: already exists
Copying blob 471db38bcfbf skipped: already exists
Copying blob 0b4aba487617 skipped: already exists
Copying blob 1e1de00ff7e1 skipped: already exists
Copying blob a48c500ed24e skipped: already exists
Copying blob c1b188dceb4d skipped: already exists
Copying blob b80efb96a0c2 skipped: already exists
Copying blob 205ec64818b3 skipped: already exists
Copying blob 908cccd6a316 skipped: already exists
Copying blob 16355516d8d4 skipped: already exists
Copying blob 0d02f1ba446f skipped: already exists
Copying blob a057177ba989 skipped: already exists
Copying blob 7128cf979cf2 skipped: already exists
Copying blob 7be20c544016 skipped: already exists
Copying blob d2d09f29916d skipped: already exists
Copying blob 4e92e4815796 skipped: already exists
Copying blob 1bb177e90777 skipped: already exists
Copying blob a8513f79354d skipped: already exists
Copying blob f66a8c75a314 skipped: already exists
Copying blob 8690bcb05279 skipped: already exists
Copying blob 5c07ee3d95a6 skipped: already exists
Copying blob b2ace573ab04 skipped: already exists
Copying blob ccfb8c20f5d8 skipped: already exists
Copying blob d2d5c34b4808 skipped: already exists
Copying blob c6c6a1137661 skipped: already exists
Copying blob 5e03e45f0ad6 skipped: already exists
Copying blob 43a7a50c9712 skipped: already exists
Copying blob 9d550beb7e16 skipped: already exists
Copying blob b036373d01fb skipped: already exists
Copying blob ee237b808eaa skipped: already exists
Copying blob 2f50e949884a skipped: already exists
Copying blob 322bd1f0e346 skipped: already exists
Copying blob 5928140f7751 skipped: already exists
Copying blob 57b89884b772 skipped: already exists
Copying blob 1de7c29cf7f1 skipped: already exists
Copying blob dc8bdbd848df skipped: already exists
Copying blob 51321bc300fb skipped: already exists
Copying blob c0474d584183 skipped: already exists
Copying blob acf6a6aab854 skipped: already exists
Copying blob eaab119b7358 skipped: already exists
Copying blob da355f996ae5 skipped: already exists
Copying blob 2190488b7f54 skipped: already exists
Copying blob dce0b5b6ee7f done
Copying config dbd2e2ecff done
Writing manifest to image destination
Storing signatures

Now at this point watch ~/.local/share/containers/storage/vfs/dir growing bigger and bigger. I let it run for hours and stopped around 300GB.

havana ~ > podman --version
podman version 1.3.1

This is tested on openSUSE Tumbleweed as of version 20190604.

**Comment by rhatdan** [comment]
Most likely issue here is you are using vfs rather then fuse-overlayfs.

yum install fuse-overlayfs
rm -rf ~/.local/share/container ~/.config/containers

And try 
podman info

Does it show overlay driver?  If yes, try your experiment again.

**Comment by ismail** [comment]
```
havana ~ > podman info
host:
  BuildahVersion: 1.8.2
  Conmon:
    package: podman-1.3.1-1.2.x86_64
    path: /usr/lib/podman/bin/conmon
    version: 'conmon version 0.2.0, commit: '
  Distribution:
    distribution: '"opensuse-tumbleweed"'
    version: "20190604"
  MemFree: 8500428800
  MemTotal: 16734777344
  OCIRuntime:
    package: runc-1.0.0~rc8-1.2.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8
      spec: 1.0.1-dev
  SwapFree: 15871246336
  SwapTotal: 16726884352
  arch: amd64
  cpus: 8
  hostname: havana
  kernel: 5.1.5-1-default
  os: linux
  rootless: true
  uptime: 26h 36m 25.93s (Approximately 1.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /suse/idoenmez/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /suse/idoenmez/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/16908
  VolumePath: /suse/idoenmez/.local/share/containers/storage/volumes
```

fuse-overlayfs doesn't seem to be available in openSUSE. But, even with vfs this can't be the expected behaviour.
