### ISSUE TITLE
podman version 1.4.1 errors when starting containers - "run failed after [conmon:e]: No such log driver json-file"

### ISSUE THREAD

**Issue by rlandy** [containers/libpod#3363]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Using podman version 1.4.1 on RHEL 8 (updated) we see the following error when starting containers:

ERROR: 27947 -- ['/usr/bin/podman', 'start', '-a', 'container-puppet-glance_api'] run failed after [conmon:e]: No such log driver json-file",
"Error: unable to start container <container ID>: write child: broken pipe",
...
ERROR: 27949 -- ['/usr/bin/podman', 'start', '-a', 'container-puppet-iscsid'] run failed after [conmon:e]: No such log driver json-file"
Repeated for all containers.

**Steps to reproduce the issue:**

1. Install podman version 1.4.1 on RHEL 8 with updated rpms

2. Run containers 

3. See driver error

**Describe the results you received:**

The following errors on every attempt to run/start containers:

WARNING: 27947 -- Retrying running container: glance_api",
 ERROR: 27946 -- ['/usr/bin/podman', 'start', '-a', 'container-puppet-crond'] run failed after [conmon:e]: No such log driver json-file",
  "Error: unable to start container <container ID>: write child: broken pipe",
2019-06-18 14:59:02 |         " attempt(s): 2",

**Describe the results you expected:**

No errors when starting containers.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.1
RemoteAPI Version:  1
Go Version:         go1.12.6
OS/Arch:            linux/amd64
```

```
+ podman info
host:
  BuildahVersion: 1.8.4
  Conmon:
    package: podman-1.4.1-2.module+el8.1.0+3401+5fb5c576.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "8.0"
  MemFree: 326901760
  MemTotal: 8191172608
  OCIRuntime:
    package: runc-1.0.0-57.rc5.dev.git2abd837.module+el8.1.0+3394+8ce796a4.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8579956736
  SwapTotal: 8589930496
  arch: amd64
  cpus: 8
  hostname: standalone.localdomain
  kernel: 4.18.0-80.el8.x86_64
  os: linux
  rootless: false
  uptime: 1h 19m 7.14s (Approximately 0.04 days)
registries:
  blocked: null
  insecure:
  - 192.168.24.1
  search:
  - registry.redhat.io
  - quay.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 48
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 60
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```
