### ISSUE TITLE
Error: could not get runtime: operation not permitted with stable podman image

### ISSUE THREAD

**Issue by orf** [containers/libpod#3464]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Using the `quay.io/podman/stable` image on MacOS or Kubernetes results in `Error: could not get runtime: operation not permitted`

**Steps to reproduce the issue:**

1. Run `docker run -it quay.io/podman/stable podman info`

**Describe the results you received:**

`Error: could not get runtime: operation not permitted`

**Describe the results you expected:**

It to work 

**Additional information you deem important (e.g. issue happens only occasionally):**

It appears to be an issue with the fuse vfs. If I do `docker run -it quay.io/podman/stable bash`, then execute:

```
rm -rf /var/lib/shared/overlay-images && rm -rf /var/lib/shared/overlay-layers
rm -rf /var/lib/shared/overlay-images/images.lock /var/lib/shared/overlay-layers/layers.lock
rm -f /etc/containers/storage.conf
```

Then `podman` no longer exits with the error.

**Output of `podman version`:**

```
Version:            1.4.2
RemoteAPI Version:  1
Go Version:         go1.12.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$docker run -it quay.io/podman/stable podman --log-level=debug info                                                   
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /var/lib/containers/storage
DEBU[0000] Using run root /var/run/containers/storage
DEBU[0000] Using static dir /var/lib/containers/storage/libpod
DEBU[0000] Using tmp dir /var/run/libpod
DEBU[0000] Using volume path /var/lib/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: imagestore=/var/lib/shared
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs
ERRO[0000] could not get runtime: operation not permitted
```

**Comment by mheon** [comment]
This is a pretty terrible error, regardless of where it's coming from - we need to get this wrapped so we can present a more reasonable explanation as to where it's coming from

**Comment by TomSweeneyRedHat** [comment]
FYI @giuseppe

**Comment by giuseppe** [comment]
we don't have really anything in place in Podman for creating a user namespace when root has limited capabilities.
Creating the user namespace won't be difficult, but we need to ensure we will still refer to the correct config files.  Differently from Buildah, we will need to ensure all containers are created from the same user namespace, so we need a pause process for root as well.

I'd suggest just to use vfs for now, @rhatdan what do you think?

**Comment by rhatdan** [comment]
Yes, I am not really sure of the use case of running podman in a locked down container anyways.
Seems to me the container should be privileged if you are running it to easily launch containers or demonstrate the features of podman.

**Comment by orf** [comment]
What about a simple case where you want to push and pull an image, or do any number of things that doesn't involve running a container? Podman is pretty great in this regard.

**Comment by rhatdan** [comment]
Ok, but skopeo would also be good in that category,   perhaps better.

**Comment by imcsk8** [comment]
Is this a valid use case?

**Comment by orf** [comment]
True, Skopeo is a better use case for re-tagging and pushing, you're right.

In any case, it's quite a confusing error that's not great right off the bat. If you cannot really support podman running in a locked down container it should error with a slightly more informative message!

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL at this, should work.  Does this work if podman is used to launch command?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan I'm not 100% sure what you mean by "podman is used to launch command".  If I use an installed version of Podman, then `podman info` as a root or non-root user works just fine.  If I add `--privileged` to the command in this issue, then I see the output as expected from info, but I do get a soft error that I didn't expect.

```
# podman run --privileged -it quay.io/podman/stable sudo podman info
ERRO[0000] unable to write system event: "write unixgram @00048->/run/systemd/journal/socket: sendmsg: no such file or directory" 
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.0.0-dev, commit: 164df8af4e62dc759c312eab4b97ea9fb6b5f1fc'
  Distribution:
    distribution: fedora
    version: "30"
...  {removed rest of the happy output for brevity}
```

I'm not sure what's up with the system event, that's a new one to me.  I think we still need to keep the `--privileged` flag in play though.
