### ISSUE TITLE
Add rootless support for General Parallel File Systems (GPFS)

### ISSUE THREAD

**Issue by jwflory** [containers/libpod#3478]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Podman is unable to pull images as a rootless user. When I try to pull images, while storing signatures, Podman attempts to open `/root/.bash_logout`, which the rootless user expectedly does not have access to.

In my case, I am using the VFS storage driver as well, although this is intended as short-term.

**Steps to reproduce the issue:**

1. `podman pull docker.io/fedora:latest`

**Describe the results you received:**

```sh
[jwflory@compute0011 ~]$ podman pull docker.io/fedora:latest
Trying to pull docker.io/fedora:latest...Getting image source signatures
Copying blob 8f6ac7ed4a91 done
Copying config 289289d1a1 done
Writing manifest to image destination
Storing signatures
ERRO[0006] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: open /root/.bash_logout: permission denied 
ERRO[0007] Error pulling image ref //fedora:latest: Error committing the finished image: error adding layer with blob "sha256:8f6ac7ed4a91c9630083524efcef2f59f27404320bfee44397f544c252ad4bd4": ApplyLayer exit status 1 stdout:  stderr: open /root/.bash_logout: permission denied 
Failed
Error: error pulling image "docker.io/fedora:latest": unable to pull docker.io/fedora:latest: unable to pull image: Error committing the finished image: error adding layer with blob "sha256:8f6ac7ed4a91c9630083524efcef2f59f27404320bfee44397f544c252ad4bd4": ApplyLayer exit status 1 stdout:  stderr: open /root/.bash_logout: permission denied
```

**Describe the results you expected:**

```sh
[jwflory@compute0011 ~]$ podman pull docker.io/fedora:latest
Trying to pull docker.io/fedora:latest...Getting image source signatures
Copying blob 8f6ac7ed4a91 done
Copying config 289289d1a1 done
Writing manifest to image destination
Storing signatures
# sha256sum hash
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a self-compiled and built version of Podman 1.4.2 for RHEL 7.5. It does use the newer shadow-utils-newxidmap and slirp4netfs packages however. This could be a local issue, but it would be helpful to know in advance while preparing for a future RHEL 7.7.

**Output of `podman version`:**

```yaml
Version:            1.4.2
RemoteAPI Version:  1
Go Version:         go1.12.6
Git Commit:         9b6a98cfd7813513e5697888baa93318395a2055
Built:              Fri Jun 28 13:46:14 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```yaml
debug:
  compiler: gc
  git commit: 9b6a98cfd7813513e5697888baa93318395a2055
  go version: go1.12.6
  podman version: 1.4.2
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: cri-o-1.14.4-8521.x86_64
    path: /usr/libexec/crio/conmon
    version: ""
  Distribution:
    distribution: '"rhel"'
    version: "7.5"
  MemFree: 414194458624
  MemTotal: 540603346944
  OCIRuntime:
    package: runc-1.0.0-59.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 27
  hostname: compute0011
  kernel: 3.10.0-862.3.2.el7.jump1.x86_64
  os: linux
  rootless: true
  uptime: 172h 29m 19.02s (Approximately 7.17 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - quay.io
  - registry.access.redhat.com
store:
  ConfigFile: /home/jfloryintern/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /physical/gpfs/home/home01/data_files/jfloryintern/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/43228
  VolumePath: /physical/gpfs/home/home01/data_files/jfloryintern/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical node.
