### ISSUE TITLE
Run rootless containers on SSSD system == "cannot specify gid= mount options for unmapped gid"

### ISSUE THREAD

**Issue by jwflory** [containers/libpod#3541]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am unable to run a rootless container on a RHEL 7.5 workstation using SSSD for authentication. This happens when I run any container on my workstation. Namespace mappings exist for my login name in `/etc/subuid` and `/etc/subgid`.

This is similar to #1147.

**Steps to reproduce the issue:**

1. `podman pull registry.fedoraproject.org/fedora:latest`
2. `podman run --rm -it registry.fedoraproject.org/fedora bash`

**Describe the results you received:**

```sh
$ podman --log-level=debug run --rm -it registry.fedoraproject.org/fedora bash
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/jfloryintern/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /home/jfloryintern/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/43228               
DEBU[0000] Using static dir /home/jfloryintern/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/43228/libpod/tmp     
DEBU[0000] Using volume path /home/jfloryintern/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "vfs"   
DEBU[0000] Initializing event backend journald          
DEBU[0000] parsed reference into "[vfs@/home/jfloryintern/.local/share/containers/storage+/run/user/43228]registry.fedoraproject.org/fedora:latest" 
DEBU[0000] parsed reference into "[vfs@/home/jfloryintern/.local/share/containers/storage+/run/user/43228]@47c865867d25e2a8bb593e329d73a7109164b37140848ffa6105a8a40b05555f" 
DEBU[0000] exporting opaque data as blob "sha256:47c865867d25e2a8bb593e329d73a7109164b37140848ffa6105a8a40b05555f" 
DEBU[0000] parsed reference into "[vfs@/home/jfloryintern/.local/share/containers/storage+/run/user/43228]@47c865867d25e2a8bb593e329d73a7109164b37140848ffa6105a8a40b05555f" 
DEBU[0000] exporting opaque data as blob "sha256:47c865867d25e2a8bb593e329d73a7109164b37140848ffa6105a8a40b05555f" 
DEBU[0000] parsed reference into "[vfs@/home/jfloryintern/.local/share/containers/storage+/run/user/43228]@47c865867d25e2a8bb593e329d73a7109164b37140848ffa6105a8a40b05555f" 
DEBU[0000] Got mounts: []                               
DEBU[0000] Got volumes: []                              
DEBU[0000] Using slirp4netns netmode                    
DEBU[0000] created OCI spec and options for new container 
DEBU[0000] Allocated lock 0 for container e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2 
DEBU[0000] parsed reference into "[vfs@/home/jfloryintern/.local/share/containers/storage+/run/user/43228]@47c865867d25e2a8bb593e329d73a7109164b37140848ffa6105a8a40b05555f" 
DEBU[0000] exporting opaque data as blob "sha256:47c865867d25e2a8bb593e329d73a7109164b37140848ffa6105a8a40b05555f" 
DEBU[0001] created container "e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2" 
DEBU[0001] container "e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2" has work directory "/home/jfloryintern/.local/share/containers/storage/vfs-containers/e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2/userdata" 
DEBU[0001] container "e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2" has run directory "/run/user/43228/vfs-containers/e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2/userdata" 
DEBU[0001] New container created "e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2" 
DEBU[0001] container "e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2" has CgroupParent "/libpod_parent/libpod-e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2" 
DEBU[0001] Handling terminal attach                     
DEBU[0001] mounted container "e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2" at "/home/jfloryintern/.local/share/containers/storage/vfs/dir/29705b2a5fb7e970bd8e19f4b36a28f8614822c4e34a02da4341154d52fa7be8" 
DEBU[0001] Created root filesystem for container e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2 at /home/jfloryintern/.local/share/containers/storage/vfs/dir/29705b2a5fb7e970bd8e19f4b36a28f8614822c4e34a02da4341154d52fa7be8 
DEBU[0001] /etc/system-fips does not exist on host, not mounting FIPS mode secret 
DEBU[0001] Created OCI spec for container e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2 at /home/jfloryintern/.local/share/containers/storage/vfs-containers/e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2/userdata/config.json 
DEBU[0001] /usr/libexec/crio/conmon messages will be logged to syslog 
DEBU[0001] running conmon: /usr/libexec/crio/conmon      args="[-c e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2 -u e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2 -n goofy_gagarin -r /usr/bin/runc -b /home/jfloryintern/.local/share/containers/storage/vfs-containers/e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2/userdata -p /run/user/43228/vfs-containers/e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2/userdata/pidfile --exit-dir /run/user/43228/libpod/tmp/exits --conmon-pidfile /run/user/43228/vfs-containers/e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/jfloryintern/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/43228 --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /run/user/43228/libpod/tmp --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg vfs --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --rm --exit-command-arg e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2 --socket-dir-path /run/user/43228/libpod/tmp/socket -t -l k8s-file:/home/jfloryintern/.local/share/containers/storage/vfs-containers/e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2/userdata/ctr.log --log-level debug --syslog]"
WARN[0001] Failed to add conmon to cgroupfs sandbox cgroup: error creating cgroup for cpu: mkdir /sys/fs/cgroup/cpu/libpod_parent: permission denied 
DEBU[0001] Received container pid: -1                   
DEBU[0001] Cleaning up container e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2 
DEBU[0001] Network is already cleaned up, skipping...   
DEBU[0001] unmounted container "e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2" 
DEBU[0001] Cleaning up container e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2 
DEBU[0001] Network is already cleaned up, skipping...   
DEBU[0001] Container e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2 storage is already unmounted, skipping... 
DEBU[0001] Container e9c9760c99063f56f69a3306451ac856b1fbb119fcccbdbadb26af4f91743ac2 storage is already unmounted, skipping... 
ERRO[0001] cannot specify gid= mount options for unmapped gid in rootless containers
: OCI runtime error
```

**Describe the results you expected:**

```sh
$ podman run --rm -it registry.fedoraproject.org/fedora bash
[root@000000000 /]#
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```sh
podman version 1.4.4
```

**Output of `podman info --debug`:**

```yaml
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: cri-o-1.15.0-8640.x86_64
    path: /usr/libexec/crio/conmon
    version: 'conmon version 1.15.0, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "7.5"
  MemFree: 842784768
  MemTotal: 7925895168
  OCIRuntime:
    package: runc-1.0.0-59.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 2034233344
  SwapTotal: 2147479552
  arch: amd64
  cpus: 8
  hostname: chiin-jfl1
  kernel: 3.10.0-862.3.2.el7.jump1.x86_64
  os: linux
  rootless: true
  uptime: 143h 48m 4.09s (Approximately 5.96 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - quay.io
  - registry.access.redhat.com
store:
  ConfigFile: /home/jfloryintern/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/jfloryintern/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /run/user/43228
  VolumePath: /home/jfloryintern/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical workstation, no virtualization used. Also using updated `newxidmap` COPR package from `shadow-utils`.
