### ISSUE TITLE
podman ps --filter doesn't work like docker's

### ISSUE THREAD

**Issue by cjeanner** [containers/libpod#3596]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The ```docker ps --filter``` allows to pass a "OR" string in the form of "name=foo|bar". Apparently, ```podman ps --filter``` doesn't work like this.

**Steps to reproduce the issue:**

1. run three containers, one named "bar", one named "foo" and the last one "blah"

2. try to list them using ```podman ps -aq --filter "name=bar|foo"```

3.

**Describe the results you received:**
It doesn't show any container.

**Describe the results you expected:**
It should show two containers, "foo" and "bar", for instance:
```
docker ps -aq --filter "name=foo|bar"
247a990999d5
4d019ac351b0
```
**Additional information you deem important (e.g. issue happens only occasionally):**
Always happening

**Output of `podman version`:**

```
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.10.2
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-1.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: da19d4db03f799783380e6a056cfc6b2bf7f0e18'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 335626240
  MemTotal: 15870173184
  OCIRuntime:
    package: runc-1.0.0-60.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 4294168576
  SwapTotal: 4294963200
  arch: amd64
  cpus: 12
  hostname: overcloud-0-controller-0
  kernel: 3.10.0-957.21.3.el7.x86_64
  os: linux
  rootless: false
  uptime: 6h 35m 40.32s (Approximately 0.25 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 79
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 31
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```
