### ISSUE TITLE
False error message if using non-default runroot and default runroot is not writable

### ISSUE THREAD

**Issue by jwflory** [containers/libpod#3712]
/kind bug

**Description**

In my environment, the default `runroot` path of `/run/user/$UID/` is not writable. Instead, I use a custom `runroot` in my `storage.conf` to work around this. However, even when it is changed, Podman reports a fatal error in the console, although it does correctly fall back to the custom `runroot`.

It would be nice to make the false error message wait to write to stderr until the custom `runroot` is tried.

**Steps to reproduce the issue:**

1. `podman run --rm -it rhel7:7.5 bash`
2. `[user@host $] `

**Describe the results you received:**

`ERRO[0000] unable to make temp dir /run/user/43228`

**Describe the results you expected:**

No output.

**Additional information you deem important (e.g. issue happens only occasionally):**

From a `strace`:

```sh
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=83717, si_uid=43228, si_status=1, si_utime=0, si_stime=0} ---
newfstatat(AT_FDCWD, "/run/user/43228", 0xc000256ed8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/run/user", {st_mode=S_IFDIR|0755, st_size=40, ...}, 0) = 0
mkdirat(AT_FDCWD, "/run/user/43228", 0700) = -1 EACCES (Permission denied)
newfstatat(AT_FDCWD, "/run/user/43228", 0xc000257078, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
ERRO[0000] unable to make temp dir /run/user/43228      
newfstatat(AT_FDCWD, "/run/user/43228", 0xc000257148, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/local_scratch/sata/52.1.all.q/run-43228", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/local_scratch/sata/52.1.all.q/run-43228", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/local_scratch/sata/52.1.all.q/run-43228/libpod/pause.pid", {st_mode=S_IFREG|0600, st_size=5, ...}, 0) = 0
openat(AT_FDCWD, "/local_scratch/sata/52.1.all.q/run-43228/libpod/pause.pid", O_RDONLY|O_CLOEXEC) = 6
```

**Output of `podman version`:**

```yaml
ERRO[0000] unable to make temp dir /run/user/43228      
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```yaml
ERRO[0000] unable to make temp dir /run/user/43228      
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.4.5-dev
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: conmon-0.3.0-8715.x86_64
    path: /usr/local/bin/conmon
    version: 'conmon version 0.3.0, commit: 8455ce1ef385120deb827d0f0588c04357bad4c4'
  Distribution:
    distribution: '"rhel"'
    version: "7.5"
  MemFree: 130202681344
  MemTotal: 270171582464
  OCIRuntime:
    package: runc-1.0.0_rc8-8715.x86_64
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc8
      commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  hostname: compute2115
  kernel: 3.10.0-862.3.2.el7.jump1.x86_64
  os: linux
  rootless: true
  uptime: 251h 17m 48.36s (Approximately 10.46 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.access.redhat.com
store:
  ConfigFile: /home/jfloryintern/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /dev/shm/50.1.all.q/container-storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /physical/gpfs/home/home01/data_files/jfloryintern/wkspc/podman-run
  VolumePath: /tmp/jflory-libpod/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

HPC compute node with Univa GridEngine. Physical infrastructure.
