### ISSUE TITLE
china can't use it

### ISSUE THREAD

**Issue by willzhang** [containers/libpod#3735]
How to config registry-mirrors like docker,otherwise ,china can't use it pull image,Because of the Great Wall Firewall

```
[root@ssr-2 ~]# cat /etc/docker/daemon.json 
{
  "registry-mirrors": ["https://uyah70su.mirror.aliyuncs.com"]
}
```

**Comment by vrothberg** [comment]
Hi @willzhang, thanks for reaching out. Starting with podman v1.4.0, you can configure the `/etc/containers/registries.conf` as described in the man pages (see https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md).

In this specific case, you need to set `/etc/containers/registries.conf` (assuming you want to mirror docker.io) as follows:
```toml
unqualified-search-registries = ["docker.io"]

[[registry]]
prefix = "docker.io"
location = "https://uyah70su.mirror.aliyuncs.com"
```
