### ISSUE TITLE
play kube cause panic

### ISSUE THREAD

**Issue by s5unty** [containers/libpod#3956]
```
a container exists with the same name (foo) as the pod in your YAML file; changing pod name to foo_pod
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1339594]

goroutine 1 [running]:
github.com/containers/libpod/pkg/adapter.kubeContainerToCreateConfig(0x19b9d80, 0xc42003e080, 0xc42044c172, 0x3, 0xc42037c7c0, 0x15, 0xc420401240, 0x3, 0x4, 0x0, ...)
	_output/src/github.com/containers/libpod/pkg/adapter/pods.go:688 +0x274
github.com/containers/libpod/pkg/adapter.(*LocalRuntime).PlayKubeYAML(0xc4202dcf40, 0x19b9d80, 0xc42003e080, 0x276fc00, 0x7ffe7116872c, 0x6, 0xc420545cc0, 0x41a97c, 0x276fc20)
	_output/src/github.com/containers/libpod/pkg/adapter/pods.go:585 +0x1809
main.playKubeCmd(0x276fc00, 0x0, 0x0)
	_output/src/github.com/containers/libpod/cmd/podman/play_kube.go:67 +0x10a
main.glob..func72(0x270a6e0, 0xc42046ea20, 0x1, 0x1, 0x0, 0x0)
	_output/src/github.com/containers/libpod/cmd/podman/play_kube.go:25 +0x87
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute(0x270a6e0, 0xc42003a0f0, 0x1, 0x1, 0x270a6e0, 0xc42003a0f0)
	_output/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:826 +0x468
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x270a1e0, 0x6, 0x2791a80, 0xc42003e000)
	_output/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:914 +0x306
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).Execute(0x270a1e0, 0xc42030a210, 0xc4200a6058)
	_output/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:864 +0x2b
main.main()
	_output/src/github.com/containers/libpod/cmd/podman/main.go:148 +0x3e
```

* OK

    ```yml
    apiVersion: v1
    kind: Pod
    metadata:
      name: foo
    spec:
      containers:
      - command: ["/bin/sh", "-c", "echo hello && sleep 300"]
        image: library/alpine:latest
        name: foo
        securityContext:
          capabilities: {}

    ```

* PANIC

    ```yml
    apiVersion: v1
    kind: Pod
    metadata:
      name: foo
    spec:
      containers:
      - command: ["/bin/sh", "-c", "echo hello && sleep 300"]
        image: library/alpine:latest
        name: foo

    ```

* version
    ```
    conmon                                            2.0.0-1~ubuntu16.04~ppa2
    cri-o-runc                                        1.0.0-rc8-1~ubuntu16.04.2~ppa1
    podman                                            1.5.1-1~ubuntu16.04~ppa1
    ```
