### ISSUE TITLE
Podman cannot create (inspect) volume

### ISSUE THREAD

**Issue by Michael-Jurek** [containers/libpod#4534]
/kind bug

When creating volume with podman: **podman volume create vmaas_vmaas-db-data**,
errors appear.

**Steps to reproduce the issue:**

1.  Run **podman volume create vmaas_vmaas-db-data**
```OUTPUT
Error: error creating volume directory "/home/mjurek/.local/share/containers/storage/volumes/vmaas_vmaas-db-data/_data": mkdir /home/mjurek/.local/share/containers/storage/volumes/vmaas_vmaas-db-data/_data: file exists

```

2. Delete file **/_data**

3. Run **podman volume create vmaas_vmaas-db-data**
```OUTPUT
Error: error setting selinux label for /home/mjurek/.local/share/containers/storage/volumes/vmaas_vmaas-db-data/_data to "system_u:object_r:container_file_t:s0:c553,c980" as shared: operation not supported

```

When creating volume with podman, it should use (delete and create) existing volume and not pop error, that file exists.

When **/_data** deleted, podman can create volume, but can't relabel selinux context. 

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.10
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.2-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: a89d21975ee86e84e0b0e1c0f887687582f4b0e3'
  Distribution:
    distribution: fedora
    version: "30"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 1879089152
  MemTotal: 16424656896
  OCIRuntime:
    name: runc
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev
  SwapFree: 7890964480
  SwapTotal: 8295804928
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: redhat-com
  kernel: 5.3.6-200.fc30.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-4.git19d199a.fc30.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.2
      commit: 19d199a6ca424fcf9516320a327cedad85cf4dfb
  uptime: 602h 29m 39.79s (Approximately 25.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/mjurek/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.5-2.fc30.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.6.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/mjurek/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: ecryptfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 143
  RunRoot: /run/user/1000
  VolumePath: /home/mjurek/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc30.x86_64

```
**Encrypted /home folder with: ecryptfs**

**Project: https://github.com/RedHatInsights/vmaas**

**docker-compose.yml:**
```
version: '3'

services:
  vmaas_database:
    container_name: vmaas-database
    build:
        context: .
        dockerfile: ./database/Dockerfile
    image: vmaas/database:latest
    restart: unless-stopped
    env_file:
      - ./conf/database-connection-admin.env
    ports:
      - 5432:5432
    volumes:
      - vmaas-db-data:/var/lib/pgsql/data

  vmaas_websocket:
    container_name: vmaas-websocket
    build:
        context: .
        dockerfile: ./websocket/Dockerfile
    image: vmaas/websocket:latest
    restart: unless-stopped
    ports:
      - 8082:8082

  vmaas_reposcan:
    container_name: vmaas-reposcan
    build:
        context: .
        dockerfile: ./reposcan/Dockerfile
    image: vmaas/reposcan:latest
    restart: unless-stopped
    env_file:
      - ./conf/database-connection-writer.env
      - ./conf/reposcan.env
    ports:
      - 8081:8081
      - 8730:8730
    volumes:
      - vmaas-reposcan-tmp:/tmp
      - vmaas-dump-data:/data:z
    depends_on:
      - vmaas_websocket
      - vmaas_database

  vmaas_webapp:
    container_name: vmaas-webapp
    build:
        context: .
        dockerfile: ./webapp/Dockerfile
    image: vmaas/webapp:latest
    restart: unless-stopped
    env_file:
      - ./conf/webapp.env
    ports:
      - 8080:8080
    depends_on:
      - vmaas_websocket
      - vmaas_reposcan

    
  vmaas_webapp_utils:
    container_name: vmaas-webapp-utils
    build:
        context: .
        dockerfile: ./webapp_utils/Dockerfile
    image: vmaas/webapp_utils:latest
    restart: unless-stopped
    env_file:
      - ./conf/webapp_utils.env
      - ./conf/database-connection-reader.env
    ports:
      - 8083:8083
    depends_on:
      - vmaas_webapp


  vmaas_prometheus:
    container_name: vmaas-prometheus
    image: prom/prometheus:v2.1.0
    volumes:
      - prometheus-data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    security_opt:
      - label=disable
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - vmaas_reposcan
      - vmaas_webapp
    restart: always

  vmaas_grafana:
    container_name: vmaas-grafana
    image: grafana/grafana:6.2.5
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - vmaas_prometheus
    ports:
      - 3000:3000
    env_file:
      - ./monitoring/grafana/grafana.conf
    user: "104"
    restart: always

volumes:
  vmaas-db-data:
  vmaas-dump-data:
  vmaas-reposcan-tmp:
  prometheus-data:
  grafana-data:
```
