### ISSUE TITLE
Podman on Ubuntu 18.04 fails with seccomp error

### ISSUE THREAD

**Issue by adrianreber** [containers/libpod#4734]
I installed Podman on Ubuntu 18.04 using following link

https://software.opensuse.org//download.html?project=devel%3Akubic%3Alibcontainers%3Astable&package=podman

This gives me podman 1.6.4~1 but starting a container gives me following error:
```
# podman run --name cr -d docker.io/library/alpine /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
Error: loading seccomp profile (/etc/crio/seccomp.json) failed: Seccomp not supported on this platform
```

I have the default kernel that came with the installation: `4.15.0-72-generic`.

I have seen the same error using Podman on a Travis based system.
```
# podman info
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.8, commit: d35534bc4b9bc722bf1ab6f4e828fcaa6bee236a-dirty'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 1491496960
  MemTotal: 2086400000
  OCIRuntime:
    name: runc
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 4294832128
  SwapTotal: 4294832128
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: ubuntu01
  kernel: 4.15.0-72-generic
  os: linux
  rootless: false
  uptime: 7m 22.07s
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```
