### ISSUE TITLE
After installing Podman, it searches for incorrect user in /etc/subuid 

### ISSUE THREAD

**Issue by DOlearczyk** [containers/libpod#4871]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After installing Podman via `apt`, all podman commands print output with following error log at start:
```
ERRO[0000] cannot find mappings for user dariusz.olearczyk: No subuid ranges found for user "dariusz.olearczyk" in /etc/subuid 
```

**Steps to reproduce the issue:**

All I did was basically follow the tutorial, so:

1. `dolearczyk@ktwdarolenb:~$ sudo add-apt-repository ppa:projectatomic/ppa`

2. `dolearczyk@ktwdarolenb:~$ sudo apt update`

3. `dolearczyk@ktwdarolenb:~$ sudo apt install podman`

4. `dolearczyk@ktwdarolenb:~$ podman info`

**Describe the results you received:**

First 3 commands worked without any problems and podman was installed without any problems. The last command printed this out (with 2 errors at start):
```
ERRO[0000] cannot find mappings for user dariusz.olearczyk: No subuid ranges found for user "dariusz.olearczyk" in /etc/subuid 
ERRO[0000] cannot find mappings for user dariusz.olearczyk: No subuid ranges found for user "dariusz.olearczyk" in /etc/subuid 
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  MemFree: 22260338688
  MemTotal: 33482067968
  OCIRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: ktwdarolenb
  kernel: 4.15.0-74-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.2
      commit: unknown
  uptime: 1h 43m 15.41s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /home/dolearczyk/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/dolearczyk/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000
  VolumePath: /home/dolearczyk/.local/share/containers/storage/volumes
```

**Describe the results you expected:**

I expected podman to use my current user `dolearczyk` instead of `dariusz.olearczyk`, which doesn't even exist.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens consistently. Also in `/etc/subuid` I can see my user correctly:
```
dolearczyk:100000:65536
```

**Output of `podman version`:**

```
dolearczyk@ktwdarolenb:~$ podman version
ERRO[0000] cannot find mappings for user dariusz.olearczyk: No subuid ranges found for user "dariusz.olearczyk" in /etc/subuid 
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
dolearczyk@ktwdarolenb:~$ podman info --debug
ERRO[0000] cannot find mappings for user dariusz.olearczyk: No subuid ranges found for user "dariusz.olearczyk" in /etc/subuid 
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  MemFree: 20283412480
  MemTotal: 33482067968
  OCIRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: ktwdarolenb
  kernel: 4.15.0-74-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.2
      commit: unknown
  uptime: 4h 19m 26.41s (Approximately 0.17 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /home/dolearczyk/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/dolearczyk/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000
  VolumePath: /home/dolearczyk/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
dolearczyk@ktwdarolenb:~$ apt list podman
Listing... Done
podman/bionic,now 1.6.2-1~ubuntu18.04~ppa1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Here's lscpu output for additional information:
```
dolearczyk@ktwdarolenb:~$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               142
Model name:          Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Stepping:            10
CPU MHz:             2300.009
CPU max MHz:         4000,0000
CPU min MHz:         400,0000
BogoMIPS:            3984.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            8192K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
```
