### ISSUE TITLE
Podman remote not working with RHCOS on Windows/Hyper-V

### ISSUE THREAD

**Issue by gbraad** [containers/libpod#5440]
Please see: https://github.com/code-ready/crc/issues/1083 and related debugging info in https://github.com/code-ready/crc/issues/961#issuecomment-595661000. We have tried to use `podman-remote` with the RHCOS VM (using CRC) on Windows+Hyper-V but no matter how it is configured it does not work as expected, while the VM works on macOS. Also, targetting a VM running F30 on Hyper-V works.

**Comment by gbraad** [comment]
tested with @baude and got an updated client which looks good:

```
PS C:\Users\gbraad\.crc\bin> $Env:PODMAN_USER = "core"
PS C:\Users\gbraad\.crc\bin> $Env:PODMAN_HOST = "172.28.191.5"
PS C:\Users\gbraad\.crc\bin> $Env:PODMAN_IDENTITY_FILE = "C:\Users\gbraad\.crc\machines\crc\id_rsa"
PS C:\Users\gbraad\.crc\bin> $Env:PODMAN_IGNORE_HOSTS = "1"
PS C:\Users\gbraad\.crc\bin> .\podman-remote-windows.exe --identity-file $env:PODMAN_IDENTITY_FILE --username $env:PODMAN_USER --remote-host $env:PODMAN_HOST info
client:
  Connection: ssh -p 22 -T -i C:\Users\gbraad\.crc\machines\crc\id_rsa -q -o StrictHostKeyChecking=no
    -o UserKnownHostsFile=/dev/null core@172.28.191.5 -- varlink -A 'podman --log-level=debug
    varlink $VARLINK_ADDRESS' bridge
  Connection Type: BridgeConnection
  OS Arch: windows/amd64
  Podman Version: 1.8.1-dev
  RemoteAPI Version: 1
host:
  arch: amd64
  buildah_version: 1.12.0-dev
  cpus: 4
  distribution:
    distribution: '"rhcos"'
    version: "4.3"
  eventlogger: journald
  hostname: crc-jccc5-master-0
  kernel: 4.18.0-147.3.1.el8_1.x86_64
  mem_free: 11740884992
  mem_total: 12289851392
  os: linux
  swap_free: 0
  swap_total: 0
  uptime: 7m 10.28s
registries:
  blocked: null
  insecure: null
  search: null
store:
  containers: 0
  graph_driver_name: overlay
  graph_driver_options: |-
    map[overlay.mount_program:map[Executable:/usr/bin/fuse-overlayfs Package:fuse-overlayfs-0.4.1-1.module+el8.1.0+4081+b29780af.x86_64 Version:fuse-overlayfs: version 0.4.1
    FUSE library version 3.2.1
    using FUSE kernel interface version 7.26]]
  graph_root: /var/home/core/.local/share/containers/storage
  graph_status:
    backing_filesystem: xfs
    native_overlay_diff: "false"
    supports_d_type: "true"
  images: 0
  run_root: /run/user/1000
```
https://github.com/code-ready/crc/issues/1083#issuecomment-598182506
