### ISSUE TITLE
--volume needs explicit container path after podman 1.6.2

### ISSUE THREAD

**Issue by bebosudo** [containers/libpod#5486]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind bug

**Description**

I've been using podman 1.6.2 on CentOS 7, until yesterday I updated it to 1.8.1.
With podman 1.6.2 I was able to "mount"/"bind" a file inside the container by using `-v /etc/hosts`; in 1.8.1 I need to specify also the destination path, like `-v /etc/hosts:/etc/hosts`.
The RPM for both versions on CentOS 7 are available in my copr: [bebosudo/containers](https://copr.fedorainfracloud.org/coprs/bebosudo/containers/)

**Steps to reproduce the issue:**

1. On podman 1.6.2:
```bash
host# podman run -it --rm -v /etc/motd busybox sh
busybox# cat /etc/motd
Hello to the server named `host'!
```

2. Update to 1.8.1:
```bash
host# podman run -it --rm -v /etc/motd busybox sh
busybox# cat /etc/motd
cat: read error: Is a directory
busybox# ls -alh /etc/motd/
total 8K     
drwxr-xr-x    2 root     root        4.0K Mar 12 21:13 .
drwxr-xr-x    1 root     root        4.0K Mar 12 21:13 ..
```

If I explicit the destination path, it now works again:
```bash
host# podman run -it --rm -v /etc/motd:/etc/motd busybox sh
busybox# cat /etc/motd
Hello to the server named `host'!
```

**Describe the results you received:**

Break of retro-compatibility.
Notice that the "new" behaviour is the same of docker 19.03.5.

**Describe the results you expected:**

Maintain compatibility with prior podman versions.
Or at least signal it with a warning like "missing destination directory in volume mount, generating empty directory"?

**Output of `podman version`:**

```
# podman version
Version:            1.8.1
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```yaml
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.1
host:
  BuildahVersion: 1.14.2
  CgroupVersion: v1
  Conmon:
    package: conmon.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.11, commit: 739ee1b3782073fc58faede290804f1a82244e83'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 33432596480
  MemTotal: 134910377984
  OCIRuntime:
    name: runc
    package: containerd.io.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 20
  eventlogger: journald
  hostname: iron
  kernel: 3.10.0-1062.9.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 562h 14m 23.46s (Approximately 23.42 days)
registries:
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 11
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 16
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman.x86_64
# yum info podman
Loaded plugins: copr, fastestmirror
Loading mirror speeds from cached hostfile
 * base: pkg.adfinis-sygroup.ch
 * epel: ftp.arnes.si
 * extras: pkg.adfinis-sygroup.ch
 * updates: pkg.adfinis-sygroup.ch
Installed Packages
Name        : podman
Arch        : x86_64
Version     : 1.8.1
Release     : 1.el7
Size        : 56 M
Repo        : installed
From repo   : copr:copr.fedorainfracloud.org:bebosudo:containers
...
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical node.

PS: unfortunately copr seems to delete old versions of the same build, so I don't have anymore version 1.6.2-3 on my copr; if needed I can rebuild it and provide other info.
