### ISSUE TITLE
Podman remote-client v1.8.0 drops error for build: no such file or directory

### ISSUE THREAD

**Issue by bszeti** [containers/libpod#5510]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman remote-client v1.8.0 drops error for `podman build`:
```
$ podman build --remote-host mylinuxhost --username root --tag mytag .
Error: error reading info about "/var/tmp/buildTarball334075740/var/tmp/buildTarball334075740/Dockerfile": stat /var/tmp/buildTarball334075740/var/tmp/buildTarball334075740/Dockerfile: no such file or directory
```
Probably the directory (/var/tmp/buildTarball334075740) is duplicated in the path where it looks for the uploaded files.

The same command works with Podman remote-client v1.6.1

**Steps to reproduce the issue:**

1. Use podman remote-client v.1.8.0

2. Create a Dockerfile in the current directory with a simple Docker build like:
`FROM registry.redhat.io/ubi8/ubi`

3. Try to use podman build command:
`podman build --remote-host mylinuxhost --username root --tag mytag .`

**Describe the results you received:**
Error: error reading info about "/var/tmp/buildTarball334075740/var/tmp/buildTarball334075740/Dockerfile": stat /var/tmp/buildTarball334075740/var/tmp/buildTarball334075740/Dockerfile: no such file or directory

**Describe the results you expected:**
Successful build. The same command works with remote-client v1.6.1

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
Tried with server v1.8.0 and v1.8.1. 
```
Client:
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
Git Commit:         2ced9094d4728dd09f60a177faa32339a8d0f721
Built:              Mon Feb 10 14:19:38 2020
OS/Arch:            darwin/amd64

Server:
Version:            1.8.1
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
client:
  Connection: unix:/run/podman/io.podman
  Connection Type: DirectConnection
  OS Arch: darwin/amd64
  Podman Version: 1.8.0
  RemoteAPI Version: 1
host:
  arch: amd64
  buildah_version: 1.14.2
  cpus: 1
  distribution:
    distribution: fedora
    version: "31"
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.5.8-200.fc31.x86_64
  mem_free: 200691712
  mem_total: 2077908992
  os: linux
  swap_free: 2147479552
  swap_total: 2147479552
  uptime: 1h 14m 12.3s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  containers: 0
  graph_driver_name: overlay
  graph_driver_options: map[overlay.mountopt:nodev,metacopy=on]
  graph_root: /var/lib/containers/storage
  graph_status:
    backing_filesystem: extfs
    native_overlay_diff: "false"
    supports_d_type: "true"
  images: 9
  run_root: /var/run/containers/storage
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.1-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using Fedora31 in VirtualBox as the Linux host for Podman remote-client.
