### ISSUE TITLE
Docker incompatibility: Podman fails if user's uid/gid is mapped in subuid/subgid

### ISSUE THREAD

**Issue by wardev** [containers/libpod#5751]
/kind bug

**Description**

I would like podman to use all of the uid/gid mappings in subuid/subgid, which Docker currently does. It seems that currently podman only uses the first one.

**Steps to reproduce the issue:**

On Ubuntu 18.04, using podman 1.8.2 installed from kubic repo.

```bash
# setup up multiple mappings for subuid and subgid.
# Note this is what docker needs for root in container to be my user name on the host.
echo "$(id -un):$(id -u):1" | sudo tee -a /etc/subuid /etc/subgid
echo "$(id -un):120000:65536" | sudo tee -a /etc/subuid /etc/subgid
# make sure podman picks up the chages
killall podman
# try to run a container that is not in the local cache
podman run -it centos:7
```
Output from podman:

```
Trying to pull optimus.nrl.navy.mil:50443/centos:7...
Getting image source signatures
Copying blob ab5ef0e58194 done  
Copying config 5e35e350ad done  
Writing manifest to image destination
Storing signatures
ERRO[0009] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 0:54 for /run/lock/lockdev): lchown /run/lock/lockdev: invalid argument 
  ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 0:54 for /run/lock/lockdev): lchown /run/lock/lockdev: invalid argument
Error: unable to pull centos:7: 1 error occurred:
	* Error committing the finished image: error adding layer with blob "sha256:ab5ef0e5819490abe86106fd9f4381123e37a03e80e650be39f7938d30ecb530": ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 0:54 for /run/lock/lockdev): lchown /run/lock/lockdev: invalid argument
```

I expected to container to be run with a user name space that includes 1001,120000-185536. The output of `podman info` indicates it is not picking up all the uid/gid mappings correctly:

```
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
```

After commenting out the line that maps a single uid/gid in subuid/gid podman behaves correctly. It even adds the mapping that was commented out:

```
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 120000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 120000
      size: 65536
```

**Output of `podman version`:**

```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 1.8.2~143 amd64 [installed]
```
